'use strict';

const { C: makeConcept } = require('./definitionFactory');

const C = (...args) => ({ ...makeConcept(...args), family: 'aesthetics' });

const AESTHETICS_DEFINITIONS = [
  // Esthétique fondamentale.
  C('aesthetics.beauty', 'Beauté / Beau', 'aesthetics', 'plato-kant', 'implemented', 'aestheticsService'),
  C('aesthetics.sublime', 'Sublime', 'aesthetics', 'kant-burke-longinus-lyotard', 'implemented', 'aestheticsService'),
  C('aesthetics.aesthetic-experience', 'Expérience esthétique', 'aesthetics', 'dewey-langer', 'implemented', 'aestheticsService'),
  C('aesthetics.taste', 'Goût / Sensus communis', 'aesthetics', 'kant-hume', 'implemented', 'aestheticsService'),
  C('aesthetics.aesthetic-judgment', 'Jugement esthétique', 'aesthetics', 'kant', 'planned'),
  C('aesthetics.universal-subjectivity', 'Subjectivité universelle', 'aesthetics', 'kant', 'planned'),
  C('aesthetics.disinterested-pleasure', 'Plaisir désintéressé', 'aesthetics', 'kant', 'planned'),
  C('aesthetics.purposiveness-without-purpose', 'Finalité sans fin', 'aesthetics', 'kant', 'planned'),
  C('aesthetics.mathematical-sublime', 'Sublime mathématique', 'aesthetics', 'kant', 'planned'),
  C('aesthetics.dynamical-sublime', 'Sublime dynamique', 'aesthetics', 'kant', 'planned'),
  C('aesthetics.postmodern-sublime', 'Sublime postmoderne / Imprésentable', 'aesthetics', 'lyotard-kant', 'planned'),

  // Définitions et théories de l’art.
  C('art.definition', 'Définition de l’art', 'art-theory', 'bell-danto-dickie-gaut-weitz', 'implemented', 'artTheoryService'),
  C('art.significant-form', 'Forme significative', 'art-theory', 'clive-bell-fry', 'implemented', 'artTheoryService'),
  C('art.institutional-theory', 'Théorie institutionnelle de l’art', 'art-theory', 'danto-dickie', 'implemented', 'artTheoryService'),
  C('art.cluster-theory', 'Théorie cluster de l’art', 'art-theory', 'gaut', 'implemented', 'artTheoryService'),
  C('art.open-concept', 'Art comme concept ouvert', 'art-theory', 'weitz', 'implemented', 'artTheoryService'),
  C('art.definition-enigma', 'Énigme de la définition de l’art', 'art-theory', 'analytic-aesthetics', 'implemented', 'artTheoryService'),
  C('art.expressionism', 'Expressionnisme esthétique', 'art-theory', 'croce-collingwood-tolstoy', 'implemented', 'artTheoryService'),
  C('art.mimesis', 'Mimèsis / Imitation', 'art-theory', 'plato-aristotle', 'implemented', 'artTheoryService'),
  C('art.catharsis', 'Catharsis', 'art-theory', 'aristotle', 'implemented', 'artTheoryService'),
  C('art.formalism', 'Formalisme', 'art-theory', 'bell-fry-hanslick', 'implemented', 'artTheoryService'),
  C('art.art-for-art', 'L’art pour l’art / Esthétisme', 'art-theory', 'wilde-pater', 'implemented', 'artTheoryService'),
  C('art.representation', 'Art comme représentation', 'art-theory', 'goodman', 'implemented', 'artTheoryService'),
  C('art.symbol-systems', 'Systèmes symboliques de l’art', 'art-theory', 'goodman', 'implemented', 'artTheoryService'),
  C('art.fictionalism', 'Fictionnalisme artistique', 'art-theory', 'analytic-aesthetics', 'implemented', 'artTheoryService'),
  C('art.fictional-reference', 'Référence fictive', 'art-theory', 'walton-searle', 'implemented', 'artTheoryService'),

  // Interprétation, auteur et intertextualité.
  C('interpretation.artistic', 'Interprétation artistique', 'interpretation', 'dewey-danto-goodman', 'implemented', 'interpretationService'),
  C('interpretation.esthetic-experience', 'Interprétation par l’expérience esthétique', 'interpretation', 'dewey', 'implemented', 'interpretationService'),
  C('interpretation.embodied-meaning', 'Sens incarné', 'interpretation', 'danto', 'implemented', 'interpretationService'),
  C('interpretation.intra-extra-artistic', 'Données intra-artistiques et extra-artistiques', 'interpretation', 'beardsley-thomson', 'implemented', 'interpretationService'),
  C('interpretation.indeterminacy', 'Indétermination interprétative', 'interpretation', 'beardsley-thomson', 'implemented', 'interpretationService'),
  C('interpretation.construction', 'Interprétation comme construction', 'interpretation', 'contemporary', 'implemented', 'interpretationService'),
  C('interpretation.death-of-author', 'Mort de l’auteur', 'interpretation', 'barthes-foucault', 'implemented', 'interpretationService'),
  C('interpretation.author', 'Auteur', 'interpretation', 'barthes-foucault', 'implemented', 'interpretationService'),
  C('interpretation.intertextuality', 'Intertextualité', 'interpretation', 'kristeva-barthes', 'implemented', 'interpretationService'),
  C('interpretation.reference', 'Référence et représentation interprétatives', 'interpretation', 'goodman', 'implemented', 'interpretationService'),

  // Jeu, fiction et narration.
  C('play.play', 'Jeu / Play / Game', 'play', 'huizinga-caillois', 'planned'),
  C('play.magic-circle', 'Cercle magique', 'play', 'huizinga', 'planned'),
  C('play.agon', 'Agôn / Compétition', 'play', 'caillois', 'planned'),
  C('play.alea', 'Aléa / Hasard', 'play', 'caillois', 'planned'),
  C('play.mimicry', 'Mimicry / Simulation', 'play', 'caillois', 'planned'),
  C('play.ilinx', 'Ilinx / Vertige', 'play', 'caillois', 'planned'),
  C('play.serious-games', 'Jeux sérieux', 'play', 'game-studies', 'planned'),
  C('play.game-studies', 'Game studies', 'play', 'contemporary', 'planned'),
  C('narrative.fictionality', 'Fictionnalité', 'narrative', 'walton-currie-searle', 'planned'),
  C('narrative.make-believe', 'Make-believe / Faire-semblant', 'narrative', 'walton', 'planned'),
  C('narrative.props', 'Accessoires fictionnels / Props', 'narrative', 'walton', 'planned'),
  C('narrative.truth-in-fiction', 'Vérité dans la fiction', 'narrative', 'currie-lamarque-olsen', 'planned'),
  C('narrative.fictional-discourse', 'Discours fictionnel', 'narrative', 'searle', 'planned'),
  C('narrative.narration', 'Narration', 'narrative', 'philosophy-of-literature', 'planned'),
  C('narrative.literature', 'Philosophie de la littérature', 'narrative', 'analytic-aesthetics', 'planned'),
  C('narrative.novel', 'Philosophie du roman', 'narrative', 'philosophy-of-literature', 'planned'),

  // Cinéma, musique, architecture et design.
  C('cinema.cinematic-signification', 'Signification cinématographique', 'cinema', 'metz', 'planned'),
  C('cinema.movement-image', 'Image-mouvement', 'cinema', 'deleuze', 'planned'),
  C('cinema.time-image', 'Image-temps', 'cinema', 'deleuze', 'planned'),
  C('cinema.crystal-image', 'Image-cristal', 'cinema', 'deleuze', 'planned'),
  C('cinema.mechanical-reproduction', 'Reproduction mécanique', 'cinema', 'benjamin', 'planned'),
  C('cinema.aura', 'Aura', 'cinema', 'benjamin', 'planned'),
  C('cinema.film-narration', 'Narration filmique', 'cinema', 'bordwell', 'planned'),
  C('cinema.cognitive-theory', 'Théorie cognitive du film', 'cinema', 'bordwell', 'planned'),
  C('cinema.ordinary-language', 'Langage ordinaire au cinéma', 'cinema', 'cavell', 'planned'),
  C('music.musically-beautiful', 'Le beau musical', 'music', 'hanslick', 'planned'),
  C('music.formalism', 'Formalisme musical', 'music', 'hanslick', 'planned'),
  C('music.expression', 'Expression musicale', 'music', 'scruton-adorno', 'planned'),
  C('music.emotion', 'Émotion et musique', 'music', 'meyer', 'planned'),
  C('music.tension-expectation', 'Tension et attente musicales', 'music', 'meyer', 'planned'),
  C('music.autonomous-art', 'Art autonome', 'music', 'adorno', 'planned'),
  C('music.culture-industry', 'Industrie culturelle', 'music', 'adorno', 'planned'),
  C('architecture.philosophy', 'Philosophie de l’architecture', 'architecture', 'aesthetics', 'planned'),
  C('design.philosophy', 'Philosophie du design', 'design', 'aesthetics', 'planned'),
  C('digital-art.philosophy', 'Philosophie de l’art numérique', 'digital-art', 'aesthetics', 'planned'),
  C('video.philosophy', 'Philosophie de la vidéo', 'video', 'aesthetics', 'planned'),

  // Styles et mouvements artistiques.
  C('style.realism', 'Réalisme artistique', 'art-movements', 'realism', 'planned'),
  C('style.naturalism', 'Naturalisme', 'art-movements', 'naturalism', 'planned'),
  C('style.classicism', 'Classicisme', 'art-movements', 'classicism', 'planned'),
  C('style.romanticism', 'Romantisme', 'art-movements', 'romanticism', 'planned'),
  C('style.baroque', 'Baroque', 'art-movements', 'baroque', 'planned'),
  C('style.rococo', 'Rococo', 'art-movements', 'rococo', 'planned'),
  C('style.geometric', 'Géométrie artistique', 'art-movements', 'geometric-abstraction', 'planned'),
  C('style.abstract', 'Art abstrait', 'art-movements', 'abstraction', 'planned'),
  C('style.minimalism', 'Minimalisme', 'art-movements', 'minimalism', 'planned'),
  C('style.maximalism', 'Maximalisme', 'art-movements', 'maximalism', 'planned'),
  C('style.surrealism', 'Surréalisme', 'art-movements', 'surrealism', 'planned'),
  C('style.cubism', 'Cubisme', 'art-movements', 'cubism', 'planned'),
  C('style.futurism', 'Futurisme', 'art-movements', 'futurism', 'planned'),
  C('style.dada', 'Dada', 'art-movements', 'dada', 'planned'),
  C('style.pop-art', 'Pop art', 'art-movements', 'pop-art', 'planned'),
  C('style.conceptual-art', 'Art conceptuel', 'art-movements', 'conceptual-art', 'planned'),
  C('style.performance-art', 'Performance art', 'art-movements', 'performance-art', 'planned'),
  C('style.digital-art', 'Art numérique', 'art-movements', 'digital-art', 'planned'),
  C('style.bioart', 'Bioart', 'art-movements', 'bioart', 'planned'),
  C('style.land-art', 'Land art', 'art-movements', 'land-art', 'planned'),
  C('style.installation', 'Installation', 'art-movements', 'installation-art', 'planned'),
  C('style.cinema', 'Cinéma comme art', 'art-movements', 'cinema', 'planned'),
];

module.exports = { AESTHETICS_DEFINITIONS };
