'use strict';

const { C: makeConcept } = require('./definitionFactory');

const C = (options) => ({ ...makeConcept(options), family: 'aesthetics' });

const AESTHETICS_DEFINITIONS = [
  // Esthétique fondamentale.
  C({ id: 'aesthetics.beauty', label: 'Beauté / Beau', domain: 'aesthetics', school: 'plato-kant', status: 'implemented', service: 'aestheticsService' }),
  C({ id: 'aesthetics.sublime', label: 'Sublime', domain: 'aesthetics', school: 'kant-burke-longinus-lyotard', status: 'implemented', service: 'aestheticsService' }),
  C({ id: 'aesthetics.aesthetic-experience', label: 'Expérience esthétique', domain: 'aesthetics', school: 'dewey-langer', status: 'implemented', service: 'aestheticsService' }),
  C({ id: 'aesthetics.taste', label: 'Goût / Sensus communis', domain: 'aesthetics', school: 'kant-hume', status: 'implemented', service: 'aestheticsService' }),
  C({ id: 'aesthetics.aesthetic-judgment', label: 'Jugement esthétique', domain: 'aesthetics', school: 'kant', status: 'planned' }),
  C({ id: 'aesthetics.universal-subjectivity', label: 'Subjectivité universelle', domain: 'aesthetics', school: 'kant', status: 'planned' }),
  C({ id: 'aesthetics.disinterested-pleasure', label: 'Plaisir désintéressé', domain: 'aesthetics', school: 'kant', status: 'planned' }),
  C({ id: 'aesthetics.purposiveness-without-purpose', label: 'Finalité sans fin', domain: 'aesthetics', school: 'kant', status: 'planned' }),
  C({ id: 'aesthetics.mathematical-sublime', label: 'Sublime mathématique', domain: 'aesthetics', school: 'kant', status: 'planned' }),
  C({ id: 'aesthetics.dynamical-sublime', label: 'Sublime dynamique', domain: 'aesthetics', school: 'kant', status: 'planned' }),
  C({ id: 'aesthetics.postmodern-sublime', label: 'Sublime postmoderne / Imprésentable', domain: 'aesthetics', school: 'lyotard-kant', status: 'planned' }),

  // Définitions et théories de l’art.
  C({ id: 'art.definition', label: 'Définition de l’art', domain: 'art-theory', school: 'bell-danto-dickie-gaut-weitz', status: 'implemented', service: 'artTheoryService' }),
  C({ id: 'art.significant-form', label: 'Forme significative', domain: 'art-theory', school: 'clive-bell-fry', status: 'implemented', service: 'artTheoryService' }),
  C({ id: 'art.institutional-theory', label: 'Théorie institutionnelle de l’art', domain: 'art-theory', school: 'danto-dickie', status: 'implemented', service: 'artTheoryService' }),
  C({ id: 'art.cluster-theory', label: 'Théorie cluster de l’art', domain: 'art-theory', school: 'gaut', status: 'implemented', service: 'artTheoryService' }),
  C({ id: 'art.open-concept', label: 'Art comme concept ouvert', domain: 'art-theory', school: 'weitz', status: 'implemented', service: 'artTheoryService' }),
  C({ id: 'art.definition-enigma', label: 'Énigme de la définition de l’art', domain: 'art-theory', school: 'analytic-aesthetics', status: 'implemented', service: 'artTheoryService' }),
  C({ id: 'art.expressionism', label: 'Expressionnisme esthétique', domain: 'art-theory', school: 'croce-collingwood-tolstoy', status: 'implemented', service: 'artTheoryService' }),
  C({ id: 'art.mimesis', label: 'Mimèsis / Imitation', domain: 'art-theory', school: 'plato-aristotle', status: 'implemented', service: 'artTheoryService' }),
  C({ id: 'art.catharsis', label: 'Catharsis', domain: 'art-theory', school: 'aristotle', status: 'implemented', service: 'artTheoryService' }),
  C({ id: 'art.formalism', label: 'Formalisme', domain: 'art-theory', school: 'bell-fry-hanslick', status: 'implemented', service: 'artTheoryService' }),
  C({ id: 'art.art-for-art', label: 'L’art pour l’art / Esthétisme', domain: 'art-theory', school: 'wilde-pater', status: 'implemented', service: 'artTheoryService' }),
  C({ id: 'art.representation', label: 'Art comme représentation', domain: 'art-theory', school: 'goodman', status: 'implemented', service: 'artTheoryService' }),
  C({ id: 'art.symbol-systems', label: 'Systèmes symboliques de l’art', domain: 'art-theory', school: 'goodman', status: 'implemented', service: 'artTheoryService' }),
  C({ id: 'art.fictionalism', label: 'Fictionnalisme artistique', domain: 'art-theory', school: 'analytic-aesthetics', status: 'implemented', service: 'artTheoryService' }),
  C({ id: 'art.fictional-reference', label: 'Référence fictive', domain: 'art-theory', school: 'walton-searle', status: 'implemented', service: 'artTheoryService' }),

  // Interprétation, auteur et intertextualité.
  C({ id: 'interpretation.artistic', label: 'Interprétation artistique', domain: 'interpretation', school: 'dewey-danto-goodman', status: 'implemented', service: 'interpretationService' }),
  C({ id: 'interpretation.esthetic-experience', label: 'Interprétation par l’expérience esthétique', domain: 'interpretation', school: 'dewey', status: 'implemented', service: 'interpretationService' }),
  C({ id: 'interpretation.embodied-meaning', label: 'Sens incarné', domain: 'interpretation', school: 'danto', status: 'implemented', service: 'interpretationService' }),
  C({ id: 'interpretation.intra-extra-artistic', label: 'Données intra-artistiques et extra-artistiques', domain: 'interpretation', school: 'beardsley-thomson', status: 'implemented', service: 'interpretationService' }),
  C({ id: 'interpretation.indeterminacy', label: 'Indétermination interprétative', domain: 'interpretation', school: 'beardsley-thomson', status: 'implemented', service: 'interpretationService' }),
  C({ id: 'interpretation.construction', label: 'Interprétation comme construction', domain: 'interpretation', school: 'contemporary', status: 'implemented', service: 'interpretationService' }),
  C({ id: 'interpretation.death-of-author', label: 'Mort de l’auteur', domain: 'interpretation', school: 'barthes-foucault', status: 'implemented', service: 'interpretationService' }),
  C({ id: 'interpretation.author', label: 'Auteur', domain: 'interpretation', school: 'barthes-foucault', status: 'implemented', service: 'interpretationService' }),
  C({ id: 'interpretation.intertextuality', label: 'Intertextualité', domain: 'interpretation', school: 'kristeva-barthes', status: 'implemented', service: 'interpretationService' }),
  C({ id: 'interpretation.reference', label: 'Référence et représentation interprétatives', domain: 'interpretation', school: 'goodman', status: 'implemented', service: 'interpretationService' }),

  // Jeu, fiction et narration.
  C({ id: 'play.play', label: 'Jeu / Play / Game', domain: 'play', school: 'huizinga-caillois', status: 'implemented', service: 'playNarrativeService' }),
  C({ id: 'play.magic-circle', label: 'Cercle magique', domain: 'play', school: 'huizinga', status: 'implemented', service: 'playNarrativeService' }),
  C({ id: 'play.agon', label: 'Agôn / Compétition', domain: 'play', school: 'caillois', status: 'implemented', service: 'playNarrativeService' }),
  C({ id: 'play.alea', label: 'Aléa / Hasard', domain: 'play', school: 'caillois', status: 'implemented', service: 'playNarrativeService' }),
  C({ id: 'play.mimicry', label: 'Mimicry / Simulation', domain: 'play', school: 'caillois', status: 'implemented', service: 'playNarrativeService' }),
  C({ id: 'play.ilinx', label: 'Ilinx / Vertige', domain: 'play', school: 'caillois', status: 'implemented', service: 'playNarrativeService' }),
  C({ id: 'play.serious-games', label: 'Jeux sérieux', domain: 'play', school: 'game-studies', status: 'implemented', service: 'playNarrativeService' }),
  C({ id: 'play.game-studies', label: 'Game studies', domain: 'play', school: 'contemporary', status: 'implemented', service: 'playNarrativeService' }),
  C({ id: 'narrative.fictionality', label: 'Fictionnalité', domain: 'narrative', school: 'walton-currie-searle', status: 'implemented', service: 'playNarrativeService' }),
  C({ id: 'narrative.make-believe', label: 'Make-believe / Faire-semblant', domain: 'narrative', school: 'walton', status: 'implemented', service: 'playNarrativeService' }),
  C({ id: 'narrative.props', label: 'Accessoires fictionnels / Props', domain: 'narrative', school: 'walton', status: 'implemented', service: 'playNarrativeService' }),
  C({ id: 'narrative.truth-in-fiction', label: 'Vérité dans la fiction', domain: 'narrative', school: 'currie-lamarque-olsen', status: 'implemented', service: 'playNarrativeService' }),
  C({ id: 'narrative.fictional-discourse', label: 'Discours fictionnel', domain: 'narrative', school: 'searle', status: 'implemented', service: 'playNarrativeService' }),
  C({ id: 'narrative.narration', label: 'Narration', domain: 'narrative', school: 'philosophy-of-literature', status: 'implemented', service: 'playNarrativeService' }),
  C({ id: 'narrative.literature', label: 'Philosophie de la littérature', domain: 'narrative', school: 'analytic-aesthetics', status: 'implemented', service: 'playNarrativeService' }),
  C({ id: 'narrative.novel', label: 'Philosophie du roman', domain: 'narrative', school: 'philosophy-of-literature', status: 'implemented', service: 'playNarrativeService' }),

  // Cinéma, musique, architecture et design.
  C({ id: 'cinema.cinematic-signification', label: 'Signification cinématographique', domain: 'cinema', school: 'metz', status: 'implemented', service: 'cinemaMusicService' }),
  C({ id: 'cinema.movement-image', label: 'Image-mouvement', domain: 'cinema', school: 'deleuze', status: 'implemented', service: 'cinemaMusicService' }),
  C({ id: 'cinema.time-image', label: 'Image-temps', domain: 'cinema', school: 'deleuze', status: 'implemented', service: 'cinemaMusicService' }),
  C({ id: 'cinema.crystal-image', label: 'Image-cristal', domain: 'cinema', school: 'deleuze', status: 'implemented', service: 'cinemaMusicService' }),
  C({ id: 'cinema.mechanical-reproduction', label: 'Reproduction mécanique', domain: 'cinema', school: 'benjamin', status: 'implemented', service: 'cinemaMusicService' }),
  C({ id: 'cinema.aura', label: 'Aura', domain: 'cinema', school: 'benjamin', status: 'implemented', service: 'cinemaMusicService' }),
  C({ id: 'cinema.film-narration', label: 'Narration filmique', domain: 'cinema', school: 'bordwell', status: 'implemented', service: 'cinemaMusicService' }),
  C({ id: 'cinema.cognitive-theory', label: 'Théorie cognitive du film', domain: 'cinema', school: 'bordwell', status: 'implemented', service: 'cinemaMusicService' }),
  C({ id: 'cinema.ordinary-language', label: 'Langage ordinaire au cinéma', domain: 'cinema', school: 'cavell', status: 'implemented', service: 'cinemaMusicService' }),
  C({ id: 'music.musically-beautiful', label: 'Le beau musical', domain: 'music', school: 'hanslick', status: 'implemented', service: 'cinemaMusicService' }),
  C({ id: 'music.formalism', label: 'Formalisme musical', domain: 'music', school: 'hanslick', status: 'implemented', service: 'cinemaMusicService' }),
  C({ id: 'music.expression', label: 'Expression musicale', domain: 'music', school: 'scruton-adorno', status: 'implemented', service: 'cinemaMusicService' }),
  C({ id: 'music.emotion', label: 'Émotion et musique', domain: 'music', school: 'meyer', status: 'implemented', service: 'cinemaMusicService' }),
  C({ id: 'music.tension-expectation', label: 'Tension et attente musicales', domain: 'music', school: 'meyer', status: 'implemented', service: 'cinemaMusicService' }),
  C({ id: 'music.autonomous-art', label: 'Art autonome', domain: 'music', school: 'adorno', status: 'implemented', service: 'cinemaMusicService' }),
  C({ id: 'music.culture-industry', label: 'Industrie culturelle', domain: 'music', school: 'adorno', status: 'implemented', service: 'cinemaMusicService' }),
  C({ id: 'architecture.philosophy', label: 'Philosophie de l’architecture', domain: 'architecture', school: 'aesthetics', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'design.philosophy', label: 'Philosophie du design', domain: 'design', school: 'aesthetics', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'digital-art.philosophy', label: 'Philosophie de l’art numérique', domain: 'digital-art', school: 'aesthetics', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'video.philosophy', label: 'Philosophie de la vidéo', domain: 'video', school: 'aesthetics', status: 'implemented', service: 'visualCultureService' }),

  // Styles et mouvements artistiques.
  C({ id: 'style.realism', label: 'Réalisme artistique', domain: 'art-movements', school: 'realism', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.naturalism', label: 'Naturalisme', domain: 'art-movements', school: 'naturalism', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.classicism', label: 'Classicisme', domain: 'art-movements', school: 'classicism', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.romanticism', label: 'Romantisme', domain: 'art-movements', school: 'romanticism', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.baroque', label: 'Baroque', domain: 'art-movements', school: 'baroque', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.rococo', label: 'Rococo', domain: 'art-movements', school: 'rococo', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.geometric', label: 'Géométrie artistique', domain: 'art-movements', school: 'geometric-abstraction', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.abstract', label: 'Art abstrait', domain: 'art-movements', school: 'abstraction', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.minimalism', label: 'Minimalisme', domain: 'art-movements', school: 'minimalism', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.maximalism', label: 'Maximalisme', domain: 'art-movements', school: 'maximalism', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.surrealism', label: 'Surréalisme', domain: 'art-movements', school: 'surrealism', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.cubism', label: 'Cubisme', domain: 'art-movements', school: 'cubism', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.futurism', label: 'Futurisme', domain: 'art-movements', school: 'futurism', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.dada', label: 'Dada', domain: 'art-movements', school: 'dada', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.pop-art', label: 'Pop art', domain: 'art-movements', school: 'pop-art', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.conceptual-art', label: 'Art conceptuel', domain: 'art-movements', school: 'conceptual-art', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.performance-art', label: 'Performance art', domain: 'art-movements', school: 'performance-art', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.digital-art', label: 'Art numérique', domain: 'art-movements', school: 'digital-art', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.bioart', label: 'Bioart', domain: 'art-movements', school: 'bioart', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.land-art', label: 'Land art', domain: 'art-movements', school: 'land-art', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.installation', label: 'Installation', domain: 'art-movements', school: 'installation-art', status: 'implemented', service: 'visualCultureService' }),
  C({ id: 'style.cinema', label: 'Cinéma comme art', domain: 'art-movements', school: 'cinema', status: 'implemented', service: 'visualCultureService' }),
];

module.exports = { AESTHETICS_DEFINITIONS };
