'use strict';

const { C } = require('./definitionFactory');

const CORE_DEFINITIONS = [
  C({ id: 'ontology.being', label: 'Être / Being / ensoma', domain: 'ontology', school: 'general', status: 'implemented', service: 'ontologyCore' }),
  C({ id: 'ontology.substance', label: 'Substance / Sostanza', domain: 'ontology', school: 'aristotle-spinoza-descartes', status: 'implemented', service: 'substanceService' }),
  C({ id: 'ontology.attribute', label: 'Attribut / Propriété', domain: 'ontology', school: 'general', status: 'implemented', service: 'ontologyAttributes' }),
  C({ id: 'ontology.mode', label: 'Mode / Modalité', domain: 'ontology', school: 'general', status: 'implemented', service: 'ontologyModes' }),
  C({ id: 'ontology.essence-accident', label: 'Essentia / Accident', domain: 'ontology', school: 'aristotle-scholastic', status: 'implemented', service: 'ontologyAttributes' }),
  C({ id: 'ontology.hypostatization', label: 'Hypostatisation', domain: 'ontology', school: 'scholastic', status: 'implemented', service: 'ontologyHypostatization' }),
  C({ id: 'ontology.stances', label: 'Réalisme / Nominalisme / Conceptualisme', domain: 'ontology', school: 'medieval-modern', status: 'implemented', service: 'ontologyStances' }),
  C({ id: 'ontology.identity-change', label: 'Identité et changement', domain: 'ontology', school: 'locke', status: 'implemented', service: 'temporalIdentityService' }),
  C({ id: 'ontology.person-other', label: 'Personne / Autrui / Altérité', domain: 'ontology', school: 'levinas', status: 'planned' }),
  C({ id: 'ontology.whole-void-infinite', label: 'Tout / Vide / Infini', domain: 'ontology', school: 'metaphysics', status: 'partial' }),
  C({ id: 'ontology.continuous-discrete', label: 'Continu / Discontinu', domain: 'ontology', school: 'metaphysics', status: 'planned' }),
  C({ id: 'ontology.possible-worlds', label: 'Mondes possibles / Possibilia', domain: 'modality', school: 'leibniz-kripke', status: 'planned' }),
  C({ id: 'ontology.contingency-necessity', label: 'Contingence / Nécessité logique et métaphysique', domain: 'modality', school: 'modal-metaphysics', status: 'partial', service: 'contingencyService' }),
  C({ id: 'school.platonism', label: 'Platonisme : formes idéales', domain: 'schools', school: 'plato', status: 'implemented', service: 'platonismService' }),
  C({ id: 'school.aristotelianism', label: 'Aristotélisme : catégories et causes', domain: 'schools', school: 'aristotle', status: 'implemented', service: 'aristotelianService' }),
  C({ id: 'school.stoicism', label: 'Stoïcisme : monisme, logos, fate', domain: 'schools', school: 'stoicism', status: 'implemented', service: 'stoicismService' }),
  C({ id: 'school.epicureanism', label: 'Épicurisme : atomes, vide, sensations', domain: 'schools', school: 'epicurus', status: 'implemented', service: 'epicureanService' }),
  C({ id: 'school.scholasticism', label: 'Scholastique : équivocité, analogie, univocité', domain: 'schools', school: 'scholastic', status: 'implemented', service: 'scholastiqueService' }),
  C({ id: 'school.cartesianism', label: 'Cartesianisme : res cogitans / res extensa', domain: 'schools', school: 'descartes', status: 'implemented', service: 'cartesianService' }),
  C({ id: 'school.leibnizianism', label: 'Leibniz : monades et harmonie préétablie', domain: 'schools', school: 'leibniz', status: 'implemented', service: 'leibnizianService' }),
  C({ id: 'school.spinozism', label: 'Spinozisme : Deus sive Natura et conatus', domain: 'schools', school: 'spinoza', status: 'implemented', service: 'spinozaService' }),
  C({ id: 'school.newtonianism', label: 'Newton : espace et temps absolus', domain: 'schools', school: 'newton', status: 'implemented', service: 'newtonianService' }),
  C({ id: 'school.kantianism', label: 'Kant : noumène, phénomène, catégories a priori', domain: 'schools', school: 'kant', status: 'implemented', service: 'kantianService' }),
  C({ id: 'school.hegelianism', label: 'Hegel : dialectique et Absolute Geist', domain: 'schools', school: 'hegel', status: 'implemented', service: 'hegelianService' }),
  C({ id: 'school.schopenhauer', label: 'Schopenhauer : volonté et représentation', domain: 'schools', school: 'schopenhauer', status: 'implemented', service: 'schopenhauerService' }),
  C({ id: 'school.nietzsche', label: 'Nietzsche : volonté de puissance et éternel retour', domain: 'schools', school: 'nietzsche', status: 'implemented', service: 'nietzscheService' }),
  C({ id: 'school.bergsonism', label: 'Bergson : durée, élan vital, intuition', domain: 'schools', school: 'bergson', status: 'implemented', service: 'bergsonService' }),
  C({ id: 'school.whitehead', label: 'Whitehead : processus, actualité, potentialité', domain: 'schools', school: 'whitehead', status: 'implemented', service: 'processPhilosophyService' }),
  C({ id: 'school.heidegger', label: 'Heidegger : Être-et-Temps, Sein, Dasein', domain: 'schools', school: 'heidegger', status: 'implemented', service: 'processPhilosophyService' }),
  C({ id: 'school.sartre', label: 'Sartre : existence, essence, mauvaise foi', domain: 'schools', school: 'sartre', status: 'implemented', service: 'phenomenologyService' }),
  C({ id: 'school.merleau-ponty', label: 'Merleau-Ponty : phénoménologie de la perception', domain: 'schools', school: 'merleau-ponty', status: 'implemented', service: 'phenomenologyService' }),
  C({ id: 'school.deleuze', label: 'Deleuze : différence, répétition, rhizome', domain: 'schools', school: 'deleuze', status: 'implemented', service: 'processPhilosophyService' }),
  C({ id: 'school.badiou', label: 'Badiou : événement, vérité, mathématiques de l’être', domain: 'schools', school: 'badiou', status: 'implemented', service: 'contingencyService' }),
  C({ id: 'school.meillassoux', label: 'Meillassoux : contingence absolue', domain: 'schools', school: 'meillassoux', status: 'implemented', service: 'contingencyService' }),
  C({ id: 'school.speculative-realism', label: 'Réalisme spéculatif : corrélationisme, accessibilité', domain: 'schools', school: 'speculative-realism', status: 'planned' }),
  C({ id: 'metaphysics.monism-idealism', label: 'Monisme idéaliste', domain: 'metaphysics', school: 'berkeley-hegel', status: 'planned' }),
  C({ id: 'metaphysics.dualism', label: 'Dualisme des substances', domain: 'metaphysics', school: 'descartes', status: 'implemented', service: 'cartesianService' }),
  C({ id: 'metaphysics.material-monism', label: 'Monisme matériel / Physicalisme', domain: 'metaphysics', school: 'physicalism', status: 'partial', service: 'propertyService' }),
  C({ id: 'metaphysics.panpsychism', label: 'Panpsychisme / Panexperientialisme', domain: 'metaphysics', school: 'contemporary', status: 'planned' }),
  C({ id: 'metaphysics.eliminativism', label: 'Éliminativisme matérialiste', domain: 'metaphysics', school: 'churchland', status: 'planned' }),
  C({ id: 'metaphysics.reductionism', label: 'Réductionnisme', domain: 'metaphysics', school: 'analytic', status: 'partial', service: 'propertyService' }),
  C({ id: 'metaphysics.emergence', label: 'Émergence / propriété émergente', domain: 'metaphysics', school: 'analytic', status: 'implemented', service: 'propertyService' }),
  C({ id: 'metaphysics.supervenience', label: 'Supervenience / supervenience psychophysique', domain: 'metaphysics', school: 'analytic', status: 'implemented', service: 'propertyService' }),
  C({ id: 'metaphysics.second-order-properties', label: 'Propriétés de deuxième ordre', domain: 'metaphysics', school: 'analytic', status: 'planned' }),
  C({ id: 'metaphysics.mind-body', label: 'Matière, esprit, conscience et problème corps-esprit', domain: 'metaphysics', school: 'mind-body', status: 'partial', service: 'consciousnessService' }),
  C({ id: 'metaphysics.qualia', label: 'Qualia', domain: 'phenomenology', school: 'contemporary', status: 'implemented', service: 'consciousnessService' }),
  C({ id: 'metaphysics.cartesian-pineal', label: 'Épine / glande pinéale de Descartes', domain: 'metaphysics', school: 'descartes', status: 'implemented', service: 'cartesianService' }),
  C({ id: 'metaphysics.reference-intentionality', label: 'Référence et intentionnalité', domain: 'phenomenology', school: 'brentano-husserl', status: 'implemented', service: 'phenomenologyService' }),
  C({ id: 'causality.determination', label: 'Détermination / Causalité', domain: 'causality', school: 'general', status: 'implemented', service: 'causalityService' }),
  C({ id: 'causality.hume-regularity', label: 'Loi et régularité causationnelles : Hume', domain: 'causality', school: 'hume', status: 'implemented', service: 'causalityService' }),
  C({ id: 'causality.counterfactuals', label: 'Conditionnels contrefactuels', domain: 'causality', school: 'lewis', status: 'implemented', service: 'causalityService' }),
  C({ id: 'causality.determinism-indeterminism', label: 'Déterminisme / Indéterminisme', domain: 'causality', school: 'metaphysics', status: 'implemented', service: 'causalityService' }),
  C({ id: 'causality.fatalism', label: 'Fatalisme', domain: 'causality', school: 'stoicism', status: 'implemented', service: 'stoicismService' }),
  C({ id: 'causality.free-will', label: 'Libre arbitre, compatibilisme, incompatibilisme, libertarianisme', domain: 'causality', school: 'analytic', status: 'implemented', service: 'causalityService' }),
  C({ id: 'time.newtonian', label: 'Temps absolu et espace absolu', domain: 'time-space', school: 'newton', status: 'implemented', service: 'newtonianService' }),
  C({ id: 'time.duration', label: 'Temps et durée', domain: 'time-space', school: 'bergson-mctaggart', status: 'implemented', service: 'bergsonService' }),
  C({ id: 'time.a-series-b-series', label: 'A-series / B-series', domain: 'time-space', school: 'mctaggart', status: 'implemented', service: 'temporalIdentityService' }),
  C({ id: 'time.block-universe', label: 'Bloc univers : éternalisme / présentisme', domain: 'time-space', school: 'contemporary', status: 'implemented', service: 'temporalIdentityService' }),
  C({ id: 'time.arrow', label: 'Flèche du temps / asymétrie temporelle', domain: 'time-space', school: 'physics', status: 'implemented', service: 'temporalIdentityService' }),
  C({ id: 'time.spacetime-relativity', label: 'Espace-temps relativiste', domain: 'time-space', school: 'einstein', status: 'implemented', service: 'temporalIdentityService' }),
  C({ id: 'process.actuality-potentiality', label: 'Actualité / Potentialité', domain: 'process', school: 'whitehead-aristotle', status: 'implemented', service: 'processPhilosophyService' }),
  C({ id: 'process.bergsonian-vital-impulse', label: 'Durée / Élan vital / Intuition', domain: 'process', school: 'bergson', status: 'implemented', service: 'bergsonService' }),
  C({ id: 'process.heidegger-dasein', label: 'Sein / Dasein / Être-et-Temps', domain: 'process', school: 'heidegger', status: 'implemented', service: 'processPhilosophyService' }),
  C({ id: 'process.deleuze-difference', label: 'Différence / Répétition / Rhizome', domain: 'process', school: 'deleuze', status: 'implemented', service: 'processPhilosophyService' }),
  C({ id: 'process.badiou-event', label: 'Événement / Vérité', domain: 'process', school: 'badiou', status: 'implemented', service: 'contingencyService' }),
  C({ id: 'process.sartrean-existence', label: 'Existence précède essence / mauvaise foi', domain: 'process', school: 'sartre', status: 'implemented', service: 'phenomenologyService' }),
];

module.exports = { CORE_DEFINITIONS };
