'use strict';

const { C } = require('./definitionFactory');

const CORE_DEFINITIONS = [
  C({
    id: 'core.self',
    label: 'Soi / Self',
    domain: 'identity',
    school: 'general',
    status: 'implemented',
    service: 'identityService',
    role: 'core',
    runtimeAuthority: true,
    falsifiable: true,
    scope: 'Conception opérationnelle du soi comme processus versionné, pas comme substance.',
    knownLimits: [
      'Le soi opérationnel de GenOS n\'est pas une identité personnelle au sens philosophique.',
      'Il décrit un ThreadLocal + DB row + lineage, pas l\'unité phénoménale d\'un sujet.',
    ],
    historicalConfidence: 1,
  }),
  C({
    id: 'core.agent',
    label: 'Agent / agentic process',
    domain: 'identity',
    school: 'general',
    status: 'implemented',
    service: 'agentService',
    role: 'core',
    runtimeAuthority: true,
    falsifiable: true,
    scope: 'Processus agentique exécutable dans GenOS : genome + état + compréhensions + horizon.',
    knownLimits: [
      'Ce n\'est pas un agent au sens AGI.',
      'C\'est un exécutant versionné avec des primitives définies, pas une personne.',
    ],
    historicalConfidence: 1,
  }),
  C({
    id: 'core.lineage',
    label: 'Lignée / Lineage',
    domain: 'identity',
    school: 'general',
    status: 'implemented',
    service: 'lineageService',
    role: 'core',
    runtimeAuthority: true,
    falsifiable: true,
    scope: 'Relation de descendance entre versions d\'un même processus agentique.',
    knownLimits: [
      'La lignée documente la continuité historique, pas l\'identité substantielle.',
      'Un fork rompt la lignée par défaut ; la continuité fonctionnelle reste à évaluer.',
    ],
    historicalConfidence: 1,
  }),
  C({
    id: 'core.genome',
    label: 'Génome / Genome',
    domain: 'identity',
    school: 'general',
    status: 'implemented',
    service: 'genomeService',
    role: 'core',
    runtimeAuthority: true,
    falsifiable: true,
    scope: 'Spécification exécutable en attente de résolution d\'identité ; la résolution est le service.',
    knownLimits: [
      'Le génome n\'est pas un ADN biologique ; c\'est un enregistrement structuré.',
      'Son interprétation dépend du runtime et peut évoluer sans modifier l\'identité de la lignée.',
    ],
    historicalConfidence: 1,
  }),
  C({
    id: 'core.environment',
    label: 'Environnement / Environment',
    domain: 'cognition',
    school: 'general',
    status: 'implemented',
    service: 'environmentService',
    role: 'core',
    runtimeAuthority: true,
    falsifiable: true,
    scope: 'Ensemble des ressources, contraintes et contexte accessible à un agent dans une exécution.',
    knownLimits: [
      'L\'environnement d\'exécution n\'est pas le monde physique.',
      'Sa modélisation est toujours partielle et instrumentation-dépendante.',
    ],
    historicalConfidence: 1,
  }),
  C({
    id: 'core.history',
    label: 'Histoire / History',
    domain: 'identity',
    school: 'general',
    status: 'implemented',
    service: 'historyService',
    role: 'core',
    runtimeAuthority: true,
    falsifiable: true,
    scope: 'Séquence des événements et des versions produits par un processus agentique.',
    knownLimits: [
      'L\'histoire est un artefact de journalisation, pas la trace phénoménologique d\'un sujet.',
      'Une exécution peut être partiellement ou non journalisée.',
    ],
    historicalConfidence: 1,
  }),
  C({
    id: 'core.trait',
    label: 'Sous-tâche / Sub-trait',
    domain: 'process',
    school: 'general',
    status: 'implemented',
    service: 'traitService',
    role: 'core',
    runtimeAuthority: true,
    falsifiable: true,
    scope: 'Sous-tâche nommée et réutilisable à l\'intérieur d\'une mission.',
    knownLimits: [
      'Un sous-tâche n\'a pas de vie autonome ; il dépend du parent.',
      'Son interface est contrainte par le runtime, pas par une théorie philosophique.',
    ],
    historicalConfidence: 1,
  }),
];

module.exports = { CORE_DEFINITIONS };