'use strict';

const { C } = require('./definitionFactory');

const CORE_DEFINITIONS = [
  C('ontology.being', 'Être / Being / ensoma', 'ontology', 'general', 'implemented', 'ontologyCore'),
  C('ontology.substance', 'Substance / Sostanza', 'ontology', 'aristotle-spinoza-descartes', 'implemented', 'substanceService'),
  C('ontology.attribute', 'Attribut / Propriété', 'ontology', 'general', 'implemented', 'ontologyAttributes'),
  C('ontology.mode', 'Mode / Modalité', 'ontology', 'general', 'implemented', 'ontologyModes'),
  C('ontology.essence-accident', 'Essentia / Accident', 'ontology', 'aristotle-scholastic', 'implemented', 'ontologyAttributes'),
  C('ontology.hypostatization', 'Hypostatisation', 'ontology', 'scholastic', 'implemented', 'ontologyHypostatization'),
  C('ontology.stances', 'Réalisme / Nominalisme / Conceptualisme', 'ontology', 'medieval-modern', 'implemented', 'ontologyStances'),
  C('ontology.identity-change', 'Identité et changement', 'ontology', 'locke', 'implemented', 'temporalIdentityService'),
  C('ontology.person-other', 'Personne / Autrui / Altérité', 'ontology', 'levinas', 'planned'),
  C('ontology.whole-void-infinite', 'Tout / Vide / Infini', 'ontology', 'metaphysics', 'partial'),
  C('ontology.continuous-discrete', 'Continu / Discontinu', 'ontology', 'metaphysics', 'planned'),
  C('ontology.possible-worlds', 'Mondes possibles / Possibilia', 'modality', 'leibniz-kripke', 'planned'),
  C('ontology.contingency-necessity', 'Contingence / Nécessité logique et métaphysique', 'modality', 'modal-metaphysics', 'partial', 'contingencyService'),
  C('school.platonism', 'Platonisme : formes idéales', 'schools', 'plato', 'implemented', 'platonismService'),
  C('school.aristotelianism', 'Aristotélisme : catégories et causes', 'schools', 'aristotle', 'implemented', 'aristotelianService'),
  C('school.stoicism', 'Stoïcisme : monisme, logos, fate', 'schools', 'stoicism', 'implemented', 'stoicismService'),
  C('school.epicureanism', 'Épicurisme : atomes, vide, sensations', 'schools', 'epicurus', 'implemented', 'epicureanService'),
  C('school.scholasticism', 'Scholastique : équivocité, analogie, univocité', 'schools', 'scholastic', 'implemented', 'scholastiqueService'),
  C('school.cartesianism', 'Cartesianisme : res cogitans / res extensa', 'schools', 'descartes', 'implemented', 'cartesianService'),
  C('school.leibnizianism', 'Leibniz : monades et harmonie préétablie', 'schools', 'leibniz', 'implemented', 'leibnizianService'),
  C('school.spinozism', 'Spinozisme : Deus sive Natura et conatus', 'schools', 'spinoza', 'implemented', 'spinozaService'),
  C('school.newtonianism', 'Newton : espace et temps absolus', 'schools', 'newton', 'implemented', 'newtonianService'),
  C('school.kantianism', 'Kant : noumène, phénomène, catégories a priori', 'schools', 'kant', 'implemented', 'kantianService'),
  C('school.hegelianism', 'Hegel : dialectique et Absolute Geist', 'schools', 'hegel', 'implemented', 'hegelianService'),
  C('school.schopenhauer', 'Schopenhauer : volonté et représentation', 'schools', 'schopenhauer', 'implemented', 'schopenhauerService'),
  C('school.nietzsche', 'Nietzsche : volonté de puissance et éternel retour', 'schools', 'nietzsche', 'implemented', 'nietzscheService'),
  C('school.bergsonism', 'Bergson : durée, élan vital, intuition', 'schools', 'bergson', 'implemented', 'bergsonService'),
  C('school.whitehead', 'Whitehead : processus, actualité, potentialité', 'schools', 'whitehead', 'implemented', 'processPhilosophyService'),
  C('school.heidegger', 'Heidegger : Être-et-Temps, Sein, Dasein', 'schools', 'heidegger', 'implemented', 'processPhilosophyService'),
  C('school.sartre', 'Sartre : existence, essence, mauvaise foi', 'schools', 'sartre', 'implemented', 'phenomenologyService'),
  C('school.merleau-ponty', 'Merleau-Ponty : phénoménologie de la perception', 'schools', 'merleau-ponty', 'implemented', 'phenomenologyService'),
  C('school.deleuze', 'Deleuze : différence, répétition, rhizome', 'schools', 'deleuze', 'implemented', 'processPhilosophyService'),
  C('school.badiou', 'Badiou : événement, vérité, mathématiques de l’être', 'schools', 'badiou', 'implemented', 'contingencyService'),
  C('school.meillassoux', 'Meillassoux : contingence absolue', 'schools', 'meillassoux', 'implemented', 'contingencyService'),
  C('school.speculative-realism', 'Réalisme spéculatif : corrélationisme, accessibilité', 'schools', 'speculative-realism', 'planned'),
  C('metaphysics.monism-idealism', 'Monisme idéaliste', 'metaphysics', 'berkeley-hegel', 'planned'),
  C('metaphysics.dualism', 'Dualisme des substances', 'metaphysics', 'descartes', 'implemented', 'cartesianService'),
  C('metaphysics.material-monism', 'Monisme matériel / Physicalisme', 'metaphysics', 'physicalism', 'partial', 'propertyService'),
  C('metaphysics.panpsychism', 'Panpsychisme / Panexperientialisme', 'metaphysics', 'contemporary', 'planned'),
  C('metaphysics.eliminativism', 'Éliminativisme matérialiste', 'metaphysics', 'churchland', 'planned'),
  C('metaphysics.reductionism', 'Réductionnisme', 'metaphysics', 'analytic', 'partial', 'propertyService'),
  C('metaphysics.emergence', 'Émergence / propriété émergente', 'metaphysics', 'analytic', 'implemented', 'propertyService'),
  C('metaphysics.supervenience', 'Supervenience / supervenience psychophysique', 'metaphysics', 'analytic', 'implemented', 'propertyService'),
  C('metaphysics.second-order-properties', 'Propriétés de deuxième ordre', 'metaphysics', 'analytic', 'planned'),
  C('metaphysics.mind-body', 'Matière, esprit, conscience et problème corps-esprit', 'metaphysics', 'mind-body', 'partial', 'consciousnessService'),
  C('metaphysics.qualia', 'Qualia', 'phenomenology', 'contemporary', 'implemented', 'consciousnessService'),
  C('metaphysics.cartesian-pineal', 'Épine / glande pinéale de Descartes', 'metaphysics', 'descartes', 'implemented', 'cartesianService'),
  C('metaphysics.reference-intentionality', 'Référence et intentionnalité', 'phenomenology', 'brentano-husserl', 'implemented', 'phenomenologyService'),
  C('causality.determination', 'Détermination / Causalité', 'causality', 'general', 'implemented', 'causalityService'),
  C('causality.hume-regularity', 'Loi et régularité causationnelles : Hume', 'causality', 'hume', 'partial', 'causalityService'),
  C('causality.counterfactuals', 'Conditionnels contrefactuels', 'causality', 'lewis', 'planned'),
  C('causality.determinism-indeterminism', 'Déterminisme / Indéterminisme', 'causality', 'metaphysics', 'partial', 'causalityService'),
  C('causality.fatalism', 'Fatalisme', 'causality', 'stoicism', 'implemented', 'stoicismService'),
  C('causality.free-will', 'Libre arbitre, compatibilisme, incompatibilisme, libertarianisme', 'causality', 'analytic', 'planned'),
  C('time.newtonian', 'Temps absolu et espace absolu', 'time-space', 'newton', 'implemented', 'newtonianService'),
  C('time.duration', 'Temps et durée', 'time-space', 'bergson-mctaggart', 'implemented', 'bergsonService'),
  C('time.a-series-b-series', 'A-series / B-series', 'time-space', 'mctaggart', 'implemented', 'temporalIdentityService'),
  C('time.block-universe', 'Bloc univers : éternalisme / présentisme', 'time-space', 'contemporary', 'planned'),
  C('time.arrow', 'Flèche du temps / asymétrie temporelle', 'time-space', 'physics', 'planned'),
  C('time.spacetime-relativity', 'Espace-temps relativiste', 'time-space', 'einstein', 'planned'),
  C('process.actuality-potentiality', 'Actualité / Potentialité', 'process', 'whitehead-aristotle', 'implemented', 'processPhilosophyService'),
  C('process.bergsonian-vital-impulse', 'Durée / Élan vital / Intuition', 'process', 'bergson', 'implemented', 'bergsonService'),
  C('process.heidegger-dasein', 'Sein / Dasein / Être-et-Temps', 'process', 'heidegger', 'implemented', 'processPhilosophyService'),
  C('process.deleuze-difference', 'Différence / Répétition / Rhizome', 'process', 'deleuze', 'implemented', 'processPhilosophyService'),
  C('process.badiou-event', 'Événement / Vérité', 'process', 'badiou', 'implemented', 'contingencyService'),
  C('process.sartrean-existence', 'Existence précède essence / mauvaise foi', 'process', 'sartre', 'implemented', 'phenomenologyService'),
];

module.exports = { CORE_DEFINITIONS };
