'use strict';

const L = ({ id, label, domain, school, service = null, metadata = {} }) => ({
  id, label, domain, school, status: service ? 'partial' : 'planned', service,
  family: metadata.family || domain,
  definition: metadata.definition || label,
  genosDomains: metadata.genosDomains || ['computation', 'epistemics'],
  aliases: metadata.aliases || [],
  relations: metadata.relations || [],
  evidenceLevel: service ? 'operational' : 'philosophical'
});

const LOGIC_DEFINITIONS = [
  L({ id: 'logic.propositional', label: 'Logique propositionnelle', domain: 'logic', school: 'classical', service: 'propositionalLogicService' }),
  L({ id: 'logic.negation', label: 'Négation', domain: 'logic', school: 'classical', service: 'propositionalLogicService' }),
  L({ id: 'logic.conjunction', label: 'Conjonction', domain: 'logic', school: 'classical', service: 'propositionalLogicService' }),
  L({ id: 'logic.disjunction', label: 'Disjonction', domain: 'logic', school: 'classical', service: 'propositionalLogicService' }),
  L({ id: 'logic.material-conditional', label: 'Implication matérielle', domain: 'logic', school: 'classical', service: 'propositionalLogicService' }),
  L({ id: 'logic.biconditional', label: 'Biconditionnelle', domain: 'logic', school: 'classical', service: 'propositionalLogicService' }),
  L({ id: 'logic.truth-table', label: 'Table de vérité', domain: 'logic', school: 'classical', service: 'propositionalLogicService' }),
  L({ id: 'logic.tautology', label: 'Tautologie', domain: 'logic', school: 'classical', service: 'propositionalLogicService' }),
  L({ id: 'logic.contradiction', label: 'Contradiction', domain: 'logic', school: 'classical', service: 'propositionalLogicService' }),
  L({ id: 'logic.equivalence', label: 'Équivalence logique', domain: 'logic', school: 'classical', service: 'propositionalLogicService' }),
  L({ id: 'logic.first-order', label: 'Logique du premier ordre', domain: 'logic', school: 'frege-godel', service: null }),
  L({ id: 'logic.quantifier', label: 'Quantificateurs universel et existentiel', domain: 'logic', school: 'first-order', service: null }),
  L({ id: 'logic.satisfiability', label: 'Satisfiabilité', domain: 'logic', school: 'model-theory', service: null }),
  L({ id: 'logic.modal', label: 'Logique modale', domain: 'logic', school: 'kripke', service: null }),
  L({ id: 'logic.possible-worlds', label: 'Sémantique des mondes possibles', domain: 'logic', school: 'leibniz-kripke', service: null }),
  L({ id: 'logic.kripke-frame', label: 'Cadre de Kripke', domain: 'logic', school: 'kripke', service: null }),
  L({ id: 'logic.temporal', label: 'Logique temporelle', domain: 'logic', school: 'prior', service: null }),
  L({ id: 'logic.epistemic', label: 'Logique épistémique', domain: 'logic', school: 'hintikka', service: null }),
  L({ id: 'logic.deontic', label: 'Logique déontique', domain: 'logic', school: 'von-wright', service: null }),
  L({ id: 'logic.dynamic', label: 'Logique dynamique et annonces publiques', domain: 'logic', school: 'baltag-moss-solecki', service: null }),
  L({ id: 'logic.paraconsistent', label: 'Logique paraconsistante', domain: 'logic', school: 'priest', service: null }),
  L({ id: 'logic.paracomplete', label: 'Logique paracomplète', domain: 'logic', school: 'kleene', service: null }),
  L({ id: 'logic.intuitionistic', label: 'Logique intuitionniste', domain: 'logic', school: 'brouwer-heyt​​ing', service: null }),
  L({ id: 'logic.many-valued', label: 'Logiques à plusieurs valeurs', domain: 'logic', school: 'lukasiewicz-kleene', service: null }),
  L({ id: 'logic.linear', label: 'Logique linéaire', domain: 'logic', school: 'girard', service: null }),
  L({ id: 'logic.quantum', label: 'Logique quantique', domain: 'logic', school: 'birkhoff-von-neumann', service: null }),
  L({ id: 'logic.higher-order', label: 'Logique du second ordre et d’ordre supérieur', domain: 'logic', school: 'higher-order', service: null }),
  L({ id: 'metalogic.soundness', label: 'Correction d’un système logique', domain: 'metalogic', school: 'hilbert', service: null }),
  L({ id: 'metalogic.completeness', label: 'Complétude', domain: 'metalogic', school: 'godel', service: null }),
  L({ id: 'metalogic.decidability', label: 'Décidabilité et indécidabilité', domain: 'metalogic', school: 'church-turing', service: null }),
  L({ id: 'metalogic.godel-first-incompleteness', label: 'Premier théorème d’incomplétude', domain: 'metalogic', school: 'godel', service: null }),
  L({ id: 'metalogic.godel-second-incompleteness', label: 'Second théorème d’incomplétude', domain: 'metalogic', school: 'godel', service: null }),
  L({ id: 'truth.tarski-undefinability', label: 'Indéfinissabilité de la vérité', domain: 'truth', school: 'tarski', service: null }),
  L({ id: 'truth.fixed-point', label: 'Théorie des points fixes de la vérité', domain: 'truth', school: 'kripke', service: null }),
  L({ id: 'paradox.liar', label: 'Paradoxe du menteur', domain: 'paradox', school: 'eubulides-tarski-kripke', service: null }),
  L({ id: 'paradox.russell', label: 'Paradoxe de Russell', domain: 'paradox', school: 'russell-zf', service: null }),
  L({ id: 'paradox.cantor', label: 'Paradoxe de Cantor', domain: 'paradox', school: 'cantor', service: null }),
  L({ id: 'paradox.burali-forti', label: 'Paradoxe de Burali-Forti', domain: 'paradox', school: 'burali-forti', service: null }),
  L({ id: 'paradox.grelling-nelson', label: 'Paradoxe de Grelling-Nelson', domain: 'paradox', school: 'grelling-nelson', service: null }),
  L({ id: 'paradox.berry', label: 'Paradoxe de Berry', domain: 'paradox', school: 'berry', service: null }),
  L({ id: 'paradox.richard', label: 'Paradoxe de Richard', domain: 'paradox', school: 'richard', service: null }),
  L({ id: 'paradox.sorites', label: 'Paradoxe du sorite', domain: 'paradox', school: 'eubulides', service: null }),
  L({ id: 'paradox.zeno', label: 'Paradoxes de Zénon', domain: 'paradox', school: 'zeno', service: null }),
  L({ id: 'paradox.fitch', label: 'Paradoxe de la connaissance de Fitch', domain: 'paradox', school: 'fitch', service: null }),
  L({ id: 'paradox.moore', label: 'Paradoxe de Moore', domain: 'paradox', school: 'moore', service: null }),
  L({ id: 'paradox.curry', label: 'Paradoxe de Curry', domain: 'paradox', school: 'curry', service: null }),
  L({ id: 'paradox.twin', label: 'Paradoxe des jumeaux', domain: 'paradox', school: 'einstein-langevin', service: null })
];

module.exports = { LOGIC_DEFINITIONS };
