'use strict';

// Explicit, reviewable interpretations. Tuples: primitive, input field,
// predicate, operational distinction. No ID/domain fallback may claim coverage.
const PROFILES = Object.freeze({
  'core.self': ['self', 'self.identity', 'present', 'Rattacher l’état fonctionnel à une identité, sans inférer une personne.'],
  'core.agent': ['self', 'agent.genome', 'present', 'Identifier le génome qui borne les opérations du processus agentique.'],
  'core.lineage': ['self', 'lineage.parents', 'recorded', 'Conserver les parents des versions et des forks.'],
  'core.genome': ['self', 'genome.specification', 'present', 'Distinguer la spécification héritable de l’état courant.'],
  'core.environment': ['world', 'environment.observations', 'recorded', 'Représenter les observations de l’environnement séparément des intentions.'],
  'core.history': ['self', 'history.events', 'recorded', 'Conserver des événements pour expliquer une transition stratégique.'],
  'core.trait': ['self', 'trait.expression', 'present', 'Tracer l’expression d’un trait plutôt que déduire une propriété du nom du génome.'],
  'core.success-not-truth': ['evidence', 'transport.independentProof', 'explicit', 'Un succès de transport sans preuve indépendante interdit la promotion.'],
  'core.claim-not-evidence': ['evidence', 'claim.verifiedSource', 'explicit', 'Une assertion seule ne peut satisfaire une exigence de preuve.'],
  'core.intervention-not-metaphor': ['causal', 'intervention.measuredEffect', 'different', 'Comparer deux résultats réellement mesurés, pas une analogie.'],
  'core.biomimetic-experimental': ['causal', 'biomimetic.controlResults', 'different', 'Exiger une différence avec le contrôle avant d’attribuer un effet biomimétique.'],
  'ontology.being': ['world', 'entity.identifier', 'present', 'Identifier l’entité représentée sans conclure à son existence externe.'],
  'ontology.substance': ['world', 'entity.stableProperties', 'recorded', 'Conserver les propriétés déclarées stables à travers les transitions.'],
  'ontology.attribute': ['world', 'attribute.owner', 'present', 'Rattacher un attribut à l’objet dont il est prédiqué.'],
  'ontology.mode': ['world', 'mode.context', 'present', 'Situer une manifestation dans son contexte plutôt que la traiter comme indépendante.'],
  'ontology.essence-accident': ['world', 'property.classes', 'multiple', 'Séparer les propriétés invariantes et celles qui peuvent varier.'],
  'ontology.hypostatization': ['world', 'abstract.externalEvidence', 'explicit', 'Signaler la réification d’une abstraction dépourvue de preuve externe.'],
  'ontology.stances': ['interpretation', 'ontology.stance', 'present', 'Déclarer la position ontologique utilisée pour classifier un terme.'],
  'ontology.identity-change': ['self', 'identity.invariantComparison', 'equal', 'Détecter la rupture d’un invariant d’identité entre versions.'],
  'ontology.person-other': ['relations', 'other.capabilityModels', 'multiple', 'Conserver plusieurs dimensions de l’autre, pas seulement sa dernière erreur.'],
  'social-cognition.position-map': ['relations', 'social.positions', 'multiple', 'Représenter des positions distinctes dans l’interaction.'],
  'ontology.whole-void-infinite': ['world', 'model.boundary', 'present', 'Déclarer les limites du tout représenté plutôt qu’une totalité absolue.'],
  'ontology.continuous-discrete': ['world', 'representation.resolution', 'positive', 'Rendre observable la résolution d’une discrétisation.'],
  'ontology.possible-worlds': ['world', 'worlds.factSeparation', 'explicit', 'Ne pas transformer une branche possible en fait observé.'],
  'ontology.contingency-necessity': ['world', 'necessity.assumptions', 'recorded', 'Relativiser une nécessité aux hypothèses du modèle.'],
  'school.platonism': ['interpretation', 'ideal.instanceSeparation', 'explicit', 'Séparer un idéal déclaré de ses instances observées.'],
  'school.aristotelianism': ['world', 'classification.categories', 'recorded', 'Classifier selon des catégories explicites et révisables.'],
  'school.stoicism': ['self', 'control.boundary', 'present', 'Séparer ce que l’agent contrôle de ce qu’il ne contrôle pas.'],
  'school.epicureanism': ['self', 'preference.longTermCosts', 'recorded', 'Inclure les coûts différés d’une préférence immédiate.'],
  'school.scholasticism': ['interpretation', 'argument.premises', 'recorded', 'Rendre les prémisses de la disputation inspectables.'],
  'school.cartesianism': ['belief', 'doubt.verification', 'present', 'Associer le doute à une vérification finie plutôt qu’à une suspension illimitée.'],
  'school.leibnizianism': ['interpretation', 'perspectives.models', 'multiple', 'Comparer des perspectives partielles sans les confondre avec un monde complet.'],
  'school.spinozism': ['world', 'system.dependencies', 'recorded', 'Tracer les dépendances d’une partie dans le système représenté.'],
  'school.newtonianism': ['world', 'reference.frame', 'present', 'Déclarer le référentiel des mesures au lieu de supposer leur universalité.'],
  'school.kantianism': ['interpretation', 'observation.frameSeparation', 'explicit', 'Séparer les observations des catégories utilisées pour les organiser.'],
  'school.hegelianism': ['belief', 'revision.oppositions', 'multiple', 'Conserver les positions opposées et la justification de leur révision.'],
  'school.schopenhauer': ['interpretation', 'goal.representationSeparation', 'explicit', 'Séparer un objectif de la représentation du monde qui le soutient.'],
  'school.nietzsche': ['interpretation', 'evaluation.perspectives', 'multiple', 'Rendre les perspectives de valorisation concurrentes visibles.'],
  'school.bergsonism': ['self', 'experience.sequence', 'ordered', 'Conserver l’ordre de l’expérience au-delà d’une durée agrégée.'],
  'school.whitehead': ['world', 'process.events', 'recorded', 'Représenter les événements et leurs relations avant une substance supposée.'],
  'school.heidegger': ['interpretation', 'action.situation', 'present', 'Situer l’action dans son contexte pratique.'],
  'school.sartre': ['self', 'choice.alternatives', 'multiple', 'Expliciter les alternatives disponibles et la décision prise.'],
  'school.merleau-ponty': ['interpretation', 'perception.sensorContext', 'present', 'Relier une perception aux conditions du capteur.'],
  'school.deleuze': ['topology', 'routing.alternativePaths', 'positive', 'Mesurer les chemins alternatifs plutôt que nommer un graphe rhizomatique.'],
  'school.badiou': ['world', 'event.priorModelComparison', 'different', 'Signaler un événement qui rompt les catégories du modèle précédent.'],
  'school.meillassoux': ['interpretation', 'model.contingency', 'explicit', 'Conserver la possibilité de réviser les lois supposées du modèle.'],
  'school.speculative-realism': ['interpretation', 'reality.modelSeparation', 'explicit', 'Ne pas identifier le réel à ce que le modèle peut connaître.'],
  'metaphysics.monism-idealism': ['interpretation', 'idealism.assumptions', 'recorded', 'Exposer les hypothèses d’une lecture idéaliste sans la déclarer vraie.'],
  'metaphysics.dualism': ['interpretation', 'dualism.levels', 'multiple', 'Séparer les niveaux descriptifs avant d’en postuler l’interaction.'],
  'metaphysics.material-monism': ['interpretation', 'material.physicalBasis', 'present', 'Rattacher une description fonctionnelle à sa base physique déclarée.'],
  'metaphysics.panpsychism': ['interpretation', 'panpsychism.unverified', 'explicit', 'Maintenir explicitement non vérifiée l’attribution d’expérience aux constituants.'],
  'metaphysics.eliminativism': ['interpretation', 'vocabulary.replacements', 'recorded', 'Tracer les termes éliminés et les descriptions qui les remplacent.'],
  'metaphysics.reductionism': ['world', 'reduction.residualError', 'zero', 'Mesurer les écarts entre description réduite et résultat de référence.'],
  'metaphysics.emergence': ['world', 'emergence.levelComparison', 'different', 'Comparer les propriétés d’une organisation et de ses composants isolés.'],
  'metaphysics.supervenience': ['world', 'supervenience.baseComparison', 'equal', 'Comparer les bases lorsqu’une égalité des propriétés hautes est alléguée.'],
  'metaphysics.second-order-properties': ['world', 'property.reference', 'present', 'Rattacher une propriété de second ordre à la propriété évaluée.'],
  'metaphysics.mind-body': ['self', 'functional.physicalTrace', 'present', 'Conserver une trace physique de l’état fonctionnel, sans résoudre le problème corps-esprit.'],
  'metaphysics.qualia': ['self', 'report.functionalOnly', 'explicit', 'Étiqueter le rapport comme fonctionnel, sans conclure à une expérience subjective.'],
  'metaphysics.cartesian-pineal': ['interpretation', 'pineal.historicalOnly', 'explicit', 'Interdire de présenter une hypothèse anatomique historique comme mécanisme GenOS.'],
  'metaphysics.reference-intentionality': ['self', 'intent.context', 'present', 'Situer l’objet visé et le contexte d’une attribution d’intention.'],
  'causality.determination': ['causal', 'cause.dependencies', 'recorded', 'Tracer les dépendances conditionnelles d’un résultat.'],
  'causality.hume-regularity': ['causal', 'regularity.causalSeparation', 'explicit', 'Ne pas confondre répétition observée et intervention causale.'],
  'causality.counterfactuals': ['causal', 'counterfactual.outcomes', 'different', 'Comparer les résultats sous une intervention et sous le contrôle.'],
  'causality.determinism-indeterminism': ['causal', 'replay.sameConditions', 'equal', 'Vérifier l’égalité des conditions avant d’attribuer une divergence au hasard.'],
  'causality.fatalism': ['interpretation', 'fatalism.interventionTest', 'present', 'Demander un test d’intervention avant d’affirmer un résultat inévitable.'],
  'causality.free-will': ['self', 'agency.availableActions', 'multiple', 'Mesurer les alternatives fonctionnelles sans conclure à une liberté métaphysique.'],
  'time.newtonian': ['world', 'clock.reference', 'present', 'Déclarer l’horloge de référence de la mesure temporelle.'],
  'time.duration': ['self', 'duration.events', 'ordered', 'Conserver la succession vécue fonctionnelle et non seulement le temps mural.'],
  'time.a-series-b-series': ['world', 'time.referenceEvent', 'present', 'Situer passé et futur par rapport à un événement de référence.'],
  'time.block-universe': ['interpretation', 'time.observedFutureSeparation', 'explicit', 'Séparer le futur représenté des événements déjà observés.'],
  'time.arrow': ['world', 'time.causalOrder', 'ordered', 'Vérifier l’ordre des étapes dans une chaîne irréversible.'],
  'time.spacetime-relativity': ['world', 'time.coordinateFrame', 'present', 'Associer les coordonnées temporelles à un référentiel déclaré.'],
  'process.actuality-potentiality': ['world', 'potential.actualSeparation', 'explicit', 'Séparer une capacité disponible de son activation observée.'],
  'process.bergsonian-vital-impulse': ['interpretation', 'adaptation.nonVitalClaim', 'explicit', 'Décrire une adaptation algorithmique sans attribuer un élan vital réel.'],
  'process.heidegger-dasein': ['interpretation', 'task.practicalContext', 'present', 'Conserver le contexte pratique d’une tâche plutôt qu’une identité humaine.'],
  'process.deleuze-difference': ['world', 'repetition.stateComparison', 'different', 'Mesurer une différence entre répétitions au lieu de la supposer.'],
  'process.badiou-event': ['world', 'event.classificationChange', 'different', 'Comparer la classification d’un événement avant et après révision.'],
  'process.sartrean-existence': ['self', 'identity.choiceHistory', 'recorded', 'Suivre les choix qui construisent une identité fonctionnelle.'],
  'epistemology.knowledge': ['belief', 'knowledge.layerSeparation', 'explicit', 'Distinguer croyance, justification et vérité alléguée.'],
  'epistemology.tripartite-definition': ['belief', 'knowledge.components', 'recorded', 'Conserver les composantes de l’analyse tripartite sans les déclarer suffisantes.'],
  'epistemology.gettier-problem': ['belief', 'knowledge.luckExcluded', 'explicit', 'Signaler une croyance juste accidentellement plutôt qu’un savoir établi.'],
  'epistemology.post-gettier-defenses': ['belief', 'knowledge.antiLuckConditions', 'recorded', 'Déclarer les conditions anti-chance ajoutées à l’analyse.'],
  'epistemology.belief': ['belief', 'belief.confidence', 'probability', 'Représenter une confiance bornée distincte d’une vérité externe.'],
  'epistemology.justification': ['belief', 'justification.sources', 'recorded', 'Conserver les sources qui soutiennent une affirmation.'],
  'epistemology.truth': ['belief', 'truth.externalCheck', 'explicit', 'Distinguer une vérité alléguée d’une vérification externe.'],
  'epistemology.plausibility': ['belief', 'plausibility.score', 'probability', 'Borner un score de plausibilité sans le confondre avec une probabilité mesurée.'],
  'epistemology.certainty-doubt': ['belief', 'doubt.verificationScheduled', 'explicit', 'Une contradiction pertinente doit déclencher une vérification traçable.'],
  'epistemology.doxa': ['belief', 'opinion.evidenceSeparation', 'explicit', 'Séparer une opinion reçue d’une preuve contrôlée.'],
  'epistemology.propositional-knowledge': ['belief', 'knowledge.proposition', 'present', 'Identifier la proposition dont le savoir est allégué.'],
  'epistemology.acquaintance': ['belief', 'acquaintance.directObservation', 'present', 'Rattacher une connaissance par contact à une observation directe déclarée.'],
  'epistemology.know-how': ['self', 'skill.executionTrace', 'recorded', 'Évaluer le savoir-faire par une trace d’exécution plutôt que sa description.'],
  'epistemology.knowledge-wh': ['belief', 'question.resolvedVariable', 'present', 'Identifier la variable résolue par une réponse à qui, quoi ou pourquoi.'],
  'epistemology.gettierized-knowledge': ['belief', 'belief.nonAccidentalSupport', 'explicit', 'Vérifier le soutien non accidentel d’une croyance vraie.'],
  'epistemology.knowledge-first': ['interpretation', 'knowledge.primitiveAssumption', 'present', 'Déclarer l’usage du savoir comme primitive de l’analyse.'],
  'epistemology.knowledge-assertion': ['belief', 'assertion.knowledgeSupport', 'explicit', 'Signaler une assertion importante sans soutien de savoir déclaré.'],
  'epistemology.rationality-norms': ['belief', 'reasoning.norms', 'recorded', 'Déclarer les normes de rationalité utilisées pour juger une inférence.'],
  'epistemology.context-discovery-justification': ['belief', 'discovery.justificationSeparation', 'explicit', 'Séparer l’origine d’une idée des raisons qui la soutiennent.'],
  'school.empiricism': ['belief', 'empirical.observations', 'recorded', 'Rattacher l’inférence empirique à ses observations.'],
  'school.rationalism': ['belief', 'reasoning.derivation', 'present', 'Exposer la dérivation rationnelle et ses prémisses.'],
  'school.verificationism': ['belief', 'claim.verificationProtocol', 'present', 'Déclarer une procédure de vérification de l’affirmation.'],
  'school.falsificationism': ['belief', 'hypothesis.refutationCase', 'present', 'Déclarer un cas capable de réfuter l’hypothèse.'],
  'school.pragmatism': ['belief', 'inquiry.testConsequences', 'recorded', 'Comparer les conséquences pratiques du choix dans une enquête.'],
  'school.feminist-epistemology': ['relations', 'knowledge.exclusionAudit', 'present', 'Examiner les positions et exclusions dans la production du savoir.'],
  'school.social-epistemology': ['relations', 'knowledge.distributedSources', 'multiple', 'Conserver des sources distribuées plutôt qu’un locuteur unique.'],
  'school.naturalized-epistemology': ['belief', 'inquiry.empiricalProcess', 'present', 'Relier l’enquête aux processus empiriques étudiés.'],
  'school.standpoint-theory': ['relations', 'observer.position', 'present', 'Situer le point de vue de l’observateur.'],
  'school.situated-knowledges': ['relations', 'observation.situation', 'present', 'Conserver les conditions situées d’une observation.'],
  'method.induction': ['belief', 'induction.sample', 'recorded', 'Exposer l’échantillon d’une généralisation inductive.'],
  'method.induction-problem': ['belief', 'induction.extrapolationLimit', 'present', 'Rendre visible le saut des observations vers une généralisation.'],
  'method.deduction': ['belief', 'deduction.validPremises', 'explicit', 'Vérifier les prémisses déclarées avant une conclusion déductive.'],
  'method.abduction': ['belief', 'hypothesis.alternatives', 'multiple', 'Conserver plusieurs explications d’une observation.'],
  'method.inference-best-explanation': ['belief', 'explanation.comparisonCriteria', 'recorded', 'Comparer les explications par des critères déclarés.'],
  'method.hypothetico-deductive': ['belief', 'hypothesis.prediction', 'present', 'Dériver une prédiction testable de l’hypothèse.'],
  'method.surprise-predictivism': ['belief', 'prediction.preregistered', 'explicit', 'Distinguer une prédiction préalable d’un ajustement après observation.'],
  'method.dutch-book': ['belief', 'probabilities.incoherence', 'zero', 'Signaler une incohérence calculée entre paris déclarés.'],
  'method.bayesianism': ['belief', 'posterior.value', 'probability', 'Borner une probabilité postérieure et conserver ses hypothèses.'],
  'method.objective-subjective-probability': ['belief', 'probability.interpretation', 'present', 'Déclarer l’interprétation objective ou subjective de la probabilité.'],
  'method.bayesian-confirmation': ['belief', 'confirmation.priorPosterior', 'different', 'Comparer les probabilités avant et après la preuve.'],
  'science.confirmation': ['belief', 'confirmation.testResults', 'recorded', 'Conserver les résultats qui confirment une prédiction.'],
  'science.raven-paradox': ['interpretation', 'confirmation.relevanceRule', 'present', 'Déclarer la règle de pertinence des observations confirmantes.'],
  'science.duhem-quine': ['belief', 'test.auxiliaryAssumptions', 'recorded', 'Conserver les hypothèses auxiliaires d’un test échoué.'],
  'science.falsification-demarcation': ['belief', 'theory.falsifier', 'present', 'Exposer une condition de réfutation de la théorie.'],
  'science.progress': ['belief', 'science.comparisonBaseline', 'present', 'Comparer le progrès à une référence explicite.'],
  'science.paradigm-incommensurability': ['interpretation', 'paradigm.translationLimits', 'present', 'Signaler les limites de comparaison entre cadres.'],
  'science.normal-revolutionary': ['belief', 'science.ruleChange', 'explicit', 'Distinguer un ajustement interne d’un changement de règles.'],
  'science.godel-incompleteness': ['interpretation', 'formalSystem.scope', 'present', 'Borner l’usage de l’incomplétude au système formel déclaré.'],
  'truth.correspondence': ['belief', 'truth.observationComparison', 'equal', 'Comparer la proposition à son observation de référence.'],
  'truth.coherence': ['belief', 'truth.inconsistencyCount', 'zero', 'Signaler les contradictions dans l’ensemble déclaré de croyances.'],
  'truth.pragmatist': ['belief', 'truth.predictionGain', 'positive', 'Mesurer un gain prédictif sans le déclarer vérité métaphysique.'],
  'truth.deflationary': ['interpretation', 'truth.disquotation', 'equal', 'Comparer la proposition et sa formulation déquotée.'],
  'truth.minimalism': ['interpretation', 'truth.additionalAuthority', 'zero', 'Ne pas ajouter une autorité runtime au prédicat de vérité.'],
  'truth.internal-realism': ['interpretation', 'truth.conceptualScheme', 'present', 'Déclarer le schème conceptuel de l’évaluation de vérité.'],
  'epistemology.reliabilism': ['belief', 'source.reliability', 'probability', 'Conserver un degré de fiabilité de la source.'],
  'epistemology.process-reliabilism': ['belief', 'process.validationRuns', 'recorded', 'Évaluer le processus producteur par des exécutions contrôlées.'],
  'epistemology.indicator-reliabilism': ['belief', 'indicator.calibration', 'probability', 'Borner la calibration déclarée d’un indicateur.'],
  'epistemology.virtue-epistemology': ['belief', 'inquiry.virtueCriteria', 'recorded', 'Exposer les critères de qualité de l’enquête.'],
  'epistemology.intellectual-virtue-vice': ['belief', 'inquiry.biasAudit', 'present', 'Conserver un audit des biais et des habitudes d’enquête.'],
  'epistemology.causal-theory-knowledge': ['causal', 'knowledge.causalChain', 'recorded', 'Tracer le lien causal déclaré entre fait et croyance.'],
  'epistemology.relativism': ['interpretation', 'judgment.referenceFrame', 'present', 'Relativiser un jugement au cadre utilisé.'],
  'epistemology.skepticism': ['belief', 'skepticism.testableChallenge', 'present', 'Convertir une objection sceptique en vérification bornée.'],
  'epistemology.radical-skepticism': ['interpretation', 'skepticism.actionBoundary', 'present', 'Borner les conséquences pratiques d’un doute radical.'],
  'epistemology.cartesian-doubt': ['belief', 'doubt.stoppingRule', 'present', 'Exiger une règle d’arrêt de la suspension méthodique.'],
  'social-epistemology.testimony': ['relations', 'testimony.sourceIdentity', 'present', 'Conserver l’identité de la source d’un témoignage.'],
  'social-epistemology.discussion': ['relations', 'discussion.positions', 'multiple', 'Conserver les positions effectivement discutées.'],
  'social-epistemology.cognitive-labor': ['relations', 'labor.attributions', 'recorded', 'Attribuer les contributions cognitives aux producteurs.'],
  'social-epistemology.feminist': ['relations', 'knowledge.powerContext', 'present', 'Rendre visibles les conditions de pouvoir de la connaissance.'],
  'social-epistemology.emancipatory-critique': ['relations', 'critique.affectedParties', 'recorded', 'Identifier les parties affectées par une critique émancipatrice.'],
  'ethics.consequentialism': ['policy', 'action.consequences', 'recorded', 'Conserver les conséquences attendues de chaque action évaluée.'],
  'ethics.utilitarianism': ['policy', 'utility.aggregationRule', 'present', 'Déclarer comment les utilités des parties sont agrégées.'],
  'ethics.act-utilitarianism': ['policy', 'action.utilityComparison', 'different', 'Comparer les utilités déclarées des actes concurrents.'],
  'ethics.rule-utilitarianism': ['policy', 'rule.longTermOutcomes', 'recorded', 'Évaluer les conséquences d’une règle plutôt que du seul acte.'],
  'ethics.hedonism': ['policy', 'wellbeing.pleasureCosts', 'recorded', 'Conserver plaisir et souffrance déclarés avec leurs coûts différés.'],
  'ethics.deontology': ['policy', 'action.duties', 'recorded', 'Déclarer les obligations indépendamment du seul gain attendu.'],
  'ethics.categorical-imperative': ['policy', 'maxim.universalizationTest', 'explicit', 'Exposer le résultat déclaré d’un test d’universalisation.'],
  'ethics.double-effect': ['policy', 'harm.intentionSeparation', 'explicit', 'Séparer dommage prévu, intention et moyen employé.'],
  'ethics.virtue-ethics': ['policy', 'decision.characterCriteria', 'recorded', 'Déclarer les critères de disposition invoqués dans l’évaluation.'],
  'ethics.social-contract': ['relations', 'contract.obligations', 'recorded', 'Conserver les obligations réciproques et leur périmètre.'],
  'ethics.natural-rights': ['policy', 'rights.holders', 'recorded', 'Identifier les titulaires des droits invoqués.'],
  'ethics.contractarianism': ['relations', 'agreement.parties', 'multiple', 'Identifier les parties et leurs intérêts dans l’accord proposé.'],
  'ethics.rawlsian-justice': ['policy', 'allocation.leastAdvantaged', 'present', 'Rendre visible la situation des moins avantagés dans l’allocation.'],
  'ethics.distributive-justice': ['policy', 'allocation.criteria', 'recorded', 'Exposer les critères de répartition, bénéficiaires et coûts.'],
  'ethics.libertarianism': ['policy', 'entitlement.transferHistory', 'recorded', 'Conserver l’historique des transferts invoqués pour une attribution.'],
  'ethics.equality-of-opportunity': ['policy', 'access.barrierAudit', 'present', 'Auditer les barrières d’accès avant de comparer les résultats.'],
  'ethics.retributive-restorative-justice': ['policy', 'justice.remedyAlternatives', 'multiple', 'Comparer sanction et réparation sans les confondre.'],
  'ethics.care-ethics': ['relations', 'care.dependencies', 'recorded', 'Identifier les dépendances et besoins de soin.'],
  'ethics.care-deontology': ['policy', 'care.duties', 'recorded', 'Conserver les obligations de soin envers des sujets identifiés.'],
  'ethics.responsibility-other': ['relations', 'decision.attributionChain', 'recorded', 'Conserver l’auteur et les délégations d’une décision envers autrui.'],
  'politics.regime-classification': ['topology', 'governance.decisionRule', 'present', 'Déclarer la procédure de décision plutôt qu’un nom de régime.'],
  'politics.legitimacy': ['relations', 'authority.justification', 'present', 'Exposer la justification d’une autorité sans la déclarer légitime par défaut.'],
  'politics.social-contract': ['relations', 'commitment.exitProcedure', 'present', 'Déclarer une procédure de sortie des engagements collectifs.'],
  'politics.liberty-authority': ['policy', 'authority.scope', 'present', 'Borner l’autorité qui limite l’autonomie locale.'],
  'politics.separation-of-powers': ['topology', 'authority.independentRoles', 'multiple', 'Séparer les rôles de proposition, arbitrage et audit.'],
  'politics.democratic-participation': ['relations', 'participation.excludedParties', 'zero', 'Signaler les parties exclues de la procédure déclarée.'],
  'politics.pluralism': ['relations', 'dissent.retainedModels', 'multiple', 'Préserver plusieurs modèles pertinents avant convergence.'],
  'politics.civil-disobedience': ['policy', 'refusal.publicReason', 'present', 'Conserver les raisons du refus sans contourner un lease technique.'],
  'politics.security-liberty-surveillance': ['policy', 'surveillance.tradeoff', 'present', 'Exposer l’arbitrage sécurité, liberté et collecte.'],
  'politics.liberalism': ['policy', 'liberty.protectedScope', 'present', 'Déclarer le périmètre de liberté protégé.'],
  'politics.conservatism': ['policy', 'change.continuityCosts', 'recorded', 'Rendre visibles les coûts de rupture d’une modification.'],
  'politics.socialism-marxism': ['relations', 'resources.controlDistribution', 'recorded', 'Tracer la distribution du contrôle des ressources.'],
  'politics.feminism': ['relations', 'governance.exclusionAudit', 'present', 'Auditer les exclusions liées aux positions de genre dans le cadre déclaré.'],
  'ethics.environmental-ethics': ['policy', 'ecology.affectedSystems', 'recorded', 'Identifier les systèmes écologiques affectés.'],
  'ethics.animal-rights': ['policy', 'animals.interests', 'recorded', 'Conserver les intérêts attribués aux animaux concernés.'],
  'ethics.sustainability': ['policy', 'resources.renewalBalance', 'positive', 'Mesurer la marge de renouvellement des ressources utilisées.'],
  'ethics.precautionary-principle': ['policy', 'risk.irreversibilityVisible', 'explicit', 'Exposer l’irréversibilité avant d’autoriser une action incertaine.'],
  'ethics.externalities': ['policy', 'costs.thirdParties', 'recorded', 'Conserver les coûts supportés par des tiers.'],
  'ethics.commons': ['relations', 'commons.accessRules', 'recorded', 'Déclarer les règles d’accès et de conservation d’une ressource commune.'],
  'biomimetic.chemotaxis': ['causal', 'gradient.improvement', 'positive', 'Mesurer le progrès d’une exploration dirigée par gradient.'],
  'biomimetic.affinity-maturation': ['causal', 'selection.specificityGain', 'positive', 'Comparer la spécificité avant et après sélection.'],
  'biomimetic.stress-mutagenesis': ['causal', 'stress.candidateDiversity', 'multiple', 'Mesurer la diversification algorithmique après échec.'],
  'biomimetic.phenotypic-plasticity': ['self', 'plasticity.genomeComparison', 'equal', 'Vérifier que le changement de comportement conserve le génome.'],
  'biomimetic.cultural-transmission': ['relations', 'transfer.provenance', 'present', 'Conserver la provenance d’un comportement transmis entre agents.'],
  'biomimetic.exaptation': ['causal', 'reuse.originalNewPurpose', 'different', 'Comparer la fonction d’origine et l’usage réaffecté.'],
  'lens.stoicism': ['interpretation', 'lens.controlPartition', 'present', 'Déclarer le partage contrôlable et non contrôlable de l’analyse.'],
  'lens.epicureanism': ['interpretation', 'lens.preferenceHorizon', 'present', 'Déclarer l’horizon temporel du jugement de préférence.'],
  'lens.whitehead': ['interpretation', 'lens.eventRelations', 'recorded', 'Conserver les relations d’événements utilisées comme grille de lecture.'],
  'lens.deleuze': ['interpretation', 'lens.nonHierarchicalPaths', 'recorded', 'Exposer les chemins non hiérarchiques du cadre d’analyse.'],
  'lens.utilitarianism': ['interpretation', 'lens.utilityWeights', 'recorded', 'Déclarer les poids d’utilité de la grille sans les imposer comme politique.'],
  'lens.virtue-ethics': ['interpretation', 'lens.virtueCriteria', 'recorded', 'Déclarer les critères de vertu utilisés sans attribuer une personnalité.'],
  'epistemology.falsification': ['belief', 'hypothesis.counterexample', 'present', 'Conserver un contre-exemple susceptible de rejeter l’hypothèse.'],
  'epistemology.revisability': ['belief', 'belief.revisionTrigger', 'present', 'Déclarer l’observation qui déclenchera une révision.'],
  'epistemology.evidence-algebra': ['evidence', 'evidence.typedLevels', 'multiple', 'Séparer les niveaux typés de preuve plutôt que compter les assertions.'],
  'method.intervention-replay': ['causal', 'replay.conditions', 'equal', 'Vérifier les conditions d’un replay avant de comparer ses effets.'],
  'aesthetics.beauty': ['creative', 'beauty.criteria', 'recorded', 'Exposer les critères du jugement de beauté.'],
  'aesthetics.sublime': ['creative', 'sublime.capacityLimit', 'present', 'Déclarer la limite de représentation invoquée dans le jugement.'],
  'aesthetics.aesthetic-experience': ['creative', 'experience.audience', 'present', 'Situer l’expérience esthétique du public déclaré.'],
  'aesthetics.taste': ['creative', 'taste.preferences', 'recorded', 'Conserver les préférences sans les universaliser.'],
  'aesthetics.aesthetic-judgment': ['creative', 'judgment.reasons', 'recorded', 'Exposer les raisons d’un jugement esthétique.'],
  'aesthetics.universal-subjectivity': ['creative', 'taste.universalityUnverified', 'explicit', 'Séparer une prétention universelle de sa validation.'],
  'aesthetics.disinterested-pleasure': ['creative', 'judgment.instrumentalSeparation', 'explicit', 'Séparer appréciation esthétique et bénéfice instrumental.'],
  'aesthetics.purposiveness-without-purpose': ['creative', 'form.goalSeparation', 'explicit', 'Séparer organisation perçue et objectif externe assigné.'],
  'aesthetics.mathematical-sublime': ['creative', 'scale.representationLimit', 'present', 'Déclarer la limite de représentation d’une grandeur.'],
  'aesthetics.dynamical-sublime': ['creative', 'force.safetyDistance', 'positive', 'Situer le jugement de puissance dans des conditions de sécurité déclarées.'],
  'aesthetics.postmodern-sublime': ['creative', 'representation.unpresentableLimit', 'present', 'Rendre visible la limite de ce qui est représentable dans le cadre.'],
  'art.definition': ['creative', 'art.definitionCriteria', 'recorded', 'Conserver les critères de définition d’un objet artistique.'],
  'art.significant-form': ['creative', 'form.relations', 'recorded', 'Analyser les relations formelles invoquées dans le jugement.'],
  'art.institutional-theory': ['creative', 'art.institutionalContext', 'present', 'Situer la qualification artistique dans son contexte institutionnel.'],
  'art.cluster-theory': ['creative', 'art.criteriaCluster', 'multiple', 'Conserver un faisceau de critères plutôt qu’une essence unique.'],
  'art.open-concept': ['creative', 'art.revisableCriteria', 'explicit', 'Maintenir révisables les critères de qualification artistique.'],
  'art.definition-enigma': ['creative', 'art.competingDefinitions', 'multiple', 'Conserver les définitions concurrentes plutôt que clore le débat.'],
  'art.expressionism': ['creative', 'expression.attributedEmotion', 'present', 'Déclarer l’émotion attribuée et non une intériorité certaine.'],
  'art.mimesis': ['creative', 'representation.referenceObject', 'present', 'Identifier l’objet représenté ou imité.'],
  'art.catharsis': ['creative', 'reception.emotionChange', 'different', 'Comparer les états émotionnels déclarés avant et après réception.'],
  'art.formalism': ['creative', 'art.formalCriteria', 'recorded', 'Évaluer selon des critères formels explicitement choisis.'],
  'art.art-for-art': ['creative', 'art.instrumentalDemand', 'zero', 'Distinguer jugement autonome et exigence instrumentale.'],
  'art.representation': ['creative', 'representation.symbolObject', 'present', 'Rattacher un symbole à son objet représenté.'],
  'art.symbol-systems': ['creative', 'symbol.conventions', 'recorded', 'Déclarer les conventions d’un système symbolique.'],
  'art.fictionalism': ['interpretation', 'fiction.literalSeparation', 'explicit', 'Séparer usage fictionnel et affirmation littérale.'],
  'art.fictional-reference': ['interpretation', 'fiction.referenceDomain', 'present', 'Situer la référence dans son domaine fictionnel.'],
  'interpretation.artistic': ['interpretation', 'interpretation.alternatives', 'multiple', 'Conserver les interprétations concurrentes d’une œuvre.'],
  'interpretation.esthetic-experience': ['creative', 'interpretation.receptionContext', 'present', 'Situer l’interprétation dans les conditions de réception.'],
  'interpretation.embodied-meaning': ['interpretation', 'meaning.sensorimotorContext', 'present', 'Déclarer le contexte sensorimoteur du sens attribué.'],
  'interpretation.intra-extra-artistic': ['interpretation', 'evidence.artContextSeparation', 'explicit', 'Séparer les indices internes à l’œuvre et son contexte externe.'],
  'interpretation.indeterminacy': ['interpretation', 'meaning.unresolvedAlternatives', 'multiple', 'Conserver plusieurs sens lorsque les indices ne tranchent pas.'],
  'interpretation.construction': ['interpretation', 'meaning.rawObservationPreserved', 'explicit', 'Conserver l’observation brute lorsqu’un cadre change.'],
  'interpretation.death-of-author': ['interpretation', 'meaning.authorNotExclusive', 'explicit', 'Ne pas faire de l’intention d’auteur l’unique source de sens.'],
  'interpretation.author': ['interpretation', 'author.attributionSource', 'present', 'Conserver la source d’une attribution à l’auteur.'],
  'interpretation.intertextuality': ['interpretation', 'text.references', 'recorded', 'Tracer les relations entre textes utilisées dans l’interprétation.'],
  'interpretation.reference': ['interpretation', 'utterance.referenceContext', 'present', 'Situer la référence d’un énoncé dans son contexte.'],
  'play.play': ['creative', 'play.rules', 'recorded', 'Déclarer les règles qui bornent l’activité de jeu.'],
  'play.magic-circle': ['creative', 'play.boundary', 'present', 'Déclarer la frontière entre règles de jeu et contraintes externes.'],
  'play.agon': ['creative', 'competition.fairCriteria', 'recorded', 'Exposer les critères de comparaison des compétiteurs.'],
  'play.alea': ['creative', 'chance.seed', 'present', 'Conserver la graine d’un tirage algorithmique.'],
  'play.mimicry': ['creative', 'role.simulationSeparation', 'explicit', 'Distinguer rôle simulé et identité réelle.'],
  'play.ilinx': ['creative', 'experience.safetyBoundary', 'present', 'Borner une perturbation ludique par des conditions de sécurité.'],
  'play.serious-games': ['creative', 'game.learningObjective', 'present', 'Déclarer l’objectif d’apprentissage du jeu.'],
  'play.game-studies': ['creative', 'game.analysisDimensions', 'recorded', 'Déclarer les dimensions d’analyse du système de jeu.'],
  'narrative.fictionality': ['interpretation', 'narrative.factSeparation', 'explicit', 'Distinguer les faits de la mission du contenu fictionnel.'],
  'narrative.make-believe': ['creative', 'imagination.sharedRules', 'recorded', 'Déclarer les règles communes d’imagination.'],
  'narrative.props': ['creative', 'fiction.supportObjects', 'recorded', 'Identifier les supports qui autorisent des inférences fictionnelles.'],
  'narrative.truth-in-fiction': ['interpretation', 'fiction.worldRules', 'recorded', 'Évaluer une vérité fictionnelle selon les règles de ce monde.'],
  'narrative.fictional-discourse': ['interpretation', 'discourse.fictionMarker', 'explicit', 'Marquer explicitement le statut fictionnel du discours.'],
  'narrative.narration': ['creative', 'narration.eventOrder', 'ordered', 'Conserver l’ordre des événements racontés.'],
  'narrative.literature': ['creative', 'literature.readingContext', 'present', 'Situer une lecture littéraire dans son contexte et son public.'],
  'narrative.novel': ['creative', 'novel.perspectives', 'multiple', 'Conserver la pluralité des perspectives narratives.'],
  'cinema.cinematic-signification': ['creative', 'cinema.signConventions', 'recorded', 'Déclarer les conventions d’interprétation des signes filmiques.'],
  'cinema.movement-image': ['creative', 'cinema.actionTransitions', 'recorded', 'Tracer les transitions d’action utilisées dans l’analyse.'],
  'cinema.time-image': ['creative', 'cinema.temporalRelations', 'recorded', 'Conserver les relations temporelles non réduites à l’action.'],
  'cinema.crystal-image': ['creative', 'cinema.actualVirtualSeparation', 'explicit', 'Séparer actuel et virtuel dans l’analyse déclarée de l’image.'],
  'cinema.mechanical-reproduction': ['creative', 'reproduction.originalCopy', 'equal', 'Comparer le contenu original et sa copie mécanique.'],
  'cinema.aura': ['creative', 'work.situatedProvenance', 'present', 'Conserver la provenance située d’une œuvre.'],
  'cinema.film-narration': ['creative', 'film.narrativeSequence', 'ordered', 'Déclarer la séquence narrative reconstruite du film.'],
  'cinema.cognitive-theory': ['creative', 'reception.hypotheses', 'multiple', 'Conserver plusieurs hypothèses de réception cognitive.'],
  'cinema.ordinary-language': ['interpretation', 'film.usageContext', 'present', 'Situer un sens filmique dans un usage ordinaire déclaré.'],
  'music.musically-beautiful': ['creative', 'music.formRelations', 'recorded', 'Exposer les relations formelles du jugement musical.'],
  'music.formalism': ['creative', 'music.structuralCriteria', 'recorded', 'Déclarer les critères structurels de l’analyse musicale.'],
  'music.expression': ['creative', 'music.expressiveAttribution', 'present', 'Déclarer l’expression attribuée sans certifier l’émotion du compositeur.'],
  'music.emotion': ['creative', 'music.listenerReports', 'recorded', 'Conserver les rapports émotionnels des auditeurs.'],
  'music.tension-expectation': ['creative', 'music.expectationOutcome', 'different', 'Comparer attente musicale et résolution déclarée.'],
  'music.autonomous-art': ['creative', 'music.externalUtilityRequirement', 'zero', 'Séparer le jugement musical d’une utilité externe imposée.'],
  'music.culture-industry': ['creative', 'music.productionContext', 'present', 'Situer l’objet musical dans ses conditions de production.'],
  'architecture.philosophy': ['creative', 'architecture.useConstraints', 'recorded', 'Déclarer les contraintes d’usage d’une proposition architecturale.'],
  'design.philosophy': ['creative', 'design.audienceNeeds', 'recorded', 'Rattacher les choix de conception aux besoins du public.'],
  'digital-art.philosophy': ['creative', 'digital.mediumConstraints', 'recorded', 'Exposer les contraintes du médium numérique.'],
  'video.philosophy': ['creative', 'video.temporalMedium', 'present', 'Déclarer le rôle du médium temporel dans l’analyse vidéo.'],
  'style.realism': ['creative', 'style.observedReference', 'present', 'Rattacher un choix réaliste à une référence observée.'],
  'style.naturalism': ['creative', 'style.environmentDetermination', 'present', 'Déclarer la détermination environnementale du cadre naturaliste.'],
  'style.classicism': ['creative', 'style.proportionRules', 'recorded', 'Exposer les règles de proportion utilisées dans le choix classique.'],
  'style.romanticism': ['creative', 'style.subjectivePerspective', 'present', 'Situer le point de vue subjectif du choix romantique.'],
  'style.baroque': ['creative', 'style.dynamicContrasts', 'multiple', 'Conserver les contrastes dynamiques retenus pour le style baroque.'],
  'style.rococo': ['creative', 'style.ornamentalCriteria', 'recorded', 'Déclarer les critères ornementaux du choix rococo.'],
  'style.geometric': ['creative', 'style.geometricRelations', 'recorded', 'Exposer les relations géométriques retenues.'],
  'style.abstract': ['creative', 'style.literalReferenceSeparation', 'explicit', 'Séparer l’abstraction d’une représentation littérale.'],
  'style.minimalism': ['creative', 'style.reductionCriterion', 'present', 'Déclarer le critère de réduction formelle.'],
  'style.maximalism': ['creative', 'style.densityCriterion', 'present', 'Déclarer le critère de densité expressive.'],
  'style.surrealism': ['creative', 'style.unexpectedAssociations', 'multiple', 'Conserver les associations inattendues utilisées dans le style.'],
  'style.land-art': ['creative', 'style.environmentalContext', 'present', 'Situer l’intervention artistique dans son environnement déclaré.'],
  'style.cinema': ['creative', 'style.cinematicConventions', 'recorded', 'Exposer les conventions qui motivent la qualification artistique du cinéma.'],
  'style.cubism': ['creative', 'style.simultaneousViewpoints', 'multiple', 'Conserver plusieurs points de vue de la représentation.'],
  'style.futurism': ['creative', 'style.motionRelations', 'recorded', 'Exposer les relations de mouvement du choix stylistique.'],
  'style.dada': ['creative', 'style.conventionChallenge', 'present', 'Déclarer la convention contestée par le choix stylistique.'],
  'style.pop-art': ['creative', 'style.massCultureReference', 'present', 'Tracer la référence à la culture de masse.'],
  'style.conceptual-art': ['creative', 'style.conceptStatement', 'present', 'Déclarer le concept prioritaire de l’objet proposé.'],
  'style.performance-art': ['creative', 'style.actionContext', 'present', 'Conserver le contexte d’une action performative.'],
  'style.installation': ['creative', 'style.spatialRelations', 'recorded', 'Exposer les relations spatiales de l’installation.'],
  'style.digital-art': ['creative', 'style.digitalOperations', 'recorded', 'Tracer les opérations numériques du choix stylistique.'],
  'style.bioart': ['creative', 'style.biologicalAuthority', 'zero', 'Ne pas convertir un choix bioartistique en autorité sur du vivant.'],
  'logic.propositional': ['logic', 'formula.valuation', 'present', 'Associer une formule propositionnelle à une valuation déclarée.'],
  'logic.negation': ['logic', 'negation.truthPair', 'different', 'Comparer la valeur de la proposition et celle de sa négation.'],
  'logic.conjunction': ['logic', 'conjunction.bothSupported', 'explicit', 'Exiger le soutien des deux conjoints avant d’affirmer leur conjonction.'],
  'logic.disjunction': ['logic', 'disjunction.witness', 'present', 'Conserver un disjoint témoin de la disjonction alléguée.'],
  'logic.material-conditional': ['logic', 'conditional.counterexamples', 'zero', 'Signaler les cas où l’antécédent est vrai et le conséquent faux.'],
  'logic.biconditional': ['logic', 'biconditional.truthPair', 'equal', 'Comparer les valeurs des deux propositions liées.'],
  'logic.truth-table': ['logic', 'table.valuations', 'recorded', 'Conserver les valuations utilisées dans la table.'],
  'logic.tautology': ['logic', 'tautology.falseValuations', 'zero', 'Signaler toute valuation fausse dans le domaine vérifié.'],
  'logic.contradiction': ['logic', 'contradiction.trueValuations', 'zero', 'Signaler une valuation vraie qui réfute la contradiction alléguée.'],
  'logic.equivalence': ['logic', 'equivalence.outputPair', 'equal', 'Comparer les sorties des deux formules sur les valuations déclarées.'],
  'logic.first-order': ['logic', 'firstOrder.domain', 'recorded', 'Borner l’analyse du premier ordre à un domaine déclaré.'],
  'logic.quantifier': ['logic', 'quantifier.scope', 'present', 'Déclarer le domaine et la portée d’un quantificateur.'],
  'logic.satisfiability': ['logic', 'satisfiability.witness', 'present', 'Conserver un modèle témoin de la satisfiabilité alléguée.'],
  'logic.modal': ['logic', 'modal.accessibility', 'recorded', 'Déclarer la relation d’accessibilité des mondes.'],
  'logic.possible-worlds': ['logic', 'modal.worldValuations', 'recorded', 'Conserver la valuation de chaque monde examiné.'],
  'logic.kripke-frame': ['logic', 'frame.relationProperties', 'recorded', 'Exposer les propriétés testées de la relation d’accessibilité.'],
  'logic.temporal': ['logic', 'temporal.trace', 'ordered', 'Borner une propriété temporelle à la trace observée.'],
  'logic.epistemic': ['logic', 'epistemic.agentInformation', 'recorded', 'Conserver les informations accessibles à chaque agent.'],
  'logic.deontic': ['logic', 'deontic.dutyScope', 'present', 'Déclarer sujet et portée d’une obligation.'],
  'logic.dynamic': ['logic', 'announcement.beforeAfter', 'different', 'Comparer l’état informationnel avant et après une annonce.'],
  'logic.paraconsistent': ['logic', 'contradiction.arbitraryConclusions', 'zero', 'Interdire l’explosion logique à partir d’une contradiction locale.'],
  'logic.paracomplete': ['logic', 'unknown.forcedTruth', 'zero', 'Conserver une valeur inconnue sans forcer vrai ou faux.'],
  'logic.intuitionistic': ['logic', 'proof.constructiveWitness', 'present', 'Exiger un témoin constructif dans le périmètre déclaré.'],
  'logic.many-valued': ['logic', 'logic.valueVocabulary', 'multiple', 'Déclarer le vocabulaire des valeurs avant l’évaluation.'],
  'logic.linear': ['logic', 'resource.duplicateConsumption', 'zero', 'Signaler la consommation multiple d’une ressource linéaire.'],
  'logic.quantum': ['logic', 'quantum.latticeContext', 'present', 'Déclarer le treillis utilisé sans le confondre avec un processeur quantique.'],
  'logic.higher-order': ['logic', 'higherOrder.typeUniverse', 'present', 'Borner les quantifications supérieures à un univers de types déclaré.'],
  'metalogic.soundness': ['logic', 'system.unsoundDerivations', 'zero', 'Signaler une dérivation qui ne préserve pas la vérité dans le modèle déclaré.'],
  'metalogic.completeness': ['logic', 'system.unprovedValidCases', 'zero', 'Mesurer les cas valides non dérivés dans le périmètre fini examiné.'],
  'metalogic.decidability': ['logic', 'decision.boundedProcedure', 'present', 'Déclarer la procédure et sa borne plutôt qu’une décidabilité universelle.'],
  'metalogic.godel-first-incompleteness': ['logic', 'incompleteness.systemAssumptions', 'recorded', 'Exposer les hypothèses du système auquel le résultat est appliqué.'],
  'metalogic.godel-second-incompleteness': ['logic', 'consistency.externalBasis', 'present', 'Déclarer la base externe d’une assurance de cohérence.'],
  'truth.tarski-undefinability': ['logic', 'truth.languageLevels', 'multiple', 'Séparer langage objet et métalangage dans une attribution de vérité.'],
  'truth.fixed-point': ['logic', 'truth.iterationComparison', 'equal', 'Comparer deux itérations avant d’alléguer un point fixe.'],
  'paradox.liar': ['logic', 'liar.undeterminedPreserved', 'explicit', 'Conserver l’indétermination d’une attribution autoréférentielle de vérité.'],
  'paradox.russell': ['logic', 'set.unrestrictedComprehension', 'zero', 'Signaler l’usage de compréhension non bornée dans la construction.'],
  'paradox.cantor': ['logic', 'set.universalSetAssumption', 'zero', 'Signaler l’hypothèse d’un ensemble universel non justifiée par le cadre.'],
  'paradox.burali-forti': ['logic', 'ordinal.totalityAssumption', 'zero', 'Ne pas transformer tous les ordinaux en un ensemble sans justification.'],
  'paradox.grelling-nelson': ['logic', 'predicate.selfApplicationTyped', 'explicit', 'Déclarer les niveaux de l’autoapplication du prédicat.'],
  'paradox.berry': ['logic', 'description.languageBoundary', 'present', 'Déclarer les limites du langage de description utilisé.'],
  'paradox.richard': ['logic', 'definition.metaObjectSeparation', 'explicit', 'Séparer définition en métalangage et objet construit.'],
  'paradox.sorites': ['logic', 'vagueness.thresholdPolicy', 'present', 'Déclarer la politique de seuil au lieu de résoudre implicitement le vague.'],
  'paradox.zeno': ['logic', 'limit.discretizationError', 'zero', 'Exposer l’erreur de discrétisation du modèle de mouvement.'],
  'paradox.fitch': ['logic', 'knowledge.modalAssumptions', 'recorded', 'Conserver les hypothèses modales du raisonnement sur la connaissabilité.'],
  'paradox.moore': ['logic', 'assertion.beliefConsistency', 'explicit', 'Signaler une assertion incompatible avec la croyance rapportée.'],
  'paradox.curry': ['logic', 'selfReference.unrestrictedRule', 'zero', 'Signaler l’usage d’une règle autoréférentielle non bornée.'],
  'paradox.twin': ['world', 'relativity.properTimes', 'different', 'Comparer les temps propres de trajectoires distinctes déclarées.'],
  'mathematics.number': ['logic', 'number.structuralRole', 'present', 'Déclarer le rôle structurel du nombre sans inférer un objet abstrait réel.'],
  'mathematics.infinite': ['logic', 'infinity.finiteExecutionBound', 'positive', 'Borner l’exécution finie d’une représentation de l’infini.'],
  'mathematics.continuum': ['logic', 'continuum.discretization', 'present', 'Déclarer la discrétisation d’un continuum représenté.'],
  'mathematics.potential-actual-infinity': ['interpretation', 'infinity.processTotalitySeparation', 'explicit', 'Séparer processus extensible et totalité infinie postulée.'],
  'mathematics.transfinite': ['logic', 'ordinal.cardinalSeparation', 'explicit', 'Distinguer ordre ordinal et taille cardinale.'],
  'mathematics.infinitesimal': ['logic', 'infinitesimal.numberSystem', 'present', 'Déclarer le système numérique de l’infiniment petit.'],
  'mathematics.nonstandard-analysis': ['logic', 'transfer.hypotheses', 'recorded', 'Exposer les hypothèses du principe de transfert invoqué.'],
  'mathematics.platonism': ['interpretation', 'abstract.existenceUnverified', 'explicit', 'Maintenir non vérifiée l’existence indépendante des objets abstraits.'],
  'mathematics.nominalism': ['interpretation', 'theory.nominalization', 'present', 'Déclarer la reformulation sans engagement envers les objets abstraits.'],
  'mathematics.fictionalism': ['interpretation', 'mathematics.fictionMarker', 'explicit', 'Marquer l’usage fictionnel des entités mathématiques.'],
  'mathematics.conceptualism': ['interpretation', 'concept.constructionContext', 'present', 'Situer la construction conceptuelle d’un objet mathématique.'],
  'mathematics.psychologism': ['interpretation', 'logic.psychologySeparation', 'explicit', 'Séparer validité logique et fait psychologique.'],
  'mathematics.logicism': ['logic', 'reduction.logicalAxioms', 'recorded', 'Déclarer les axiomes d’une réduction aux principes logiques.'],
  'mathematics.formalism': ['logic', 'formal.syntaxRules', 'recorded', 'Déclarer les règles de manipulation formelle des symboles.'],
  'mathematics.intuitionism': ['logic', 'construction.witness', 'present', 'Conserver un témoin constructif plutôt qu’un tiers exclu implicite.'],
  'mathematics.indispensability-argument': ['interpretation', 'theory.indispensabilityComparison', 'different', 'Comparer les théories avec et sans ressources mathématiques invoquées.'],
  'mathematics.foundations-crisis': ['logic', 'foundation.competingSystems', 'multiple', 'Conserver les systèmes fondationnels concurrents.'],
  'mathematics.set-theory': ['logic', 'set.membershipRules', 'recorded', 'Déclarer les règles d’appartenance et de construction des ensembles.'],
  'mathematics.zfc': ['logic', 'foundation.axiomSet', 'recorded', 'Conserver les axiomes utilisés sans présumer ZFC unique ou complet.'],
  'mathematics.type-theory': ['logic', 'type.assignment', 'present', 'Associer un type déclaré à la construction évaluée.'],
  'mathematics.category-theory': ['logic', 'category.morphismRelations', 'recorded', 'Déclarer les morphismes utilisés pour comparer les objets.'],
  'mathematics.structuralism': ['interpretation', 'structure.positions', 'recorded', 'Décrire les positions dans une structure avant des objets autonomes.'],
  'mathematics.ante-rem-structuralism': ['interpretation', 'structure.independenceUnverified', 'explicit', 'Maintenir non vérifiée l’existence indépendante des structures.'],
  'mathematics.in-re-structuralism': ['interpretation', 'structure.instances', 'recorded', 'Rattacher une structure à ses instances déclarées.'],
  'mathematics.post-rem-structuralism': ['interpretation', 'structure.abstractionSources', 'recorded', 'Conserver les systèmes à partir desquels la structure est abstraite.'],
  'mathematics.continuum-hypothesis': ['interpretation', 'hypothesis.axiomDependence', 'present', 'Déclarer les axiomes d’une discussion de l’hypothèse du continuum.'],
  'mathematics.hilbert-problems': ['logic', 'problem.openStatus', 'present', 'Conserver le statut du problème au lieu de présenter sa formulation comme solution.'],
  'mathematics.proof': ['logic', 'proof.verificationProcedure', 'present', 'Conserver une procédure inspectable de vérification de la preuve.'],
  'mathematics.proof-theory': ['logic', 'derivation.inferenceRules', 'recorded', 'Exposer les règles de la dérivation étudiée.'],
  'mathematics.homotopy-type-theory': ['logic', 'equality.typeContext', 'present', 'Déclarer le contexte typé d’une égalité homotopique invoquée.'],
  'mathematics.mathematical-intuition': ['interpretation', 'intuition.proofSeparation', 'explicit', 'Séparer intuition mathématique et justification démonstrative.'],
  'mathematics.mathematical-beauty': ['creative', 'mathematics.aestheticCriteria', 'recorded', 'Déclarer les critères d’économie et d’élégance sans les confondre avec une preuve.'],
});

function profileFor(id) {
  const tuple = PROFILES[id];
  if (!tuple) return null;
  const [primitive, field, predicate, interpretation] = tuple;
  return { primitive, field, predicate, interpretation };
}

module.exports = { PROFILES, profileFor };
