'use strict';

/**
 * @file formalizationArtifact.js
 * @description FormalizationArtifact — the immutable bridge between a natural-language
 * mathematical claim and its formalization in a target formal language (Lean 4 today).
 *
 * OWN IDENTITY: FormalizationArtifact is the SOURCE OF TRUTH for what Lean must prove.
 * It stores both the natural statement (human meaning) and the formal statement
 * (machine meaning), plus fingerprints for binding.
 *
 * BINDING AUTHORITY: When a ProofArtifact is attached to a FormalizationArtifact,
 * the formalStatement (and its fingerprint) is what Lean MUST prove. The proof worker
 * ONLY supplies the proof body after `:=`. The theorem header is generated by GenOS
 * from the immutable FormalizationArtifact, never from worker-supplied text.
 *
 * This is the architectural replacement for the text-comparison approach where
 * extractLeanTheoremStatement() was used to compare fingerprints. The old approach
 * was spoofable because the worker could wrap the goal in a Lean string literal.
 * The new approach is NOT spoofable because GenOS generates the header from the
 * FormalizationArtifact itself.
 */

const { createHash } = require('node:crypto');

const SHA256 = /^sha256:[a-f0-9]{64}$/;

function naturalStatementFingerprint(statement) {
  if (!statement || typeof statement !== 'string') return null;
  return `sha256:${createHash('sha256').update(statement.normalize('NFC').trim()).digest('hex')}`;
}

function formalStatementFingerprint(statement) {
  if (!statement || typeof statement !== 'string') return null;
  return `sha256:${createHash('sha256').update(statement.normalize('NFC').trim()).digest('hex')}`;
}

class FormalizationArtifact {
  constructor(options = {}) {
    this.id = options.id || `formalization-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    this.naturalStatement = options.naturalStatement || '';
    this.naturalStatementFingerprint = options.naturalStatement
      ? naturalStatementFingerprint(options.naturalStatement)
      : null;
    this.formalLanguage = options.formalLanguage || 'lean4';
    this.formalStatement = options.formalStatement || '';
    this.formalStatementFingerprint = options.formalStatement
      ? formalStatementFingerprint(options.formalStatement)
      : null;
    this.formalizer = options.formalizer || null;
    this.imports = options.imports || [];
    this.environmentDigest = options.environmentDigest || null;
    this.provenance = options.provenance || null;
    this.createdAt = new Date().toISOString();

    // ─── Immutability : l'artefact devient autorité après construction ───
    // Deep-freeze des collections et de l'objet lui-même pour empêcher
    // la mutation post-enregistrement (cf. revue architecture 2026-09-22).
    Object.freeze(this.imports);
    Object.freeze(this.provenance);
    Object.freeze(this);
  }

  /**
   * Generate the immutable Lean theorem header from this artifact.
   *
   * The header is: theorem <name> : <formalStatement>
   *
   * This is the ONLY text that goes before `:=`. The proof worker supplies only
   * what comes after `:=`. This prevents the worker from wrapping the goal in a
   * string literal or proving a different statement.
   *
   * @param {object} options - generation options
   * @param {string} options.name - theorem name (defaults to 'genos_target')
   * @returns {string} the Lean theorem header (without `:=` or proof body)
   */
  generateLeanHeader(options = {}) {
    const name = options.name || 'genos_target';
    const statement = this.formalStatement || '';
    // Escape the statement properly for Lean source.
    // The formalStatement is already a valid Lean expression; we just embed it.
    // We do NOT quote it — quoting turns it into a string literal, which is the bug
    // we are fixing. The statement must be the type of the theorem, not a string.
    return `theorem ${name} :\n  ${statement}`;
  }

  /**
   * Generate the complete Lean source for verification: header + proof body.
   *
   * The header comes from this FormalizationArtifact (immutable).
   * The proofBody is supplied by the proof worker (mutable, only the proof).
   *
   * @param {object} options
   * @param {string} options.proofBody - the proof term/block after `:=`
   * @param {string} options.name - theorem name
   * @returns {string} complete Lean source
   */
  generateLeanSource(options = {}) {
    const header = this.generateLeanHeader(options);
    const proofBody = options.proofBody || '';
    if (!proofBody) return header + '\n:= by\n  sorry'; // never actually used for verification
    return header + '\n:= by\n' + proofBody;
  }

  /**
   * Check that a Lean source's theorem header matches this artifact's formalStatement.
   *
   * This is the binding check: the source must prove EXACTLY this formalStatement,
   * not a string-wrapped version, not a different statement.
   *
   * @param {string} source - the Lean source to check
   * @returns {object} { matched: boolean, headerStatement: string | null, error: string | null }
   */
  checkSourceBinding(source) {
    if (!source || typeof source !== 'string') {
      return { matched: false, headerStatement: null, error: 'Source is empty or not a string.' };
    }
    const trimmed = source.trim();
    // Extract the theorem header from the source.
    // We match: theorem <name> : <statement>
    // The statement is everything between `:` and `:=` (or end of line if no `:=`).
    const headerMatch = trimmed.match(/^theorem\s+\w+\s*:\s*([\s\S]*?)\s*(:=|$)/);
    if (!headerMatch) {
      return { matched: false, headerStatement: null, error: 'Could not extract theorem header from Lean source.' };
    }
    let headerStatement = headerMatch[1].trim();
    // Normalize: collapse all whitespace (including newlines) into single spaces.
    // This handles multi-line theorem headers like:
    //   theorem foo
    //   (n : Nat)
    //   :
    //   n + 0 = n := by
    // The formalStatement is a single-line normalized expression, so we must
    // normalize the extracted header the same way before fingerprint comparison.
    headerStatement = headerStatement.replace(/\s+/g, ' ');
    headerStatement = headerStatement.trim();
    // Compare fingerprints.
    const sourceFp = formalStatementFingerprint(headerStatement);
    if (!sourceFp) {
      return { matched: false, headerStatement, error: 'Could not compute fingerprint of extracted header.' };
    }
    if (sourceFp !== this.formalStatementFingerprint) {
      return {
        matched: false,
        headerStatement,
        error: `Statement fingerprint mismatch. Source header proves: "${headerStatement}" (fp: ${sourceFp}). Expected: "${this.formalStatement}" (fp: ${this.formalStatementFingerprint}).`,
      };
    }
    return { matched: true, headerStatement, error: null };
  }

  /**
   * Summary for debugging/telemetry.
   */
  summary() {
    return {
      id: this.id,
      naturalStatement: this.naturalStatement.substring(0, 80),
      naturalStatementFingerprint: this.naturalStatementFingerprint,
      formalLanguage: this.formalLanguage,
      formalStatement: this.formalStatement.substring(0, 80),
      formalStatementFingerprint: this.formalStatementFingerprint,
      formalizer: this.formalizer,
      imports: this.imports,
      provenance: this.provenance,
    };
  }
}

/**
 * Create a FormalizationRegistry — a map from canonical statement fingerprint
 * to FormalizationArtifact. Used by the runtime to store and retrieve
 * formalizations by their natural or formal fingerprint.
 */
class FormalizationRegistry {
  constructor() {
    this._byNaturalFingerprint = new Map();
    this._byFormalFingerprint = new Map();
    this._byId = new Map();
  }

  add(artifact) {
    if (!artifact || !(artifact instanceof FormalizationArtifact)) {
      throw new Error('FormalizationRegistry.add requires a FormalizationArtifact.');
    }
    if (artifact.naturalStatementFingerprint) {
      this._byNaturalFingerprint.set(artifact.naturalStatementFingerprint, artifact);
    }
    if (artifact.formalStatementFingerprint) {
      this._byFormalFingerprint.set(artifact.formalStatementFingerprint, artifact);
    }
    this._byId.set(artifact.id, artifact);
    return artifact;
  }

  /**
   * Retrieve a formalization by its canonical (natural) statement fingerprint.
   * This is the primary lookup: the runtime has the natural statement, looks up the
   * formalization, and uses the formalStatement as the binding authority.
   */
  getByCanonical(canonicalStatement) {
    if (!canonicalStatement || typeof canonicalStatement !== 'string') return null;
    const fp = naturalStatementFingerprint(canonicalStatement);
    return fp ? this._byNaturalFingerprint.get(fp) || null : null;
  }

  /**
   * Retrieve a formalization by its formal statement fingerprint.
   */
  getByFormalStatement(formalStatement) {
    if (!formalStatement || typeof formalStatement !== 'string') return null;
    const fp = formalStatementFingerprint(formalStatement);
    return fp ? this._byFormalFingerprint.get(fp) || null : null;
  }

  getById(id) {
    return this._byId.get(id) || null;
  }

  has(canonicalStatement) {
    return this.getByCanonical(canonicalStatement) !== null;
  }

  size() {
    return this._byId.size;
  }
}

function createFormalizationArtifact(options = {}) {
  return new FormalizationArtifact(options);
}

function createFormalizationRegistry() {
  return new FormalizationRegistry();
}

module.exports = {
  FormalizationArtifact,
  FormalizationRegistry,
  createFormalizationArtifact,
  createFormalizationRegistry,
  naturalStatementFingerprint,
  formalStatementFingerprint,
};
