'use strict';

/**
 * @file proofArtifact.js
 * @description ProofArtifact — a mathematical result with verification receipt.
 * No theorem/lemma exists without a kernel certificate.
 *
 * ProofArtifact is a VIEW over FormalResult + LeanIncrementalGate receipt.
 * Direct receipt attachment is FORBIDDEN — verification MUST pass through Lean gate.
 * No fake receipts, no sorry/admit, no bypass.
 *
 * BINDING AUTHORITY:
 *   - When a FormalizationArtifact is supplied via attachFormalResult(formalResult, formalization),
 *     its formalStatement is the IMMUTABLE authority for what Lean must prove.
 *     The proof worker supplies ONLY the proof body after `:=`.
 *     The theorem header is generated by GenOS from the FormalizationArtifact.
 *     This replaces the text-comparison approach (extractLeanTheoremStatement) which was
 *     spoofable via string-wrapping (e.g., proving "∀ n, n + 0 = n" as a string literal).
 *   - When absent, fall back to canonicalStatement fingerprint comparison (text-based,
 *     less robust — kept for backward compatibility with non-formalized artifacts).
 *
 * CRITICAL: The Lean source MUST prove EXACTLY the canonicalStatement,
 * not a trivial substitute like `True`. The Lean 4 kernel is the physics
 * of this world — no statement passes without a valid proof of itself.
 */

const { createFormalResult, decodeFormalResult } = require('../formalResultService');
const { LeanIncrementalGate, PLACEHOLDER_PROOF } = require('../epistemicScheduler/leanIncrementalGate');
const { createHash } = require('node:crypto');

const SHA256 = /^sha256:[a-f0-9]{64}$/;
const ARTIFACT_TYPES = Object.freeze(['conjecture', 'lemma', 'theorem', 'counterexample', 'obligation']);

/**
 * Check if a Lean source is a trivial placeholder (e.g., proves `True`).
 * This prevents the classic epistemic bypass: proving something other than the claim.
 */
function isTrivialLeanSource(source) {
  if (!source || typeof source !== 'string') return true;
  const trimmed = source.trim();
  // Detect common trivial patterns
  const trivialPatterns = [
    /theorem\s+\w+\s*:\s*True\s*:=/,
    /theorem\s+\w+\s*:\s*False\s*→/,
    /:\s*True\s*:=\s*by\s+trivial/,
    /:\s*True\s*:=\s*by\s+tauto/,
    /exact\s+\(\s*by\s+trivial\s*\)/,
  ];
  return trivialPatterns.some(p => p.test(trimmed));
}

/**
 * Extract the theorem statement from a Lean source string.
 * Returns the statement text between `theorem ... :` and `:=`, with surrounding quotes stripped, or null if not found.
 */
function extractLeanTheoremStatement(source) {
  if (!source || typeof source !== 'string') return null;
  const trimmed = source.trim();
  // Match theorem statement: theorem name : "statement" := or theorem name : statement :=
  const match = trimmed.match(/^theorem\s+\w+\s*:\s*"((?:[^"\\]|\\.)*)"\s*:=/);
  if (match) {
    return match[1];
  }
  const match2 = trimmed.match(/^theorem\s+\w+\s*:\s*((?:[^"\\]|\\.)*)\s*:=/);
  if (match2) {
    return match2[1];
  }
  // Try thin colon pattern: theorem name : statement :=
  const match3 = trimmed.match(/^theorem\s+\S+\s*:\s*((?:[^"\\]|\\.)*)\s*=/);
  if (match3) {
    return match3[1];
  }
  return null;
}

/**
 * Check if the Lean source proves the expected statement (by fingerprint).
 * Compares the extracted Lean theorem statement against the expected canonicalStatement fingerprint.
 */
function doesLeanSourceProveStatement(source, expectedFingerprint) {
  if (!source || typeof source !== 'string' || !expectedFingerprint) return false;
  const statement = extractLeanTheoremStatement(source);
  if (!statement) return false;
  const statementFp = `sha256:${require('node:crypto').createHash('sha256').update(statement).digest('hex')}`;
  return statementFp === expectedFingerprint;
}

/**
 * Compute statement fingerprint from canonical statement for binding.
 * The Lean proof must produce a sourceDigest that can be linked to this.
 */
function statementFingerprint(statement) {
  return `sha256:${createHash('sha256').update(statement).digest('hex')}`;
}

class ProofArtifact {
  constructor(options = {}) {
    this.id = options.id || `art-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    this.type = options.type || 'conjecture';
    this.statement = options.statement || '';
    this.domain = options.domain || 'general';
    this.proof = options.proof || null;
    this.receipt = null;
    this.status = options.status || 'conjecture';
    this.dependencies = options.dependencies || [];
    this.producedBy = options.producedBy || null;
    this.verifiedBy = null;
    this.createdAt = new Date().toISOString();
    this._formalResult = null;
    this._leanReceipt = null;
    this._statementFingerprint = options.statement ? statementFingerprint(options.statement) : null;
  }

  /**
   * Attach a FormalResult created by formalResultService.
   * The result MUST have valid proof evidence and real SHA-256 fingerprints.
   * This does NOT verify — it only attaches the formalized statement.
   * Verification requires verifyThroughLean().
   */
  attachFormalResult(formalResult, formalization = null) {
    if (!formalResult || typeof formalResult !== 'object') {
      throw new Error('ProofArtifact.attachFormalResult requires a FormalResult object.');
    }
    if (!formalResult.resultId || !SHA256.test(formalResult.resultId)) {
      throw new Error('FormalResult must have a valid SHA-256 resultId.');
    }
    if (!formalResult.semanticFingerprint || !SHA256.test(formalResult.semanticFingerprint)) {
      throw new Error('FormalResult must have a valid SHA-256 semanticFingerprint.');
    }
    if (formalResult.status === 'verified' && formalResult.evidence.kind !== 'proof') {
      throw new Error('Verified status requires proof evidence.');
    }
    // Reject any attempt to inject fake receipts
    if (formalResult.status === 'verified' && (!formalResult.provenance || !formalResult.provenance.source?.digest || !SHA256.test(formalResult.provenance.source.digest))) {
      throw new Error('Verified FormalResult requires valid provenance with SHA-256 source digest.');
    }
    // Bind statement fingerprint
    if (!formalResult.canonicalStatement) {
      throw new Error('FormalResult must have a canonicalStatement.');
    }
    const expectedFp = statementFingerprint(formalResult.canonicalStatement);

    // Formalization binding: if a FormalizationArtifact is supplied, use its
    // leanExpressionFingerprint as the reference for what Lean must prove.
    // This is the immutable theorem header. When absent, fall back to the
    // statement fingerprint derived from canonicalStatement (text-based,
    // less robust — kept for backward compat with non-formalized artifacts).
    this._formalization = formalization || null;
    this._bindingAuthority = formalization ? 'formalization' : 'statement';
    this._formalizationFp = formalization ? formalization.leanExpressionFingerprint : null;

    this._statementFingerprint = expectedFp;

    this._formalResult = formalResult;
    this.status = formalResult.status;
    this.verifiedBy = formalResult.producer?.model || null;
    return this;
  }

  /**
   * Verify this artifact through the LeanIncrementalGate.
   * This is the ONLY way to produce a verified artifact.
   * Uses leanGate.verifyNode() which enforces: prerequisites, validation, graph update, publish.
   * The Lean source MUST prove the canonicalStatement, not a trivial substitute.
   */
  async verifyThroughLean(leanGate, source) {
    if (!leanGate || typeof leanGate.verifyNode !== 'function') {
      throw new Error('ProofArtifact.verifyThroughLean requires a LeanIncrementalGate instance.');
    }
    if (!this._formalResult) {
      throw new Error('Cannot verify: no FormalResult attached. Call attachFormalResult first.');
    }
    if (!this._formalResult.canonicalStatement) {
      throw new Error('Cannot verify: FormalResult missing canonicalStatement.');
    }

    // CRITICAL: Reject trivial Lean sources that don't prove the actual statement
    if (isTrivialLeanSource(source)) {
      throw new Error('Lean source proves trivial True — must prove the canonicalStatement exactly.');
    }
    if (PLACEHOLDER_PROOF.test(source || '')) {
      throw new Error('Lean placeholders sorry/admit are forbidden.');
    }
    if (!SHA256.test(leanGate.environmentDigest)) {
      throw new Error('LeanIncrementalGate must have a valid SHA-256 environmentDigest.');
    }
    if (!leanGate.toolchainVersion || !String(leanGate.toolchainVersion).trim()) {
      throw new Error('LeanIncrementalGate must have a pinned toolchainVersion.');
    }

    // CRITICAL: Verify that the Lean source proves the exact statement
    // defined by the binding authority (formalization or canonicalStatement).
    // When a FormalizationArtifact is present (this._formalization !== null),
    // it is the immutable authority: its formalStatement is what Lean MUST prove.
    // The proof worker supplies ONLY the proof body after `:=`; the theorem header
    // is generated by GenOS from the FormalizationArtifact.
    // When absent, fall back to the text-based fingerprint comparison on
    // canonicalStatement (less robust — kept for backward compat).
    if (this._formalization) {
      // Immutable authority: the FormalizationArtifact's formalStatement.
      // Check that the source header matches the formalization's formalStatement.
      const bindingCheck = this._formalization.checkSourceBinding(source);
      if (!bindingCheck.matched) {
        throw new Error('Lean source does not prove the expected formalStatement. ' + (bindingCheck.error || 'Binding mismatch.'));
      }
      // Binding passed: the header matches exactly.
      // Proceed to gate verification.
    } else if (this._statementFingerprint) {
      // Fallback: extract statement from Lean source and compare fingerprints.
      // This is text-based and less robust (see isTrivialLeanSource bypass
      // where the worker wraps the goal in a string literal).
      const extractedStmt = extractLeanTheoremStatement(source);
      if (extractedStmt) {
        const { createHash } = require('node:crypto');
        const stmtFp = 'sha256:' + createHash('sha256').update(extractedStmt).digest('hex');
        if (stmtFp !== this._statementFingerprint) {
          throw new Error('Lean source does not prove the expected canonicalStatement. Statement fingerprint mismatch. Extracted: ' + extractedStmt + ' Expected fp: ' + this._statementFingerprint);
        }
      } else {
        throw new Error('Could not extract theorem statement from Lean source.');
      }
    } else {
      throw new Error('Cannot verify: no binding authority available (no formalization, no statement fingerprint).');
    }

    // Use the gate's verifyNode — this enforces all guarantees:
    // - graph.getNode() type check
    // - status === 'formalized' 
    // - prerequisitesVerified() with dependency receipts
    // - validateRequest() including sorry/admit check
    // - graph.updateStatus()
    // - publish()
    const nodeId = this._formalResult.resultId.replace('sha256:', '').slice(0, 64); // derive nodeId
    const leanNodeId = `node-${nodeId}`; // adapter for gate
    
    // Ensure the gate has this node registered with the right statement
    const graph = leanGate.graph;
    const existingNode = graph.getNode(leanNodeId);
    if (!existingNode) {
      // Register the node with the canonical statement
      graph.addNode({
        nodeId: leanNodeId,
        type: this.type === 'theorem' ? 'theorem' : 'lemma',
        canonicalStatement: this._formalResult.canonicalStatement,
        status: 'formalized',
      });
    } else if (existingNode.canonicalStatement !== this._formalResult.canonicalStatement) {
      throw new Error('Gate node statement mismatch with FormalResult canonicalStatement.');
    }

    // Call the gate's verifyNode — this is the ONLY path to verification
    const receipt = await leanGate.verifyNode({
      nodeId: leanNodeId,
      source,
      timeoutMs: 300000,
      leanExecutable: 'lean',
    });

    if (receipt.status !== 'passed') {
      this.status = 'failed';
      this._leanReceipt = receipt;
      return false;
    }

    // CRITICAL: Atomic transition — create NEW FormalResult with status=verified
    // This replaces the old formalResult entirely, no partial state
    const verifiedFormalResult = createFormalResult({
      canonicalStatement: this._formalResult.canonicalStatement,
      status: 'verified',
      evidence: {
        kind: 'proof',
        content: this._formalResult.evidence?.content || source,
        reproduction: { command: 'lean', environment: leanGate.toolchainVersion },
      },
      assumptions: this._formalResult.assumptions,
      validityDomain: this._formalResult.validityDomain,
      dependencies: this._formalResult.dependencies,
      provenance: {
        ...this._formalResult.provenance,
        transformations: [
          ...(this._formalResult.provenance?.transformations || []),
          `lean_verification:${receipt.receiptDigest}`,
        ],
      },
      producer: {
        model: leanGate.toolchainVersion,
        version: '1.0',
      },
    });

    // Verify integrity of the new result
    if (verifiedFormalResult.status !== 'verified') {
      throw new Error('Verified FormalResult creation failed integrity check.');
    }

    this._formalResult = verifiedFormalResult;
    this._leanReceipt = receipt;
    this.receipt = {
      resultId: this._formalResult.resultId,
      semanticFingerprint: this._formalResult.semanticFingerprint,
      status: 'verified',
      evidence: this._formalResult.evidence,
      provenance: this._formalResult.provenance,
      leanReceipt: receipt,
    };
    this.status = 'verified';
    this.verifiedBy = leanGate.toolchainVersion;
    return true;
  }

  /**
   * Check if artifact is genuinely verified.
   * Requires: verified status, real FormalResult(status=verified), real Lean receipt with valid SHA-256 digests.
   */
  isVerified() {
    return this.status === 'verified'
      && this._formalResult !== null
      && this._formalResult.status === 'verified'
      && this._formalResult.evidence?.kind === 'proof'
      && this._leanReceipt !== null
      && this._leanReceipt.status === 'passed'
      && SHA256.test(this._leanReceipt.sourceDigest || '')
      && SHA256.test(this._leanReceipt.receiptDigest || '')
      && SHA256.test(this._leanReceipt.environmentDigest || '');
  }

  summary() {
    return {
      id: this.id,
      type: this.type,
      statement: this.statement.substring(0, 80),
      status: this.status,
      verified: this.isVerified(),
      producedBy: this.producedBy,
      hasFormalResult: this._formalResult !== null,
      hasLeanReceipt: this._leanReceipt !== null,
      formalResultStatus: this._formalResult?.status,
    };
  }
}

function createProofArtifact(options) {
  return new ProofArtifact(options);
}

module.exports = {
  ProofArtifact,
  createProofArtifact,
  ARTIFACT_TYPES,
  isTrivialLeanSource,
  statementFingerprint,
};
