import { start } from './app.mjs';
import { startSupervision } from './supervision.mjs';
import { startManagement } from './management.mjs';
import { startFiles } from './files.mjs';
import { startOperations } from './operations.mjs';
import { startResearch } from './research.mjs';
import { startNavigation } from './navigation.mjs';
import { startOnboarding } from './onboarding.mjs';
import { startPresentation } from './presentation.mjs';
import { startWorlds } from './worlds.mjs';
import { startKnowledge } from './knowledge.mjs';
start();
startSupervision();
startManagement();
startFiles();
startOperations();
startResearch();
startWorlds();
startKnowledge();
startNavigation();
startOnboarding();
startPresentation();
