import { start } from './app.mjs';
import { startSupervision } from './supervision.mjs';
import { startManagement } from './management.mjs';
import { startFiles } from './files.mjs';
import { startOperations } from './operations.mjs';
import { startResearch } from './research.mjs';
start();
startSupervision();
startManagement();
startFiles();
startOperations();
startResearch();
