use super::ArgsMacro;
use std::path::PathBuf;

#[derive(ArgsMacro, Debug)]
pub struct InspectCommand {
    #[command(subcommand)]
    pub command: InspectSubcommands,
}

#[derive(clap::Subcommand, Debug)]
pub enum InspectSubcommands {
    /// Render a belief's provenance tree: the belief, its evidence tool
    /// outputs (T1), and the events that produced them (E1).
    Belief(InspectBeliefArgs),
}

#[derive(ArgsMacro, Debug)]
pub struct InspectBeliefArgs {
    /// Snapshot the belief lives on: file path or snapshot id resolved in the
    /// snapshot store.
    #[arg(long)]
    pub snapshot: String,
    /// Belief id to inspect. Resolved against the snapshot's own `state.beliefs`.
    #[arg(long = "belief-id")]
    pub belief_id: String,
    /// Event store to look up the originating `ToolCompleted`/`ToolFailed`
    /// event in. Optional; when absent, the tree shows tool output nodes
    /// without their `generated by` grandchild.
    #[arg(long)]
    pub events: Option<PathBuf>,
    #[arg(long, default_value = ".genos")]
    pub root: PathBuf,
    /// Snapshot store used to resolve `--snapshot` by id.
    #[arg(long)]
    pub snapshots: Option<PathBuf>,
    #[arg(long, value_enum, default_value_t = super::InspectFormat::Text)]
    pub format: InspectFormat,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, super::ValueEnum)]
pub enum InspectFormat {
    Text,
    Json,
    Yaml,
}
