'use strict';

const SCOPES = Object.freeze(['mission', 'workspace', 'project', 'persistent']);
const SESSION_STATUSES = Object.freeze(['FORMING', 'ACTIVE', 'RECOVERING', 'DEGRADED', 'ESCALATED', 'QUIESCENT', 'CLOSED']);
const PATCH_STATUSES = Object.freeze(['AVAILABLE', 'OCCUPIED', 'VACANT', 'QUARANTINED', 'UNAVAILABLE']);
const DEME_STATUSES = Object.freeze(['FOUNDING', 'ESTABLISHING', 'ACTIVE', 'STRESSED', 'AT_RISK', 'COLLAPSED', 'DORMANT', 'QUARANTINED', 'RECOLONIZING']);
const PROPAGULE_TYPES = Object.freeze(['AGENT', 'GENOME', 'COGNITIVE_RECIPE', 'PROCEDURE', 'ARTIFACT', 'MEMORY_FRAGMENT', 'CLAIM', 'COUNTEREXAMPLE', 'TEST', 'VERIFIER', 'STRATEGY', 'TOOL_CONFIG', 'ELITE', 'BOUNDS']);
const EVENT_TYPES = Object.freeze([
  'SESSION_CREATED', 'PATCH_CREATED', 'PATCH_STATUS_CHANGED', 'DEME_CREATED', 'DEME_STATUS_CHANGED', 'DEME_PROFILE_UPDATED', 'DEME_WORKSPACE_ATTACHED', 'DEME_BOUNDARY_VIOLATION', 'DEME_BUDGET_CONSUMED', 'MIGRATION_OFFERED', 'MIGRATION_ACCEPTED',
  'MIGRATION_REJECTED', 'MIGRATION_ROLLED_BACK', 'DEME_AT_RISK', 'LOCAL_EXTINCTION', 'COLONIZATION_STARTED',
  'COLONIZATION_FAILED', 'RECOLONIZATION_COMPLETED', 'CORRIDOR_CHANGED', 'RESCUE_OUTCOME_RECORDED',
  'REGIONAL_CYCLE_RECORDED', 'REGIONAL_CYCLE_FAILED'
]);

module.exports = { SCOPES, SESSION_STATUSES, PATCH_STATUSES, DEME_STATUSES, PROPAGULE_TYPES, EVENT_TYPES };
