'use strict';
const assert = require('node:assert/strict');
const { validatePayload, validateRequest } = require('../bin/orchestratorRequestValidation.cjs');
for (const value of [null, [], 'orchestrate', 1]) assert.throws(() => validatePayload(value));
validatePayload({});
for (const action of ['orchestrate', 'dispatch_worker', 'philosophy']) validateRequest(action, {});
assert.throws(() => validateRequest('typo', {}), /Unknown/);
for (const timeoutMs of [0, -1, NaN, Infinity, 'invalid']) assert.throws(() => validateRequest('orchestrate', { timeoutMs }));
validateRequest('orchestrate', { timeoutMs: 5000 });
console.log('Malformed orchestration requests are rejected before mission persistence.');
