const TOOL_ALIASES: Record<string, string> = {
  genos_create: 'Forge',
  genos_snapshot: 'Snap',
  genos_restore: 'Rewind',
  genos_fork: 'Fork',
  genos_run: 'Runner',
  genos_inspect: 'Scout',
  genos_diff: 'Delta',
  genos_lineage: 'Lineage',
  genos_replay: 'Replay',
  genos_merge: 'Merge',
  genos_workspace_experiment: 'Lab',
  genos_causal_replay_experiment: 'WhatIf',
  genos_incident_experiment: 'FaultLab',
  genos_scientific_experiment: 'Science',
  genos_security_coevolution: 'Sentinel',
  genos_bug_investigation: 'Trace',
  genos_diagnose: 'Pulse',
  genos_hypothesis_evidence: 'Evidence',
  genos_solve: 'Solver',
  genos_evaluate_trajectories: 'Score',
  genos_record_decision: 'Decide',
  genos_blame: 'Blame',
  genos_invalidate_assumption: 'Axiom',
  genos_record_experience: 'Learn',
  genos_search_failures: 'Failures',
  genos_cherry_pick_experience: 'Cherry',
  genos_adversarial_review: 'Audit',
  genos_future_ci: 'FutureCI',
  genos_repository_genome: 'RepoDNA',
  genos_bisect_agent: 'Bisect',
  genos_analyze_trajectory: 'Analyze',
  genos_compile_memory: 'Compile',
  genos_resilience_apoptosis: 'Apoptosis',
  genos_resilience_cryptobiosis: 'Cryo',
  genos_resilience_hypermutation: 'Mutate',
  genos_resilience_circuit_breaker: 'Breaker',
  genos_biomimicry_swarm_consensus: 'Quorum',
  genos_biomimicry_flocking_explore: 'Flock',
  genos_biomimicry_network_quorum: 'Mycelia',
  genos_biomimicry_distributed_huddle: 'Huddle'
};

export function getToolAlias(name: string): string {
  return TOOL_ALIASES[name] || name.replace(/^genos_/, '').split('_').map((part) => part[0]?.toUpperCase() + part.slice(1)).join(' ');
}
