'use strict';

const TEAM_RUN_STATUS = Object.freeze([
  'FORMING', 'READY', 'RUNNING', 'REPAIRING', 'COMPLETED', 'FAILED', 'BLOCKED', 'CANCELLED'
]);
const TEAM_RUN_PHASE = Object.freeze([
  'ELIGIBILITY', 'FORMATION', 'PREBRIEF', 'EXECUTION', 'INTEGRATION', 'REPAIR', 'DEBRIEF'
]);
const MEMBER_STATUS = Object.freeze(['PLANNED', 'ACTIVE', 'BLOCKED', 'COMPLETED', 'FAILED', 'REPLACED']);
const PARTICIPATION_MODES = Object.freeze(['FULL', 'CONSULTATIVE', 'OBSERVER', 'ON_DEMAND']);
const WORK_NODE_STATUS = Object.freeze(['BLOCKED', 'READY', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED']);
const HANDOFF_STATUS = Object.freeze([
  'PROPOSED', 'READY_FOR_REVIEW', 'ACCEPTED', 'ACCEPT', 'PARTIAL_ACCEPT', 'REJECT', 'REQUEST_REPAIR', 'REQUEST_CLARIFICATION'
]);
const HANDOFF_TYPES = Object.freeze(['DELIVERY', 'DELEGATION', 'CONSULTATION', 'VALIDATION', 'ESCALATION']);

module.exports = { TEAM_RUN_STATUS, TEAM_RUN_PHASE, MEMBER_STATUS, PARTICIPATION_MODES, WORK_NODE_STATUS, HANDOFF_STATUS, HANDOFF_TYPES };
