const CREATE_INDEXES_LINES = [
"CREATE INDEX IF NOT EXISTS idx_telemetry_created ON telemetry_events(created_at);",
"CREATE INDEX IF NOT EXISTS idx_telemetry_agent ON telemetry_events(agent_id);",
"CREATE INDEX IF NOT EXISTS idx_trace_spans_agent ON trace_spans(agent_id);",
"CREATE INDEX IF NOT EXISTS idx_trajectories_status ON trajectories(status);",
"CREATE INDEX IF NOT EXISTS idx_lineage_workspace ON lineage_nodes(workspace_id);",
"CREATE INDEX IF NOT EXISTS idx_access_keys_hash ON access_keys(key_hash);",
"CREATE INDEX IF NOT EXISTS idx_experiments_status ON experiments(status);",
"CREATE INDEX IF NOT EXISTS idx_snapshots_workspace ON workspace_snapshots(workspace_id);",
"CREATE INDEX IF NOT EXISTS idx_votes_proposal ON swarm_votes(proposal_id);",
"CREATE INDEX IF NOT EXISTS idx_trinity_worlds_agent ON trinity_worlds(agent_id);",
"CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at);",
"CREATE INDEX IF NOT EXISTS idx_approvals_status ON platform_approvals(status);",
"CREATE INDEX IF NOT EXISTS idx_compliance_framework ON compliance_reports(framework, created_at);",
"CREATE INDEX IF NOT EXISTS idx_ide_workspace ON ide_integrations(workspace_id, ide);",
"CREATE INDEX IF NOT EXISTS idx_provenance_subject ON provenance_records(subject_type, subject_id);",
"CREATE INDEX IF NOT EXISTS idx_provenance_payload_hash ON provenance_records(payload_hash);",
"CREATE INDEX IF NOT EXISTS idx_provenance_parent_hash ON provenance_records(parent_hash);",
"CREATE INDEX IF NOT EXISTS idx_evaluation_benchmark ON evaluation_runs(benchmark, created_at);",
"CREATE INDEX IF NOT EXISTS idx_strategy_contract_agent ON strategy_contracts(agent_id, version DESC);",
"CREATE INDEX IF NOT EXISTS idx_strategy_execution_agent ON strategy_execution_runs(agent_id, created_at DESC);",
"CREATE INDEX IF NOT EXISTS idx_strategy_execution_steps ON strategy_execution_steps(run_id, sequence);",
"CREATE INDEX IF NOT EXISTS idx_workflows_workspace ON workflows(workspace_id, updated_at DESC);",
"CREATE INDEX IF NOT EXISTS idx_workflow_versions_workflow ON workflow_versions(workflow_id, version DESC);",
"CREATE UNIQUE INDEX IF NOT EXISTS idx_workspaces_tenant_name ON workspaces(COALESCE(organization_id, ''), COALESCE(project_id, ''), name);",
"CREATE INDEX IF NOT EXISTS idx_workflow_runs_workflow ON workflow_runs(workflow_id, created_at DESC);",
"CREATE INDEX IF NOT EXISTS idx_prompt_versions_prompt ON prompt_versions(prompt_id, version DESC);",
"CREATE INDEX IF NOT EXISTS idx_dataset_cases_dataset ON dataset_cases(dataset_id, created_at);",
"CREATE INDEX IF NOT EXISTS idx_rag_chunks_document ON rag_chunks(document_id, chunk_index);",
"CREATE INDEX IF NOT EXISTS idx_integrations_status ON integrations(status, created_at DESC);",
"CREATE INDEX IF NOT EXISTS idx_releases_environment ON releases(environment, status, created_at DESC);",
"CREATE INDEX IF NOT EXISTS idx_release_rollouts_scope ON release_rollouts(organization_id, project_id, created_at DESC);",
"CREATE INDEX IF NOT EXISTS idx_usage_ledger_scope ON usage_ledger(organization_id, project_id, occurred_at DESC);",
"CREATE INDEX IF NOT EXISTS idx_registry_artifacts_scope ON registry_artifacts(organization_id, project_id, kind, updated_at DESC);",
"CREATE INDEX IF NOT EXISTS idx_marketplace_listings_status ON marketplace_listings(status, created_at DESC);",
"CREATE INDEX IF NOT EXISTS idx_framework_executions_scope ON framework_executions(organization_id, project_id, created_at DESC);",
"CREATE INDEX IF NOT EXISTS idx_environments_org ON environments(organization_id, name);",
"CREATE INDEX IF NOT EXISTS idx_model_job_tokens ON model_job_tokens(job_id, id);",
"CREATE INDEX IF NOT EXISTS idx_projects_org ON projects(organization_id, name);",
"CREATE INDEX IF NOT EXISTS idx_org_memberships_principal ON organization_memberships(principal_id, organization_id);",
"CREATE INDEX IF NOT EXISTS idx_project_memberships_principal ON project_memberships(principal_id, project_id);",
"CREATE INDEX IF NOT EXISTS idx_synapses_target ON memory_synapses(target_id);",
"CREATE INDEX IF NOT EXISTS idx_synapses_weight ON memory_synapses(weight);",
"CREATE INDEX IF NOT EXISTS idx_synapses_pruning ON memory_synapses(c3_opsonization, cd47_expression);",
"CREATE INDEX IF NOT EXISTS idx_synapses_tenant ON memory_synapses(organization_id, project_id);",
"",
"-- Local user accounts for username/password login",
"CREATE TABLE IF NOT EXISTS users (",
"    id TEXT PRIMARY KEY,",
"    username TEXT NOT NULL UNIQUE COLLATE NOCASE,",
"    password_hash TEXT NOT NULL,",
"    role TEXT NOT NULL DEFAULT 'operator' CHECK (role IN ('admin', 'operator', 'viewer')),",
"    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,",
"    last_login_at DATETIME,",
"    is_active INTEGER DEFAULT 1",
");",
"CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);"
].join("\n");

const CREATE_INDEXES_SQL = CREATE_INDEXES_LINES;

module.exports = { CREATE_INDEXES_SQL };
