/**
 * MCP Tools Seed Definitions
 */

const MCP_TOOLS_LIST = [
  // Workspace Control
  { name: 'genos_create', cat: 'Workspace Control', risk: 'Amber', desc: 'Creates isolated branch workspace' },
  { name: 'genos_snapshot', cat: 'Workspace Control', risk: 'Low', desc: 'Captures full workspace timeline snapshot' },
  { name: 'genos_restore', cat: 'Workspace Control', risk: 'High', desc: 'Destructive rollback to prior snapshot' },
  { name: 'genos_fork', cat: 'Workspace Control', risk: 'Amber', desc: 'Forks workspace into parallel universe' },
  { name: 'genos_run', cat: 'Workspace Control', risk: 'High', desc: 'Executes sandboxed terminal commands' },
  { name: 'genos_inspect', cat: 'Workspace Control', risk: 'Low', desc: 'Inspects file AST and workspace state' },
  { name: 'genos_diff', cat: 'Workspace Control', risk: 'Low', desc: 'Calculates structural diffs between snapshots' },
  { name: 'genos_lineage', cat: 'Workspace Control', risk: 'Low', desc: 'Extracts full MCTS DAG lineage tree' },
  { name: 'genos_replay', cat: 'Workspace Control', risk: 'Low', desc: 'Step-by-step causal replay traversal' },
  { name: 'genos_merge', cat: 'Workspace Control', risk: 'High', desc: 'Merges parallel universe branch into master' },

  // Experimental Labs
  { name: 'genos_workspace_experiment', cat: 'Experimental Labs', risk: 'Amber', desc: 'Runs hypothesis testing in workspace' },
  { name: 'genos_causal_replay_experiment', cat: 'Experimental Labs', risk: 'Low', desc: 'Causal counterfactual incident replay' },
  { name: 'genos_incident_experiment', cat: 'Experimental Labs', risk: 'Amber', desc: 'Simulates fault injection and recovery' },
  { name: 'genos_scientific_experiment', cat: 'Experimental Labs', risk: 'Amber', desc: 'Executes scientific experiment protocols' },
  { name: 'genos_security_coevolution', cat: 'Experimental Labs', risk: 'High', desc: 'Red vs Blue adversarial security simulation' },
  { name: 'genos_bug_investigation', cat: 'Experimental Labs', risk: 'Low', desc: 'Automated root-cause fault localization' },
  { name: 'genos_diagnose', cat: 'Experimental Labs', risk: 'Low', desc: 'Diagnostic health and latency analysis' },
  { name: 'genos_hypothesis_evidence', cat: 'Experimental Labs', risk: 'Low', desc: 'Attaches evidence to causal hypotheses' },
  { name: 'genos_solve', cat: 'Experimental Labs', risk: 'Amber', desc: 'Synthesizes verified algorithmic solutions' },
  { name: 'genos_evaluate_trajectories', cat: 'Experimental Labs', risk: 'Low', desc: 'Evaluates candidate code trajectory scores' },

  // Knowledge & Experience
  { name: 'genos_record_decision', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Persists architectural decision records' },
  { name: 'genos_blame', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Performs semantic blame analysis on faults' },
  { name: 'genos_invalidate_assumption', cat: 'Knowledge & Experience', risk: 'Amber', desc: 'Invalidates stale architectural axioms' },
  { name: 'genos_record_experience', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Encodes episodic memory trajectory' },
  { name: 'genos_search_failures', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Searches historical failure taxonomy' },
  { name: 'genos_cherry_pick_experience', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Transfers learned heuristics across swarms' },
  { name: 'genos_adversarial_review', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Performs CVE and logic vulnerability scan' },
  { name: 'genos_future_ci', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Simulates forward CI impact of changes' },
  { name: 'genos_repository_genome', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Synthesizes structural repository graph' },
  { name: 'genos_bisect_agent', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Binary search agent decisions for regressions' },
  { name: 'genos_analyze_trajectory', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Deep AST inspect of trajectory code' },
  { name: 'genos_compile_memory', cat: 'Knowledge & Experience', risk: 'Amber', desc: 'Distills episodic memory into concise rules' },

  // Resilience & Biomimicry
  { name: 'genos_resilience_apoptosis', cat: 'Resilience & Security', risk: 'High', desc: 'Programmed self-termination of runaway nodes' },
  { name: 'genos_resilience_cryptobiosis', cat: 'Resilience & Security', risk: 'High', desc: 'State freeze and memory hibernation' },
  { name: 'genos_resilience_hypermutation', cat: 'Resilience & Security', risk: 'High', desc: 'Accelerated genetic prompt mutation' },
  { name: 'genos_resilience_circuit_breaker', cat: 'Resilience & Security', risk: 'High', desc: 'Manual trip or reset of tool circuit breaker' },
  { name: 'genos_biomimicry_swarm_consensus', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Honeybee dance quorum voting protocol' },
  { name: 'genos_biomimicry_flocking_explore', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Boids flocking exploration algorithm' },
  { name: 'genos_biomimicry_network_quorum', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Mycelial network quorum communication' },
  { name: 'genos_biomimicry_distributed_huddle', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Penguin huddle energy conservation mode' },

  // Auto-generated by Orchestrator CLI
  { name: 'genos_org_specialist_expert_committee', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Specialist Expert Committee organization mode' },
  { name: 'genos_org_blind_adversarial_review', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Blind Adversarial Review organization mode' },
  { name: 'genos_org_red_blue_coevolution', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Red Blue Coevolution organization mode' },
  { name: 'genos_org_brier_weighted_consensus', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Brier Weighted Consensus organization mode' },
  { name: 'genos_org_quorum_with_abstention', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Quorum With Abstention organization mode' },
  { name: 'genos_org_stigmergy', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Stigmergy organization mode' },
  { name: 'genos_org_flocking_boids', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Flocking Boids organization mode' },
  { name: 'genos_org_fish_school_search', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Fish School Search organization mode' },
  { name: 'genos_org_slime_mould_network', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Slime Mould Network organization mode' },
  { name: 'genos_org_grey_wolf_optimizer', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Grey Wolf Optimizer organization mode' },
  { name: 'genos_org_mycelial_routing', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Mycelial Routing organization mode' },
  { name: 'genos_org_dynamic_polyethism', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Dynamic Polyethism organization mode' },
  { name: 'genos_org_energy_huddle', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Energy Huddle organization mode' },
  { name: 'genos_org_network_silence', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Network Silence organization mode' },
  { name: 'genos_org_strategy_arena', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Strategy Arena organization mode' },
  { name: 'genos_org_hierarchical_merge', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Hierarchical Merge organization mode' },
  { name: 'genos_org_competitive_arena', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Competitive Arena organization mode' },
  { name: 'genos_org_isolated_recovery', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Isolated Recovery organization mode' },
  { name: 'genos_org_memory_compilation', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Memory Compilation organization mode' },
  { name: 'genos_strat_verify', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Verify strategy primitive' },
  { name: 'genos_strat_audit', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Audit strategy primitive' },
  { name: 'genos_strat_minimal_mutation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Minimal Mutation strategy primitive' },
  { name: 'genos_strat_tests', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Tests strategy primitive' },
  { name: 'genos_strat_plan', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Plan strategy primitive' },
  { name: 'genos_strat_independent_verify', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Independent Verify strategy primitive' },
  { name: 'genos_strat_vfs_dry_run', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Vfs Dry Run strategy primitive' },
  { name: 'genos_strat_permission_check', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Permission Check strategy primitive' },
  { name: 'genos_strat_blast_radius', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Blast Radius strategy primitive' },
  { name: 'genos_strat_slm_route', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Slm Route strategy primitive' },
  { name: 'genos_strat_entropy_check', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Entropy Check strategy primitive' },
  { name: 'genos_strat_frontier_escalation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Frontier Escalation strategy primitive' },
  { name: 'genos_strat_provider_route', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Provider Route strategy primitive' },
  { name: 'genos_strat_fallback_chain', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Fallback Chain strategy primitive' },
  { name: 'genos_strat_degraded_mode', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Degraded Mode strategy primitive' },
  { name: 'genos_strat_common_probes', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Common Probes strategy primitive' },
  { name: 'genos_strat_probe', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Probe strategy primitive' },
  { name: 'genos_strat_conditional_mutation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Conditional Mutation strategy primitive' },
  { name: 'genos_strat_belief_update', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Belief Update strategy primitive' },
  { name: 'genos_strat_expected_information_gain', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Expected Information Gain strategy primitive' },
  { name: 'genos_strat_next_probe', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Next Probe strategy primitive' },
  { name: 'genos_strat_snapshot_test', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Snapshot Test strategy primitive' },
  { name: 'genos_strat_safe_revert', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Safe Revert strategy primitive' },
  { name: 'genos_strat_impact_graph', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Impact Graph strategy primitive' },
  { name: 'genos_strat_provenance', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Provenance strategy primitive' },
  { name: 'genos_strat_isolated_run', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Isolated Run strategy primitive' },
  { name: 'genos_strat_single_mutation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Single Mutation strategy primitive' },
  { name: 'genos_strat_paired_evaluation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Paired Evaluation strategy primitive' },
  { name: 'genos_strat_heredity_experiment', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Heredity Experiment strategy primitive' },
  { name: 'genos_strat_variance_analysis', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Variance Analysis strategy primitive' },
  { name: 'genos_strat_select_winner', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Select Winner strategy primitive' },
  { name: 'genos_strat_preserve_losers', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Preserve Losers strategy primitive' },
  { name: 'genos_strat_multi_objective_evaluation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Multi Objective Evaluation strategy primitive' },
  { name: 'genos_strat_pareto_select', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Pareto Select strategy primitive' },
  { name: 'genos_strat_pareto_frontier', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Pareto Frontier strategy primitive' },
  { name: 'genos_strat_utopia_distance', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Utopia Distance strategy primitive' },
  { name: 'genos_strat_minimum_evaluation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Minimum Evaluation strategy primitive' },
  { name: 'genos_strat_prune', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Prune strategy primitive' },
  { name: 'genos_strat_reallocate', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Reallocate strategy primitive' },
  { name: 'genos_strat_branch_evolution', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Branch Evolution strategy primitive' },
  { name: 'genos_strat_recursive_fork', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Recursive Fork strategy primitive' },
  { name: 'genos_strat_rank_states', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Rank States strategy primitive' },
  { name: 'genos_strat_retain_top_k', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Retain Top K strategy primitive' },
  { name: 'genos_strat_expand', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Expand strategy primitive' },
  { name: 'genos_strat_mcts_select', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Mcts Select strategy primitive' },
  { name: 'genos_strat_prm_evaluate', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Prm Evaluate strategy primitive' },
  { name: 'genos_strat_backpropagate', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Backpropagate strategy primitive' },
  { name: 'genos_strat_mutate', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Mutate strategy primitive' },
  { name: 'genos_strat_temperature_schedule', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Temperature Schedule strategy primitive' },
  { name: 'genos_strat_stagnation_check', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Stagnation Check strategy primitive' },
  { name: 'genos_strat_affinity_selection', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Affinity Selection strategy primitive' },
  { name: 'genos_strat_select', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Select strategy primitive' },
  { name: 'genos_strat_breed', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Breed strategy primitive' },
  { name: 'genos_strat_speciation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Speciation strategy primitive' },
  { name: 'genos_strat_niche_preservation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Niche Preservation strategy primitive' },
  { name: 'genos_strat_search_memory', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Search Memory strategy primitive' },
  { name: 'genos_strat_similarity_rank', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Similarity Rank strategy primitive' },
  { name: 'genos_strat_cherry_pick_golden_path', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Cherry Pick Golden Path strategy primitive' },
  { name: 'genos_strat_avoid_known_dead_ends', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Avoid Known Dead Ends strategy primitive' },
  { name: 'genos_strat_preserve_provenance', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Preserve Provenance strategy primitive' },
  { name: 'genos_strat_experience_packets', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Experience Packets strategy primitive' },
  { name: 'genos_strat_knowledge_graph', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Knowledge Graph strategy primitive' },
  { name: 'genos_strat_reviewed_apply', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Reviewed Apply strategy primitive' },
  { name: 'genos_strat_belief_provenance', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Belief Provenance strategy primitive' },
  { name: 'genos_strat_contradiction_check', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Contradiction Check strategy primitive' },
  { name: 'genos_strat_source_refs', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Source Refs strategy primitive' },
  { name: 'genos_strat_stdp_update', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Stdp Update strategy primitive' },
  { name: 'genos_strat_causal_weighting', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Causal Weighting strategy primitive' },
  { name: 'genos_strat_prune_and_scale', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Prune And Scale strategy primitive' },
  { name: 'genos_strat_context_compaction', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Context Compaction strategy primitive' },
  { name: 'genos_strat_infer_traits', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Infer Traits strategy primitive' },
  { name: 'genos_strat_replicate', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Replicate strategy primitive' },
  { name: 'genos_strat_promote_trait', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Promote Trait strategy primitive' },
  { name: 'genos_strat_phenotype_evidence', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Phenotype Evidence strategy primitive' },
  { name: 'genos_strat_validate_child', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Validate Child strategy primitive' },
  { name: 'genos_strat_permissions', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Permissions strategy primitive' },
  { name: 'genos_strat_taint_tracking', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Taint Tracking strategy primitive' },
  { name: 'genos_strat_execution_receipt', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Execution Receipt strategy primitive' },
  { name: 'genos_strat_artifact_hash', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Artifact Hash strategy primitive' },
  { name: 'genos_strat_belief_gate', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Belief Gate strategy primitive' },
  { name: 'genos_strat_failure_window', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Failure Window strategy primitive' },
  { name: 'genos_strat_open', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Open strategy primitive' },
  { name: 'genos_strat_half_open', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Half Open strategy primitive' },
  { name: 'genos_strat_checkpoint', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Checkpoint strategy primitive' },
  { name: 'genos_strat_terminate', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Terminate strategy primitive' },
  { name: 'genos_strat_autopsy', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Autopsy strategy primitive' },
  { name: 'genos_strat_freeze_spore', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Freeze Spore strategy primitive' },
  { name: 'genos_strat_persist', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Persist strategy primitive' },
  { name: 'genos_strat_rehydrate', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Rehydrate strategy primitive' },
  { name: 'genos_strat_last_good_snapshot', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Last Good Snapshot strategy primitive' },
  { name: 'genos_strat_alternate_genome', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Alternate Genome strategy primitive' },
  { name: 'genos_strat_hot_spare', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Hot Spare strategy primitive' },
  { name: 'genos_strat_health_switch', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Health Switch strategy primitive' },
  { name: 'genos_strat_dead_letter_queue', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Dead Letter Queue strategy primitive' },
  { name: 'genos_strat_forensic_autopsy', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Forensic Autopsy strategy primitive' },
  { name: 'genos_strat_negative_selection', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Negative Selection strategy primitive' },
  { name: 'genos_strat_quarantine', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Quarantine strategy primitive' },
  { name: 'genos_strat_threat_memory', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Threat Memory strategy primitive' },
  { name: 'genos_strat_decoy_branch', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Decoy Branch strategy primitive' },
  { name: 'genos_strat_observe', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Observe strategy primitive' },
  { name: 'genos_strat_destroy_decoy', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Destroy Decoy strategy primitive' },
  { name: 'genos_strat_shannon_entropy', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Shannon Entropy strategy primitive' },
  { name: 'genos_strat_drift_threshold', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Drift Threshold strategy primitive' },
  { name: 'genos_strat_message_graph', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Message Graph strategy primitive' },
  { name: 'genos_strat_cycle_detection', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Cycle Detection strategy primitive' },
  { name: 'genos_strat_artifact_gate', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Artifact Gate strategy primitive' },
  { name: 'genos_strat_iteration_limit', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Iteration Limit strategy primitive' },
  { name: 'genos_strat_token_limit', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Token Limit strategy primitive' },
  { name: 'genos_strat_time_limit', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Time Limit strategy primitive' },
  { name: 'genos_strat_uncertainty_limit', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Uncertainty Limit strategy primitive' },
  { name: 'genos_strat_uncertainty_gate', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Uncertainty Gate strategy primitive' },
  { name: 'genos_strat_approval_request', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Approval Request strategy primitive' },
  { name: 'genos_strat_dag_mark_sweep', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Dag Mark Sweep strategy primitive' },
  { name: 'genos_strat_worktree_cleanup', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Worktree Cleanup strategy primitive' },
  { name: 'genos_strat_cas_gc', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Cas Gc strategy primitive' },
  { name: 'genos_strat_state_fold', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute State Fold strategy primitive' },
  { name: 'genos_strat_intervene', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Intervene strategy primitive' },
  { name: 'genos_strat_causal_diff', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Causal Diff strategy primitive' },
  { name: 'genos_strat_alternative_future', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Alternative Future strategy primitive' },
  { name: 'genos_strat_inject_change', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Inject Change strategy primitive' },
  { name: 'genos_strat_replay_dependencies', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Replay Dependencies strategy primitive' },
  { name: 'genos_strat_production_snapshot', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Production Snapshot strategy primitive' },
  { name: 'genos_strat_mutated_universes', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Mutated Universes strategy primitive' },
  { name: 'genos_strat_signature_match', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Signature Match strategy primitive' },
  { name: 'genos_strat_score_partial_repro', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Score Partial Repro strategy primitive' },
  { name: 'genos_strat_recursive_refinement', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Recursive Refinement strategy primitive' },
  { name: 'genos_strat_future_worlds', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Future Worlds strategy primitive' },
  { name: 'genos_strat_dependency_matrix', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Dependency Matrix strategy primitive' },
  { name: 'genos_strat_paired_execution', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Paired Execution strategy primitive' },
  { name: 'genos_strat_similarity', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Similarity strategy primitive' },
  { name: 'genos_strat_equivalence_verdict', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Equivalence Verdict strategy primitive' },
  { name: 'genos_strat_role_forks', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Role Forks strategy primitive' },
  { name: 'genos_strat_independent_reports', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Independent Reports strategy primitive' },
  { name: 'genos_strat_synthesis', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Synthesis strategy primitive' },
  { name: 'genos_strat_blind_critics', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Blind Critics strategy primitive' },
  { name: 'genos_strat_neutral_observer', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Neutral Observer strategy primitive' },
  { name: 'genos_strat_brier_scores', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Brier Scores strategy primitive' },
  { name: 'genos_strat_weighted_quorum', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Weighted Quorum strategy primitive' },
  { name: 'genos_strat_active_refusal', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Active Refusal strategy primitive' },
  { name: 'genos_strat_pheromone_deposit', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Pheromone Deposit strategy primitive' },
  { name: 'genos_strat_trail_selection', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Trail Selection strategy primitive' },
  { name: 'genos_strat_evaporation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Evaporation strategy primitive' },
  { name: 'genos_strat_separation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Separation strategy primitive' },
  { name: 'genos_strat_alignment', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Alignment strategy primitive' },
  { name: 'genos_strat_cohesion', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Cohesion strategy primitive' },
  { name: 'genos_strat_weighted_barycenter', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Weighted Barycenter strategy primitive' },
  { name: 'genos_strat_resource_shift', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Resource Shift strategy primitive' },
  { name: 'genos_strat_path_conductivity', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Path Conductivity strategy primitive' },
  { name: 'genos_strat_route_pruning', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Route Pruning strategy primitive' },
  { name: 'genos_strat_alpha_beta_delta', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Alpha Beta Delta strategy primitive' },
  { name: 'genos_strat_position_update', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Position Update strategy primitive' },
  { name: 'genos_strat_capability_route', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Capability Route strategy primitive' },
  { name: 'genos_strat_knowledge_transfer', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Knowledge Transfer strategy primitive' },
  { name: 'genos_strat_role_gradient', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Role Gradient strategy primitive' },
  { name: 'genos_strat_dynamic_assignment', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Dynamic Assignment strategy primitive' },
  { name: 'genos_strat_energy_observe', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Energy Observe strategy primitive' },
  { name: 'genos_strat_resource_equalize', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Resource Equalize strategy primitive' },
  { name: 'genos_strat_local_buffer', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Local Buffer strategy primitive' },
  { name: 'genos_strat_critical_or_success_flush', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Critical Or Success Flush strategy primitive' },
  { name: 'genos_strat_solver_tournament', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Solver Tournament strategy primitive' },
  { name: 'genos_strat_elo', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Elo strategy primitive' },
  { name: 'genos_strat_pareto', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Pareto strategy primitive' },
];

async function seedMcpTools(db) {
  for (const t of MCP_TOOLS_LIST) {
    await db.run(
      `INSERT OR REPLACE INTO mcp_tools (id, name, provider, category, risk_level, description, actions_json, is_locked, circuit_state) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      t.name, t.name, 'genos', t.cat, t.risk, t.desc, JSON.stringify([t.name]), 0, 'CLOSED'
    );
  }
}

module.exports = { seedMcpTools, MCP_TOOLS_LIST };
