const fs = require('fs');
const path = require('path');

const MCP_TOOLS_LIST = [
  { name: 'genos_philosophy', cat: 'Orchestration', risk: 'Low', desc: 'Canonical philosophical concept registry and safe evaluations' },
  { name: 'genos_fossil_record', cat: 'Fossilisation', risk: 'Amber', desc: 'Bury an extinct lineage as an immutable stratigraphic fossil' },
  { name: 'genos_fossil_list', cat: 'Fossilisation', risk: 'Low', desc: 'List fossils visible in the current tenant scope' },
  { name: 'genos_fossil_strata', cat: 'Fossilisation', risk: 'Low', desc: 'List dated fossil strata in the current tenant scope' },
  { name: 'genos_fossil_excavate', cat: 'Fossilisation', risk: 'Low', desc: 'Excavate a fossil in read-only mode with integrity verification' },
  { name: 'genos_fossil_decode', cat: 'Fossilisation', risk: 'Low', desc: 'Decode residual phenotype markers from a fossil' },
  { name: 'genos_fossil_candidate', cat: 'Fossilisation', risk: 'Amber', desc: 'Derive a non-promoted AgentDNA candidate from an intact fossil' },
  { name: 'genos_grns', cat: 'Epigenetics', risk: 'Low', desc: 'Gene Regulatory Networks integration' },
  { name: 'genos_routing_algorithm', cat: 'Ecology', risk: 'Low', desc: 'Routing algorithm execution' },
  { name: 'genos_social_trust', cat: 'Ecology', risk: 'Low', desc: 'Social trust computation' },
  { name: 'genos_thalamic_filtering', cat: 'Neurobiology', risk: 'Low', desc: 'Thalamic filtering process' },
  { name: 'genos_multisensory_integration', cat: 'Neurobiology', risk: 'Low', desc: 'Multisensory integration system' },
  { name: 'genos_necrosis_ledger', cat: 'Cellular', risk: 'Low', desc: 'Necrosis ledger system' },
  { name: 'genos_molecular_chaperone', cat: 'Cellular', risk: 'Low', desc: 'Molecular chaperones manager' },
  { name: 'genos_cell_division', cat: 'Cellular', risk: 'Low', desc: 'Cell division orchestrator' },
  { name: 'genos_dna_methylation', cat: 'Epigenetics', risk: 'Low', desc: 'DNA Methylation integration' },
  { name: 'genos_lamarckian_mutation', cat: 'Epigenetics', risk: 'Low', desc: 'Lamarckian evolution simulation' },
  { name: 'genos_coevolution', cat: 'Genetics', risk: 'Low', desc: 'Coevolution orchestration' },
  { name: 'genos_quantitative_genetics', cat: 'Genetics', risk: 'Low', desc: 'Quantitative genetics integration' },
  // Workspace Control
  { name: 'genos_create', cat: 'Workspace Control', risk: 'Amber', desc: 'Creates isolated branch workspace' },
  { name: 'genos_snapshot', cat: 'Workspace Control', risk: 'Low', desc: 'Captures full workspace timeline snapshot' },
  { name: 'genos_restore', cat: 'Workspace Control', risk: 'High', desc: 'Destructive rollback to prior snapshot' },
  { name: 'genos_fork', cat: 'Workspace Control', risk: 'Amber', desc: 'Forks workspace into parallel universe' },
  { name: 'genos_merge', cat: 'Workspace Control', risk: 'High', desc: 'Merges an isolated branch under evidence gates' },
  { name: 'genos_run', cat: 'Workspace Control', risk: 'High', desc: 'Executes sandboxed terminal commands' },
  { name: 'genos_inspect', cat: 'Workspace Control', risk: 'Low', desc: 'Inspects file AST and workspace state' },
  { name: 'genos_diff', cat: 'Workspace Control', risk: 'Low', desc: 'Calculates structural diffs between snapshots' },
  { name: 'genos_lineage', cat: 'Workspace Control', risk: 'Low', desc: 'Extracts full MCTS DAG lineage tree' },
  { name: 'genos_replay', cat: 'Workspace Control', risk: 'Low', desc: 'Step-by-step causal replay traversal' },
  // Experimental Labs
  { name: 'genos_workspace_experiment', cat: 'Experimental Labs', risk: 'Amber', desc: 'Runs hypothesis testing in workspace' },
  { name: 'genos_causal_replay_experiment', cat: 'Experimental Labs', risk: 'Low', desc: 'Causal counterfactual incident replay' },
  { name: 'genos_incident_experiment', cat: 'Experimental Labs', risk: 'Amber', desc: 'Simulates fault injection and recovery' },
  { name: 'genos_scientific_experiment', cat: 'Experimental Labs', risk: 'Amber', desc: 'Executes scientific experiment protocols' },
  { name: 'genos_security_coevolution', cat: 'Experimental Labs', risk: 'High', desc: 'Red vs Blue adversarial security simulation' },
  { name: 'genos_bug_investigation', cat: 'Experimental Labs', risk: 'Low', desc: 'Automated root-cause fault localization' },
  { name: 'genos_diagnose', cat: 'Experimental Labs', risk: 'Low', desc: 'Diagnostic health and latency analysis' },
  { name: 'genos_hypothesis_evidence', cat: 'Experimental Labs', risk: 'Low', desc: 'Attaches evidence to causal hypotheses' },
  { name: 'genos_solve', cat: 'Experimental Labs', risk: 'Amber', desc: 'Synthesizes verified algorithmic solutions' },
  { name: 'genos_evaluate_trajectories', cat: 'Experimental Labs', risk: 'Low', desc: 'Evaluates candidate code trajectory scores' },
  // Knowledge & Experience
  { name: 'genos_record_decision', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Persists architectural decision records' },
  { name: 'genos_blame', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Performs semantic blame analysis on faults' },
  { name: 'genos_invalidate_assumption', cat: 'Knowledge & Experience', risk: 'Amber', desc: 'Invalidates stale architectural axioms' },
  { name: 'genos_record_experience', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Encodes episodic memory trajectory' },
  { name: 'genos_search_failures', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Searches historical failure taxonomy' },
  { name: 'genos_cherry_pick_experience', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Transfers learned heuristics across swarms' },
  { name: 'genos_adversarial_review', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Performs CVE and logic vulnerability scan' },
  { name: 'genos_future_ci', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Simulates forward CI impact of changes' },
  { name: 'genos_repository_genome', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Synthesizes structural repository graph' },
  { name: 'genos_bisect_agent', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Binary search agent decisions for regressions' },
  { name: 'genos_analyze_trajectory', cat: 'Knowledge & Experience', risk: 'Low', desc: 'Deep AST inspect of trajectory code' },
  { name: 'genos_compile_memory', cat: 'Knowledge & Experience', risk: 'Amber', desc: 'Distills episodic memory into concise rules' },
  { name: 'genos_strat_compile_memory', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute the compile_memory strategy primitive.' },
  // Resilience & Biomimicry
  { name: 'genos_resilience_apoptosis', cat: 'Resilience & Security', risk: 'High', desc: 'Programmed self-termination of runaway nodes' },
  { name: 'genos_resilience_cryptobiosis', cat: 'Resilience & Security', risk: 'High', desc: 'State freeze and memory hibernation' },
  { name: 'genos_resilience_hypermutation', cat: 'Resilience & Security', risk: 'High', desc: 'Accelerated genetic prompt mutation' },
  { name: 'genos_resilience_circuit_breaker', cat: 'Resilience & Security', risk: 'High', desc: 'Manual trip or reset of tool circuit breaker' },
  { name: 'genos_get_conscience_state', cat: 'Resilience & Security', risk: 'Low', desc: 'Inspects real-time conscience state and dissonance level' },
  { name: 'genos_get_conscience_history', cat: 'Resilience & Security', risk: 'Low', desc: 'Inspects conscience revision history and cognitive transitions' },
  { name: 'genos_get_swarm_entropy', cat: 'Resilience & Security', risk: 'Low', desc: 'Inspects Shannon entropy, drift state, and cyclic deadlocks across the swarm' },
  { name: 'genos_biomimicry_swarm_consensus', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Honeybee dance quorum voting protocol' },
  { name: 'genos_biomimicry_flocking_explore', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Boids flocking exploration algorithm' },
  { name: 'genos_biomimicry_network_quorum', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Mycelial network quorum communication' },
  { name: 'genos_biomimicry_distributed_huddle', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Penguin huddle energy conservation mode' },
  { name: 'genos_biomimicry_stigmergy', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Stigmergic collaboration (pheromone deposit/read)' },
  { name: 'genos_biomimicry_vomeronasal', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Accessory olfactory bulb and subliminal vomeronasal signaling (Flehmen response)' },
  { name: 'genos_biomimicry_electrosensory', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Mormyrocerebellum passive & active electrosensory field distortion analysis' },
  { name: 'genos_biomimicry_cluster_n', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Cluster N quantum magnetoreception and goal vector alignment compass' },
  { name: 'genos_biomimicry_tectum_thermal', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Tectum opticum infrared thermal pit organ and multi-modal synesthetic fusion' },
  { name: 'genos_biomimicry_echolocation', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Hypertrophied echolocation cortex and 3D Doppler ultrasonic topology mapping' },
  { name: 'genos_evolution_assimilate_plasmid', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Horizontal Gene Transfer via plasmid assimilation' },
  { name: 'genos_biomimicry_thalamic_bridge', cat: 'Neurobiology', risk: 'Low', desc: 'Direct zero-copy sensory sharing between craniopagus conjoined twin agents' },
  { name: 'genos_biomimicry_cryptophasia', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Dense inter-twin dialect opcode compression with epistemic chaperone auditing' },

  // Signal transport zero-texte (§45)
  { name: 'genos_signal_publish', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Publie un signal zero-texte (ligand/voltage/pheromone/plasmid/tensor)' },
  { name: 'genos_signal_read', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Lit les signaux zero-texte non-lus pour un agent (topics abonnés)' },
  { name: 'genos_signal_purge', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Nettoie les signaux expirés du bus' },
  { name: 'genos_signal_electrocyte_vote', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Vote par consensus électrocyte + Kuramoto (potentiel de membrane)' },
  { name: 'genos_signal_chemotactic_follow', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Suit le gradient chimiotactique d\'un locus stigmergique' },
  { name: 'genos_signal_plasmid_transfer', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Transfert horizontal de décision binaire via plasmide HGT' },
  { name: 'genos_signal_collective_decision', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Orchestrateur de décision collective multi-topologie (electrocyte/stigmergic/plasmid)' },
  { name: 'genos_biomimicry_mirror_twin_fork', cat: 'Workspace Control', risk: 'Low', desc: 'Symmetric counterfactual fork creating constructive and adversarial twin pairs' },
  { name: 'genos_biomimicry_somatic_resonance', cat: 'Resilience & Security', risk: 'Low', desc: 'Syncytial stress telemetry and collective entropy shockwave propagation' },
  { name: 'genos_biomimicry_chimeric_merge', cat: 'Genetics', risk: 'Low', desc: 'Tetragametic mosaic merge combining tool genome and immune memory' },
  { name: 'genos_biomimicry_polyovulation_spawn', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Multi-zygote heterogeneous dizygotic fleet spawn' },
  { name: 'genos_biomimicry_monozygotic_split', cat: 'Workspace Control', risk: 'Low', desc: 'Early monozygotic cleavage into isogenic MCTS twin clones' },
  { name: 'genos_biomimicry_hybrid_multiples', cat: 'Orchestration', risk: 'Low', desc: 'Hierarchical cluster combining polyovulation and monozygotic cleavage' },
  { name: 'genos_biomimicry_conjoined_twin_bind', cat: 'Resilience & Security', risk: 'Low', desc: 'Deep visceral core binding, shared token pool, and mutual survival lock' },
  { name: 'genos_biomimicry_parasitic_graft', cat: 'Resilience & Security', risk: 'Low', desc: 'Autosite assimilation of arrested twin auxiliary tools as zero-cost limbs' },
  { name: 'genos_biomimicry_fetus_in_fetu', cat: 'Resilience & Security', risk: 'Low', desc: 'Endoparasitic dormant rescue pod encapsulation and emergency resurrection' },
  { name: 'genos_biomimicry_sesquizygotic_split', cat: 'Genetics', risk: 'Low', desc: 'Dispermic fertilization sharing 100% maternal and 50% paternal traits' },
  { name: 'genos_biomimicry_heteropaternal_superfecundation', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Multi-provider half-sibling twin spawn maximizing cognitive diversity' },
  { name: 'genos_biomimicry_superfetation_pipeline', cat: 'Orchestration', risk: 'Low', desc: 'Asynchronous multi-stage gestation with warm knowledge cache inheritance' },
  { name: 'genos_biomimicry_tissue_chimerism', cat: 'Genetics', risk: 'Low', desc: 'Monolithic agent with compartmentalized dual-DNA subsystem lineages' },
  { name: 'genos_biomimicry_obligate_polyembryony', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Mandatory deterministic cleavage into isogenic quadruplets with 75% quorum' },
  { name: 'genos_biomimicry_marmoset_germline_chimerism', cat: 'Genetics', risk: 'Low', desc: 'Cross-twin germline transfer and reproductive procreation by proxy' },
  { name: 'genos_biomimicry_freemartin_endocrine_inhibition', cat: 'Resilience & Security', risk: 'Low', desc: 'Asymmetric endocrine inhibition locking replication and boosting compute' },
  { name: 'genos_biomimicry_embryonic_diapause_pipeline', cat: 'Orchestration', risk: 'Low', desc: '3-Tier sequential pipeline with zero-latency embryonic diapause thawing' },
  // Temporel H38/H39 — noms canoniques + alias doc (désync historique documentée dans handlers/index.js)
  { name: 'genos_temporal_consciousness_transfer', cat: 'Orchestration', risk: 'Low', desc: 'H38 transfert de conscience temporel (alias doc: genos_biomimicry_consciousness_transfer)' },
  { name: 'genos_temporal_novikov_causal_rebase', cat: 'Orchestration', risk: 'Low', desc: 'H39 rebasage causal Novikov (alias doc: genos_biomimicry_novikov_causal_rebase)' },
  { name: 'genos_biomimicry_consciousness_transfer', cat: 'Orchestration', risk: 'Low', desc: 'Alias doc H38 de genos_temporal_consciousness_transfer' },
  { name: 'genos_biomimicry_novikov_causal_rebase', cat: 'Orchestration', risk: 'Low', desc: 'Alias doc H39 de genos_temporal_novikov_causal_rebase' },
  // Auto-generated by Orchestrator CLI
  { name: 'genos_org_specialist_expert_committee', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Specialist Expert Committee organization mode' },
  { name: 'genos_org_blind_adversarial_review', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Blind Adversarial Review organization mode' },
  { name: 'genos_org_red_blue_coevolution', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Red Blue Coevolution organization mode' },
  { name: 'genos_org_brier_weighted_consensus', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Brier Weighted Consensus organization mode' },
  { name: 'genos_org_quorum_with_abstention', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Quorum With Abstention organization mode' },
  { name: 'genos_org_stigmergy', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Stigmergy organization mode' },
  { name: 'genos_org_flocking_boids', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Flocking Boids organization mode' },
  { name: 'genos_org_fish_school_search', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Fish School Search organization mode' },
  { name: 'genos_org_slime_mould_network', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Slime Mould Network organization mode' },
  { name: 'genos_org_grey_wolf_optimizer', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Grey Wolf Optimizer organization mode' },
  { name: 'genos_org_mycelial_routing', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Mycelial Routing organization mode' },
  { name: 'genos_org_dynamic_polyethism', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Dynamic Polyethism organization mode' },
  { name: 'genos_org_energy_huddle', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Energy Huddle organization mode' },
  { name: 'genos_org_network_silence', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Network Silence organization mode' },
  { name: 'genos_org_strategy_arena', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Strategy Arena organization mode' },
  { name: 'genos_org_hierarchical_merge', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Hierarchical Merge organization mode' },
  { name: 'genos_org_competitive_arena', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Competitive Arena organization mode' },
  { name: 'genos_org_isolated_recovery', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Isolated Recovery organization mode' },
  { name: 'genos_org_memory_compilation', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate Memory Compilation organization mode' },
  { name: 'genos_strat_verify', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Verify strategy primitive' },
  { name: 'genos_strat_audit', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Audit strategy primitive' },
  { name: 'genos_strat_minimal_mutation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Minimal Mutation strategy primitive' },
  { name: 'genos_strat_tests', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Tests strategy primitive' },
  { name: 'genos_strat_plan', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Plan strategy primitive' },
  { name: 'genos_strat_independent_verify', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Independent Verify strategy primitive' },
  { name: 'genos_strat_vfs_dry_run', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Vfs Dry Run strategy primitive' },
  { name: 'genos_strat_permission_check', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Permission Check strategy primitive' },
  { name: 'genos_strat_blast_radius', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Blast Radius strategy primitive' },
  { name: 'genos_strat_slm_route', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Slm Route strategy primitive' },
  { name: 'genos_strat_entropy_check', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Entropy Check strategy primitive' },
  { name: 'genos_strat_frontier_escalation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Frontier Escalation strategy primitive' },
  { name: 'genos_strat_provider_route', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Provider Route strategy primitive' },
  { name: 'genos_strat_fallback_chain', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Fallback Chain strategy primitive' },
  { name: 'genos_strat_degraded_mode', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Degraded Mode strategy primitive' },
  { name: 'genos_strat_common_probes', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Common Probes strategy primitive' },
  { name: 'genos_strat_probe', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Probe strategy primitive' },
  { name: 'genos_strat_conditional_mutation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Conditional Mutation strategy primitive' },
  { name: 'genos_strat_belief_update', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Belief Update strategy primitive' },
  { name: 'genos_strat_expected_information_gain', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Expected Information Gain strategy primitive' },
  { name: 'genos_strat_next_probe', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Next Probe strategy primitive' },
  { name: 'genos_strat_snapshot_test', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Snapshot Test strategy primitive' },
  { name: 'genos_strat_safe_revert', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Safe Revert strategy primitive' },
  { name: 'genos_strat_impact_graph', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Impact Graph strategy primitive' },
  { name: 'genos_strat_provenance', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Provenance strategy primitive' },
  { name: 'genos_strat_isolated_run', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Isolated Run strategy primitive' },
  { name: 'genos_strat_single_mutation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Single Mutation strategy primitive' },
  { name: 'genos_strat_paired_evaluation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Paired Evaluation strategy primitive' },
  { name: 'genos_strat_heredity_experiment', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Heredity Experiment strategy primitive' },
  { name: 'genos_strat_variance_analysis', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Variance Analysis strategy primitive' },
  { name: 'genos_strat_select_winner', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Select Winner strategy primitive' },
  { name: 'genos_strat_preserve_losers', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Preserve Losers strategy primitive' },
  { name: 'genos_strat_multi_objective_evaluation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Multi Objective Evaluation strategy primitive' },
  { name: 'genos_strat_pareto_select', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Pareto Select strategy primitive' },
  { name: 'genos_strat_pareto_frontier', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Pareto Frontier strategy primitive' },
  { name: 'genos_strat_utopia_distance', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Utopia Distance strategy primitive' },
  { name: 'genos_strat_minimum_evaluation', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Minimum Evaluation strategy primitive' },
  { name: 'genos_strat_prune', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Prune strategy primitive' },
  { name: 'genos_strat_reallocate', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Reallocate strategy primitive' },
  { name: 'genos_strat_branch_evolution', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Branch Evolution strategy primitive' },
  { name: 'genos_strat_recursive_fork', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Recursive Fork strategy primitive' },
  { name: 'genos_strat_rank_states', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Rank States strategy primitive' },
  { name: 'genos_strat_retain_top_k', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Retain Top K strategy primitive' },
  { name: 'genos_strat_expand', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Expand strategy primitive' },
  { name: 'genos_strat_mcts_select', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute Mcts Select strategy primitive' },
  { name: 'genos_browser_act', cat: 'Web & Interaction', risk: 'Low', desc: 'Interactive semantic web browser navigation and download ingestion' },
  // Option A — Affordances, test matériel, plug & play, ganglia basaux, batteries externes
  { name: 'genos_biomimicry_affordances_scanner', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Detecte les affordances d\'un objet: ce qu\'il permet de faire, pas ce qu\'il est (cortex parietal)' },
  { name: 'genos_biomimicry_tool_health_probe', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Boucle somatosensorielle : verifie etat, usure et viabilite d\'un outil avant usage (corbeau caledonien)' },
  { name: 'genos_biomimicry_extended_body_schema', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Redefinition du schema corporel : l\'outil integre s\'etend jusqu\'au bout du bras (plasticite corporelle)' },
  { name: 'genos_biomimicry_ganglia_basals', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Calcul dopamine/coût-benefit : selection optimisée des options (ganglia basaux, noyaux gris centraux)' },
  { name: 'genos_biomimicry_external_charge', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Detection de batteries environnementales : lézard ectotherme, soleil comme chargeur externe, signal d\'inconfort' },
  { name: 'genos_biomimicry_axolotl_regeneration', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Regenration fonctionnelle axolotl : reconstruction topologie differente mais fonctionnellement equivalente apres defaillance structurelle (Ambystoma mexicanum)' },
  { name: 'genos_biomimicry_axolotl_topology_mode', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Mode plastique axolotl : topologie non-figee, reconfiguration toujours possible (state larvaire, neotenie) vs mode stabilise' },
  { name: 'genos_biomimicry_axolotl_neotenic_state', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Orientation strategique etatique larval : systeme reste immature pour garder sa capacite de transformation radicale' },
  { name: 'genos_genome_mutate', cat: 'Orchestration', risk: 'Amber', desc: 'Mutate an AgentDNA genome (stochastic, hypermutation or targeted locus).' },
  { name: 'genos_genome_clone', cat: 'Orchestration', risk: 'Amber', desc: 'Clone an AgentDNA genome (mitosis, binary fission or budding).' },
  { name: 'genos_genome_decoy', cat: 'Orchestration', risk: 'Amber', desc: 'Produce a marked decoy AgentDNA genome with a plausible phenotype.' }
];

async function seedMcpTools(db) {
  for (const t of MCP_TOOLS_LIST) {
    await db.run(
      `INSERT OR IGNORE INTO mcp_tools (id, name, provider, category, risk_level, description, actions_json, is_locked, circuit_state) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      t.name, t.name, 'genos', t.cat, t.risk, t.desc, JSON.stringify([t.name]), 0, 'CLOSED'
    );
  }
}

module.exports = { seedMcpTools, MCP_TOOLS_LIST };
