const crypto = require('crypto');
const { getDatabase } = require('../db');
const { scopeSql } = require('../middleware/tenant');
const parse = (value, fallback) => { try { return JSON.parse(value); } catch (_) { return fallback; } };
const KNOWN_GRADERS = new Set(['exact_match', 'groundedness', 'safety', 'llm_judge']);

async function listDatasets(req, res, next) { try { const db = await getDatabase(); const scope = scopeSql(req); const rows = await db.all(`SELECT * FROM datasets WHERE ${scope.clause} ORDER BY updated_at DESC`, ...scope.params); res.json(rows.map((row) => ({ ...row, metadata: parse(row.metadata_json, {}) }))); } catch (error) { next(error); } }
async function createDataset(req, res, next) { try { const db = await getDatabase(); const { name, description = '' } = req.body || {}; if (!String(name || '').trim()) return res.status(400).json({ error: { code: 'INVALID_NAME', message: 'Dataset name is required.' } }); const id = `ds-${crypto.randomUUID()}`; const scope = scopeSql(req); await db.run('INSERT INTO datasets(id,name,description,organization_id,project_id) VALUES(?,?,?,?,?)', id, String(name).trim(), description, ...scope.params); res.status(201).json(await db.get('SELECT * FROM datasets WHERE id=?', id)); } catch (error) { next(error); } }
async function addCase(req, res, next) { try { const db = await getDatabase(); const scope = scopeSql(req); const dataset = await db.get(`SELECT id FROM datasets WHERE id=? AND ${scope.clause}`, req.params.id, ...scope.params); if (!dataset) return res.status(404).json({ error: { code: 'DATASET_NOT_FOUND', message: 'Dataset not found.' } }); const id = `case-${crypto.randomUUID()}`; const { input = {}, expected = null, labels = [] } = req.body || {}; if (!Array.isArray(labels)) return res.status(400).json({ error: { code: 'INVALID_LABELS', message: 'labels must be an array.' } }); await db.run('INSERT INTO dataset_cases(id,dataset_id,input_json,expected_json,labels_json) VALUES(?,?,?,?,?)', id, req.params.id, JSON.stringify(input), JSON.stringify(expected), JSON.stringify(labels)); res.status(201).json({ id, datasetId: req.params.id, input, expected, labels }); } catch (error) { next(error); } }
async function listCases(req, res, next) { try { const db = await getDatabase(); const scope = scopeSql(req); const rows = await db.all('SELECT c.* FROM dataset_cases c JOIN datasets d ON d.id=c.dataset_id WHERE c.dataset_id=? AND d.organization_id=? AND d.project_id=? ORDER BY c.created_at', req.params.id, ...scope.params); res.json(rows.map((row) => ({ ...row, input: parse(row.input_json, {}), expected: parse(row.expected_json, null), labels: parse(row.labels_json, []) }))); } catch (error) { next(error); } }
async function createJob(req, res, next) { try { const db = await getDatabase(); const scope = scopeSql(req); const datasetId = String(req.body?.datasetId || '').trim(); if (!datasetId) return res.status(400).json({ error: { code: 'DATASET_REQUIRED', message: 'datasetId is required.' } }); const dataset = await db.get(`SELECT id FROM datasets WHERE id=? AND ${scope.clause}`, datasetId, ...scope.params); if (!dataset) return res.status(404).json({ error: { code: 'DATASET_NOT_FOUND', message: 'Dataset not found.' } }); const cases = await db.get('SELECT COUNT(*) AS count FROM dataset_cases WHERE dataset_id=?', datasetId); if (!cases?.count) return res.status(409).json({ error: { code: 'EMPTY_DATASET', message: 'Add at least one case before creating an evaluation job.' } }); const config = req.body?.config || {}; const graders = config.graders || ['exact_match']; if (!Array.isArray(graders) || graders.length === 0 || graders.some((grader) => !KNOWN_GRADERS.has(grader))) return res.status(400).json({ error: { code: 'INVALID_GRADERS', message: 'Unsupported evaluation grader.' } }); const requested = Number(req.body?.maxAttempts ?? 3); const maxAttempts = Number.isFinite(requested) ? Math.max(1, Math.min(Math.floor(requested), 10)) : 3; const id = `eval-${crypto.randomUUID()}`; await db.run('INSERT INTO evaluation_jobs(id,dataset_id,status,config_json,max_attempts,organization_id,project_id) VALUES(?,?,?,?,?,?,?)', id, datasetId, 'queued', JSON.stringify(config), maxAttempts, ...scope.params); res.status(202).json({ id, status: 'queued', maxAttempts }); } catch (error) { next(error); } }
async function listJobs(req, res, next) { try { const db = await getDatabase(); const scope = scopeSql(req, 'j'); res.json(await db.all(`SELECT j.* FROM evaluation_jobs j WHERE ${scope.clause} ORDER BY j.created_at DESC`, ...scope.params)); } catch (error) { next(error); } }
module.exports = { listDatasets, createDataset, addCase, listCases, createJob, listJobs };
