const crypto = require('crypto');
const frameworkAdapters = require('../services/frameworkAdapters');
const { getDatabase } = require('../db');
const parse = (v, fallback) => { try { return JSON.parse(v); } catch (_) { return fallback; } };
const map = (span) => span && ({ ...span, inputs: parse(span.inputs_json, {}), outputs: parse(span.outputs_json, {}) });

async function listTraces(req, res, next) { try { const db = await getDatabase(); const limit = Math.min(Number(req.query.limit) || 50, 200); const rows = await db.all('SELECT trace_id, COUNT(*) AS span_count, MIN(start_time) AS start_time, MAX(COALESCE(end_time, start_time)) AS end_time, SUM(CASE WHEN error IS NOT NULL THEN 1 ELSE 0 END) AS error_count FROM trace_spans GROUP BY trace_id ORDER BY start_time DESC LIMIT ?', limit); res.json(rows.map((r) => ({ ...r, duration_ms: Math.max(0, r.end_time - r.start_time) }))); } catch (e) { next(e); } }
async function getTrace(req, res, next) { try { const db = await getDatabase(); const spans = await db.all('SELECT * FROM trace_spans WHERE trace_id = ? ORDER BY start_time ASC', req.params.traceId); if (!spans.length) return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Trace not found.' } }); res.json({ traceId: req.params.traceId, spans: spans.map(map) }); } catch (e) { next(e); } }
async function ingestSpan(req, res, next) { try { const db = await getDatabase(); const raw = req.body || {}; const body = raw.framework ? frameworkAdapters.normalize(raw.framework, raw) : raw; const id = body.spanId || body.id || `span-${crypto.randomUUID()}`; const traceId = body.traceId || body.trace_id || `trace-${crypto.randomUUID()}`; await db.run('INSERT OR REPLACE INTO trace_spans (id, trace_id, agent_id, parent_span_id, name, start_time, end_time, inputs_json, outputs_json, error) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', id, traceId, body.agentId || body.agent_id || 'unknown', body.parentSpanId || body.parent_span_id || null, body.name || 'span', Number(body.startTime || body.start_time || Date.now()), body.endTime || body.end_time ? Number(body.endTime || body.end_time) : null, JSON.stringify(body.inputs || body.attributes || {}), JSON.stringify(body.outputs || {}), body.error || null); res.status(201).json({ id, traceId, framework: body.framework || null }); } catch (e) { next(e); } }
async function replayTrace(req, res, next) { try { const db = await getDatabase(); const spans = await db.all('SELECT * FROM trace_spans WHERE trace_id = ? ORDER BY start_time ASC', req.params.traceId); if (!spans.length) return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Trace not found.' } }); return res.status(501).json({ error: { code: 'TRACE_REPLAY_UNAVAILABLE', message: 'Trace replay requires a deterministic replay worker and is not available yet.' }, traceId: req.params.traceId, spanCount: spans.length }); } catch (e) { next(e); } }
module.exports = { listTraces, getTrace, ingestSpan, replayTrace };
