'use strict';

const SESSION_PHASES = Object.freeze([
  'CONSTITUTION', 'FORMATION', 'SEALED_JUDGMENT', 'COMMITTED', 'REVIEW',
  'DELIBERATION', 'REVISION', 'AGGREGATION', 'DECIDED', 'ESCALATED'
]);

const SESSION_STATUSES = Object.freeze(['ACTIVE', 'DECIDED', 'ESCALATED', 'CLOSED']);

const COMMUNITY_EVENTS = Object.freeze([
  'COMMUNITY_CREATED', 'CONSTITUTION_COMMITTED', 'MEMBER_RECRUITED',
  'JUDGMENT_COMMITTED', 'CLAIM_PUBLISHED', 'ARGUMENT_ADDED', 'EVIDENCE_ADDED',
  'OBJECTION_ADDED', 'BELIEF_REVISED', 'ABSTAINED', 'DISSENT_ESCALATED',
  'CONSENSUS_REACHED', 'PLURALISM_RETAINED', 'EXPERIMENT_ESCALATED',
  'PHASE_CHANGED', 'STATUS_CHANGED', 'CONSTITUTION_VERSIONED', 'JUDGMENTS_REVEALED',
  'DISSENT_RECORDED', 'DISSENT_STATUS_CHANGED', 'CALIBRATION_RECORDED', 'COMMUNITY_JUDGMENT_RECORDED',
  'MEMBER_QUARANTINED', 'MEMBER_REINSTATED'
]);

module.exports = { SESSION_PHASES, SESSION_STATUSES, COMMUNITY_EVENTS };
