const crypto=require('crypto');const express=require('express');const router=express.Router();const {getDatabase}=require('../db');const {requirePermission,resolveUserFromHeaders}=require('../middleware/auth');const {requireTenantScope}=require('../middleware/tenant');const jobWorker=require('../services/jobWorker');
const fs=require('fs');const path=require('path');const runtimeAdapter=require('../services/agentRuntimeAdapter');const {isPathWithinRoot,resolveWorkspacesRoot}=require('../services/workspaceRegistry');
async function organizationAdmin(db,user,organizationId){if(user.permissions?.includes('all'))return true;return Boolean(await db.get("SELECT role FROM organization_memberships WHERE principal_id=? AND organization_id=? AND role IN ('owner','admin')",user.keyId||user.username,organizationId));}

async function deleteProjectResources(db, project) {
	const workspaces = await db.all('SELECT id, path FROM workspaces WHERE organization_id=? AND project_id=?', project.organization_id, project.id);
	const workspaceIds = workspaces.map((workspace) => workspace.id);
	const agents = workspaceIds.length ? await db.all(`SELECT id FROM agents WHERE workspace_id IN (${workspaceIds.map(() => '?').join(',')})`, ...workspaceIds) : [];
	for (const agent of agents) runtimeAdapter.stopMission(agent.id);

	const tables = await db.all("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'");
	for (const table of tables) {
		const columns = await db.all(`PRAGMA table_info(${JSON.stringify(table.name)})`);
		if (columns.some((column) => column.name === 'project_id') && table.name !== 'projects') {
			await db.run(`DELETE FROM "${table.name.replace(/"/g, '""')}" WHERE project_id=?`, project.id);
		}
	}
	if (workspaceIds.length) {
		const placeholders = workspaceIds.map(() => '?').join(',');
		await db.run(`DELETE FROM agents WHERE workspace_id IN (${placeholders})`, ...workspaceIds);
		await db.run(`DELETE FROM cryptobiosis_snapshots WHERE workspace_id IN (${placeholders})`, ...workspaceIds);
		await db.run(`DELETE FROM workspaces WHERE id IN (${placeholders})`, ...workspaceIds);
	}
	await db.run('DELETE FROM projects WHERE id=?', project.id);

	const root = resolveWorkspacesRoot();
	const skippedPaths = [];
	for (const workspace of workspaces) {
		const workspacePath = path.resolve(workspace.path);
		if (!isPathWithinRoot(root, workspacePath)) { skippedPaths.push(workspace.path); continue; }
		fs.rmSync(workspacePath, { recursive: true, force: true });
	}
	return { workspaceCount: workspaces.length, stoppedAgentCount: agents.length, skippedPaths };
}
router.get('/organizations',async(req,res,next)=>{try{const user=await resolveUserFromHeaders(req.headers);const db=await getDatabase();if(user.permissions.includes('all'))return res.json(await db.all('SELECT * FROM organizations ORDER BY created_at DESC'));res.json(await db.all('SELECT o.* FROM organizations o JOIN organization_memberships om ON om.organization_id=o.id WHERE om.principal_id=? ORDER BY o.created_at DESC',user.keyId||user.username));}catch(e){next(e);}});
router.post('/organizations',requirePermission('workspace:write'),async(req,res,next)=>{try{const user=await resolveUserFromHeaders(req.headers);const name=String(req.body?.name||'').trim();if(!name)return res.status(400).json({error:{code:'INVALID_ORGANIZATION',message:'name is required'}});const db=await getDatabase();const id=`org-${crypto.randomUUID()}`;await db.run('INSERT INTO organizations(id,name) VALUES(?,?)',id,name);await db.run('INSERT INTO organization_memberships(principal_id,organization_id,role) VALUES(?,?,?)',user.keyId||user.username,id,'owner');await db.run('INSERT INTO audit_logs (actor,action,resource,decision,reason,payload_json) VALUES (?,?,?,?,?,?)',user.keyId||user.username,'ORGANIZATION_CREATE',id,'allowed','Organization created',JSON.stringify({name,owner:user.keyId||user.username}));res.status(201).json(await db.get('SELECT * FROM organizations WHERE id=?',id));}catch(e){next(e);}});
router.get('/projects',async(req,res,next)=>{try{const user=await resolveUserFromHeaders(req.headers);const organizationId=String(req.headers['x-organization-id']||'').trim();if(!organizationId)return res.status(400).json({error:{code:'ORGANIZATION_REQUIRED',message:'X-Organization-Id is required to list projects.'}});const db=await getDatabase();if(user.permissions?.includes('all'))return res.json(await db.all('SELECT * FROM projects WHERE organization_id=? ORDER BY name',organizationId));const principal=user.keyId||user.username;res.json(await db.all("SELECT DISTINCT p.* FROM projects p LEFT JOIN organization_memberships om ON om.organization_id=p.organization_id AND om.principal_id=? LEFT JOIN project_memberships pm ON pm.project_id=p.id AND pm.principal_id=? WHERE p.organization_id = ? AND (om.role IN ('owner','admin') OR pm.principal_id IS NOT NULL) ORDER BY p.name",principal,principal,organizationId));}catch(e){next(e);}});
router.get('/organizations/:id/members',requirePermission('read'),async(req,res,next)=>{try{const user=await resolveUserFromHeaders(req.headers);const db=await getDatabase();const principal=user.keyId||user.username;const member=await db.get('SELECT role FROM organization_memberships WHERE organization_id=? AND principal_id=?',req.params.id,principal);if(!member&&!user.permissions.includes('all'))return res.status(403).json({error:{code:'ORGANIZATION_MEMBERSHIP_REQUIRED',message:'Organization membership is required'}});res.json(await db.all('SELECT principal_id, organization_id, role, created_at FROM organization_memberships WHERE organization_id=? ORDER BY created_at, principal_id',req.params.id));}catch(e){next(e);}});
router.post('/organizations/:id/members',requirePermission('workspace:write'),async(req,res,next)=>{try{const user=await resolveUserFromHeaders(req.headers);const db=await getDatabase();const actor=user.keyId||user.username;const admin=await db.get("SELECT role FROM organization_memberships WHERE organization_id=? AND principal_id=? AND role IN ('owner','admin')",req.params.id,actor);if(!admin&&!user.permissions.includes('all'))return res.status(403).json({error:{code:'ORGANIZATION_ADMIN_REQUIRED',message:'Organization admin membership is required'}});const principalId=String(req.body?.principalId||'').trim();const role=String(req.body?.role||'viewer').trim();if(!principalId||!new Set(['owner','admin','member','viewer']).has(role))return res.status(400).json({error:{code:'INVALID_MEMBER',message:'principalId and a valid organization role are required'}});const principal=await db.get('SELECT id FROM access_keys WHERE id=? UNION SELECT username AS id FROM users WHERE username=?',principalId,principalId);if(!principal&&!user.permissions.includes('all'))return res.status(400).json({error:{code:'UNKNOWN_PRINCIPAL',message:'principalId does not identify a known principal'}});await db.run('INSERT INTO organization_memberships(principal_id,organization_id,role) VALUES(?,?,?) ON CONFLICT(principal_id,organization_id) DO UPDATE SET role=excluded.role',principalId,req.params.id,role);await db.run('INSERT INTO audit_logs (actor,action,resource,decision,reason,payload_json) VALUES (?,?,?,?,?,?)',actor,'ORGANIZATION_MEMBER_UPSERT',req.params.id,'allowed','Organization membership changed',JSON.stringify({principalId,role}));res.status(201).json(await db.get('SELECT principal_id, organization_id, role, created_at FROM organization_memberships WHERE principal_id=? AND organization_id=?',principalId,req.params.id));}catch(e){next(e);}});
router.delete('/organizations/:id/members/:principalId',requirePermission('workspace:write'),async(req,res,next)=>{try{const user=await resolveUserFromHeaders(req.headers);const db=await getDatabase();const actor=user.keyId||user.username;const admin=await db.get("SELECT role FROM organization_memberships WHERE organization_id=? AND principal_id=? AND role IN ('owner','admin')",req.params.id,actor);if(!admin&&!user.permissions.includes('all'))return res.status(403).json({error:{code:'ORGANIZATION_ADMIN_REQUIRED',message:'Organization admin membership is required'}});const target=await db.get('SELECT role FROM organization_memberships WHERE organization_id=? AND principal_id=?',req.params.id,req.params.principalId);if(!target)return res.status(404).json({error:{code:'MEMBER_NOT_FOUND',message:'Organization member not found'}});if(['owner','admin'].includes(target.role)){const remaining=await db.get("SELECT COUNT(*) AS count FROM organization_memberships WHERE organization_id=? AND role IN ('owner','admin') AND principal_id<>?",req.params.id,req.params.principalId);if(Number(remaining?.count||0)<1)return res.status(409).json({error:{code:'LAST_ORGANIZATION_ADMIN',message:'The last organization administrator cannot be removed'}});}await db.run('DELETE FROM organization_memberships WHERE organization_id=? AND principal_id=?',req.params.id,req.params.principalId);await db.run('INSERT INTO audit_logs (actor,action,resource,decision,reason,payload_json) VALUES (?,?,?,?,?,?)',actor,'ORGANIZATION_MEMBER_DELETE',req.params.id,'allowed','Organization membership removed',JSON.stringify({principalId:req.params.principalId}));res.json({success:true});}catch(e){next(e);}});
router.post('/projects',requirePermission('workspace:write'),async(req,res,next)=>{try{const user=await resolveUserFromHeaders(req.headers);const db=await getDatabase();const organizationId=String(req.body?.organizationId||'').trim();const name=String(req.body?.name||'').trim();if(!organizationId||!name)return res.status(400).json({error:{code:'INVALID_PROJECT',message:'organizationId and name are required'}});if(!await db.get('SELECT id FROM organizations WHERE id=?',organizationId))return res.status(404).json({error:{code:'ORGANIZATION_NOT_FOUND',message:'Organization not found'}});const membership=await db.get("SELECT role FROM organization_memberships WHERE principal_id = ? AND organization_id = ? AND role IN ('owner','admin')",user.keyId||user.username,organizationId);if(!membership&&!user.permissions.includes('all'))return res.status(403).json({error:{code:'ORGANIZATION_ADMIN_REQUIRED',message:'Organization admin membership is required'}});if(await db.get('SELECT id FROM projects WHERE organization_id=? AND name=?',organizationId,name))return res.status(409).json({error:{code:'PROJECT_EXISTS',message:'A project with this name already exists in the organization'}});const id=`project-${crypto.randomUUID()}`;await db.run('INSERT INTO projects(id,organization_id,name,status) VALUES(?,?,?,?)',id,organizationId,name,'active');res.status(201).json(await db.get('SELECT * FROM projects WHERE id=?',id));}catch(e){next(e);}});
router.post('/projects/:id/members',requirePermission('workspace:write'),async(req,res,next)=>{try{const user=await resolveUserFromHeaders(req.headers);const db=await getDatabase();const project=await db.get('SELECT organization_id FROM projects WHERE id=?',req.params.id);if(!project)return res.status(404).json({error:{code:'PROJECT_NOT_FOUND',message:'Project not found'}});const admin=await db.get("SELECT role FROM organization_memberships WHERE principal_id=? AND organization_id=? AND role IN ('owner','admin')",user.keyId||user.username,project.organization_id);if(!admin&&!user.permissions.includes('all'))return res.status(403).json({error:{code:'ORGANIZATION_ADMIN_REQUIRED',message:'Organization admin membership is required'}});const principalId=String(req.body?.principalId||'').trim();const role=String(req.body?.role||'viewer').trim();const allowedRoles=new Set(['viewer','member','admin']);if(!principalId||!allowedRoles.has(role))return res.status(400).json({error:{code:'INVALID_MEMBER',message:'principalId and a valid role (viewer, member, admin) are required'}});const principal=await db.get('SELECT id FROM access_keys WHERE id=? UNION SELECT username AS id FROM users WHERE username=?',principalId,principalId);if(!principal&&!user.permissions.includes('all'))return res.status(400).json({error:{code:'UNKNOWN_PRINCIPAL',message:'principalId does not identify a known principal'}});await db.run('INSERT INTO project_memberships(principal_id,project_id,role) VALUES(?,?,?) ON CONFLICT(principal_id,project_id) DO UPDATE SET role=excluded.role',principalId,req.params.id,role);res.status(201).json(await db.get('SELECT * FROM project_memberships WHERE principal_id=? AND project_id=?',principalId,req.params.id));}catch(e){next(e);}});
router.patch('/projects/:id',requirePermission('workspace:write'),async(req,res,next)=>{try{const user=await resolveUserFromHeaders(req.headers);const db=await getDatabase();const project=await db.get('SELECT * FROM projects WHERE id=?',req.params.id);if(!project)return res.status(404).json({error:{code:'PROJECT_NOT_FOUND',message:'Project not found'}});const admin=await db.get("SELECT role FROM organization_memberships WHERE principal_id=? AND organization_id=? AND role IN ('owner','admin')",user.keyId||user.username,project.organization_id);if(!admin&&!user.permissions.includes('all'))return res.status(403).json({error:{code:'ORGANIZATION_ADMIN_REQUIRED',message:'Organization admin membership is required'}});const name=String(req.body?.name||project.name).trim();const status=String(req.body?.status||project.status||'active').trim();if(!name||!['active','archived'].includes(status))return res.status(400).json({error:{code:'INVALID_PROJECT',message:'name and status must be valid'}});const duplicate=await db.get('SELECT id FROM projects WHERE organization_id=? AND name=? AND id<>?',project.organization_id,name,req.params.id);if(duplicate)return res.status(409).json({error:{code:'PROJECT_EXISTS',message:'A project with this name already exists in the organization'}});await db.run('UPDATE projects SET name=?, status=? WHERE id=?',name,status,req.params.id);await db.run('UPDATE workspaces SET is_archived=?, updated_at=CURRENT_TIMESTAMP WHERE organization_id=? AND project_id=?',status==='archived'?1:0,project.organization_id,req.params.id);res.json(await db.get('SELECT * FROM projects WHERE id=?',req.params.id));}catch(e){next(e);}});
router.delete('/projects/:id/members/:principalId',requirePermission('workspace:write'),async(req,res,next)=>{try{const user=await resolveUserFromHeaders(req.headers);const db=await getDatabase();const project=await db.get('SELECT organization_id FROM projects WHERE id=?',req.params.id);if(!project)return res.status(404).json({error:{code:'PROJECT_NOT_FOUND',message:'Project not found'}});const admin=await db.get("SELECT role FROM organization_memberships WHERE principal_id=? AND organization_id=? AND role IN ('owner','admin')",user.keyId||user.username,project.organization_id);if(!admin&&!user.permissions.includes('all'))return res.status(403).json({error:{code:'ORGANIZATION_ADMIN_REQUIRED',message:'Organization admin membership is required'}});const target=await db.get('SELECT role FROM project_memberships WHERE project_id=? AND principal_id=?',req.params.id,req.params.principalId);if(!target)return res.status(404).json({error:{code:'MEMBER_NOT_FOUND',message:'Project member not found'}});if(target.role==='admin'){const remaining=await db.get("SELECT COUNT(*) AS count FROM project_memberships WHERE project_id=? AND role='admin' AND principal_id<>?",req.params.id,req.params.principalId);if(Number(remaining?.count||0)<1)return res.status(409).json({error:{code:'LAST_PROJECT_ADMIN',message:'The last project administrator cannot be removed'}});}const result=await db.run('DELETE FROM project_memberships WHERE project_id=? AND principal_id=?',req.params.id,req.params.principalId);if (!result.changes) return res.status(404).json({error:{code:'MEMBER_NOT_FOUND',message:'Project member not found'}});res.json({success:true});}catch(e){next(e);}});
router.delete('/projects/:id',requirePermission('workspace:delete'),async(req,res,next)=>{try{const user=await resolveUserFromHeaders(req.headers);const db=await getDatabase();const project=await db.get('SELECT * FROM projects WHERE id=?',req.params.id);if(!project)return res.status(404).json({error:{code:'PROJECT_NOT_FOUND',message:'Project not found'}});if(!await organizationAdmin(db,user,project.organization_id))return res.status(403).json({error:{code:'ORGANIZATION_ADMIN_REQUIRED',message:'Organization admin membership is required'}});const cleanup=await deleteProjectResources(db,project);res.json({success:true,projectId:project.id,...cleanup});}catch(e){next(e);}});
router.post('/projects/:id/restore',requirePermission('workspace:write'),async(req,res,next)=>{try{const user=await resolveUserFromHeaders(req.headers);const db=await getDatabase();const project=await db.get('SELECT * FROM projects WHERE id=?',req.params.id);if(!project)return res.status(404).json({error:{code:'PROJECT_NOT_FOUND',message:'Project not found'}});const admin=await db.get("SELECT role FROM organization_memberships WHERE principal_id=? AND organization_id=? AND role IN ('owner','admin')",user.keyId||user.username,project.organization_id);if(!admin&&!user.permissions.includes('all'))return res.status(403).json({error:{code:'ORGANIZATION_ADMIN_REQUIRED',message:'Organization admin membership is required'}});await db.run("UPDATE projects SET status='active' WHERE id=?",req.params.id);await db.run('UPDATE workspaces SET is_archived=0, updated_at=CURRENT_TIMESTAMP WHERE organization_id=? AND project_id=?',project.organization_id,req.params.id);res.json(await db.get('SELECT * FROM projects WHERE id=?',req.params.id));}catch(e){next(e);}});
router.get('/environments',requireTenantScope(),async(req,res,next)=>{try{const db=await getDatabase();res.json(await db.all('SELECT * FROM environments WHERE organization_id = ? ORDER BY name',req.tenant.organizationId));}catch(e){next(e);}});
router.get('/workers',async(req,res,next)=>{try{const db=await getDatabase();const workflow=await db.get("SELECT COUNT(*) AS count FROM workflow_runs WHERE status IN ('queued','running')");const evals=await db.get("SELECT COUNT(*) AS count FROM evaluation_jobs WHERE status IN ('queued','running')");const models=await db.get("SELECT COUNT(*) AS count FROM model_jobs WHERE status IN ('queued','running')");const retryRows=await Promise.all([db.get("SELECT COALESCE(SUM(CASE WHEN attempts > 1 THEN attempts - 1 ELSE 0 END), 0) AS count FROM evaluation_jobs WHERE status IN ('queued','running')"),db.get("SELECT COALESCE(SUM(CASE WHEN attempts > 1 THEN attempts - 1 ELSE 0 END), 0) AS count FROM model_jobs WHERE status IN ('queued','running')")]);const runtime=jobWorker.getWorkerStatus();res.json({status:runtime.running?'healthy':'offline',workers:runtime.running?1:0,active:runtime.busy?1:0,queueDepth:(workflow?.count||0)+(evals?.count||0)+(models?.count||0),retries:retryRows.reduce((total,row)=>total+(row?.count||0),0),blocked:0,processId:runtime.processId,timestamp:new Date().toISOString()});}catch(e){next(e);}});
module.exports=router;
