const express=require('express');const router=express.Router();const {getDatabase}=require('../db');const {requirePermission,resolveUserFromHeaders}=require('../middleware/auth');const {requireTenantScope}=require('../middleware/tenant');const jobWorker=require('../services/jobWorker');
router.get('/organizations',async(req,res,next)=>{try{const db=await getDatabase();res.json(await db.all('SELECT * FROM organizations ORDER BY created_at DESC'));}catch(e){next(e);}});
router.post('/organizations',requirePermission('workspace:write'),async(req,res,next)=>{try{const db=await getDatabase();const id=`org-${Date.now()}`;await db.run('INSERT INTO organizations(id,name) VALUES(?,?)',id,req.body?.name||'Default Organization');res.status(201).json(await db.get('SELECT * FROM organizations WHERE id=?',id));}catch(e){next(e);}});
router.get('/projects',requireTenantScope(),async(req,res,next)=>{try{const db=await getDatabase();res.json(await db.all('SELECT * FROM projects WHERE organization_id = ? ORDER BY name',req.tenant.organizationId));}catch(e){next(e);}});
router.post('/projects',requirePermission('workspace:write'),async(req,res,next)=>{try{const user=await resolveUserFromHeaders(req.headers);const db=await getDatabase();const organizationId=String(req.body?.organizationId||'').trim();const name=String(req.body?.name||'').trim();if(!organizationId||!name)return res.status(400).json({error:{code:'INVALID_PROJECT',message:'organizationId and name are required'}});const membership=await db.get("SELECT role FROM organization_memberships WHERE principal_id = ? AND organization_id = ? AND role IN ('owner','admin')",user.keyId||user.username,organizationId);if(!membership&&!user.permissions.includes('all'))return res.status(403).json({error:{code:'ORGANIZATION_ADMIN_REQUIRED',message:'Organization admin membership is required'}});const id=`project-${Date.now()}`;await db.run('INSERT INTO projects(id,organization_id,name) VALUES(?,?,?)',id,organizationId,name);res.status(201).json(await db.get('SELECT * FROM projects WHERE id=?',id));}catch(e){next(e);}});
router.post('/projects/:id/members',requirePermission('workspace:write'),async(req,res,next)=>{try{const user=await resolveUserFromHeaders(req.headers);const db=await getDatabase();const project=await db.get('SELECT organization_id FROM projects WHERE id=?',req.params.id);if(!project)return res.status(404).json({error:{code:'PROJECT_NOT_FOUND',message:'Project not found'}});const admin=await db.get("SELECT role FROM organization_memberships WHERE principal_id=? AND organization_id=? AND role IN ('owner','admin')",user.keyId||user.username,project.organization_id);if(!admin&&!user.permissions.includes('all'))return res.status(403).json({error:{code:'ORGANIZATION_ADMIN_REQUIRED',message:'Organization admin membership is required'}});const principalId=String(req.body?.principalId||'').trim();const role=String(req.body?.role||'viewer').trim();if(!principalId)return res.status(400).json({error:{code:'INVALID_MEMBER',message:'principalId is required'}});await db.run('INSERT INTO project_memberships(principal_id,project_id,role) VALUES(?,?,?) ON CONFLICT(principal_id,project_id) DO UPDATE SET role=excluded.role',principalId,req.params.id,role);res.status(201).json(await db.get('SELECT * FROM project_memberships WHERE principal_id=? AND project_id=?',principalId,req.params.id));}catch(e){next(e);}});
router.get('/environments',async(req,res,next)=>{try{const db=await getDatabase();res.json(await db.all('SELECT * FROM environments ORDER BY name'));}catch(e){next(e);}});
router.get('/workers',async(req,res,next)=>{try{const db=await getDatabase();const workflow=await db.get("SELECT COUNT(*) AS count FROM workflow_runs WHERE status IN ('queued','running')");const evals=await db.get("SELECT COUNT(*) AS count FROM evaluation_jobs WHERE status IN ('queued','running')");const models=await db.get("SELECT COUNT(*) AS count FROM model_jobs WHERE status IN ('queued','running')");const retryRows=await Promise.all([db.get("SELECT COALESCE(SUM(CASE WHEN attempts > 1 THEN attempts - 1 ELSE 0 END), 0) AS count FROM evaluation_jobs WHERE status IN ('queued','running')"),db.get("SELECT COALESCE(SUM(CASE WHEN attempts > 1 THEN attempts - 1 ELSE 0 END), 0) AS count FROM model_jobs WHERE status IN ('queued','running')")]);const runtime=jobWorker.getWorkerStatus();res.json({status:runtime.running?'healthy':'offline',workers:runtime.running?1:0,active:runtime.busy?1:0,queueDepth:(workflow?.count||0)+(evals?.count||0)+(models?.count||0),retries:retryRows.reduce((total,row)=>total+(row?.count||0),0),blocked:0,processId:runtime.processId,timestamp:new Date().toISOString()});}catch(e){next(e);}});
module.exports=router;
