const express = require('express');
const crypto = require('crypto');
const router = express.Router();
const { getDatabase } = require('../db');
const vault = require('../services/secretVault');
const { requireRole, hashKey } = require('../middleware/auth');

async function dbReady() { const db = await getDatabase(); await db.exec("CREATE TABLE IF NOT EXISTS sso_providers (id TEXT PRIMARY KEY, issuer TEXT NOT NULL, client_id TEXT NOT NULL, redirect_uri TEXT NOT NULL, client_secret_json TEXT, scopes TEXT NOT NULL DEFAULT 'openid profile email', enabled INTEGER NOT NULL DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)"); await db.exec('CREATE TABLE IF NOT EXISTS user_identities (id TEXT PRIMARY KEY, provider_id TEXT NOT NULL, subject TEXT NOT NULL, email TEXT, display_name TEXT, role TEXT NOT NULL DEFAULT \'viewer\', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE(provider_id, subject))'); return db; }
function decodeJwt(token) { try { return JSON.parse(Buffer.from(token.split('.')[1], 'base64url').toString('utf8')); } catch (_) { return {}; } }
router.get('/providers', async (req, res, next) => { try { const db = await dbReady(); res.json(await db.all('SELECT id,issuer,client_id,redirect_uri,scopes,enabled FROM sso_providers ORDER BY id')); } catch (e) { next(e); } });
router.post('/providers', requireRole(['admin']), async (req, res, next) => { try { const db = await dbReady(); const { id, issuer, clientId, clientSecret, redirectUri, scopes = 'openid profile email' } = req.body || {}; if (!id || !issuer || !clientId || !redirectUri) return res.status(400).json({ error: { code: 'INVALID_SSO_PROVIDER', message: 'id, issuer, clientId and redirectUri are required.' } }); const encrypted = clientSecret ? JSON.stringify(vault.encrypt(clientSecret)) : null; await db.run('INSERT OR REPLACE INTO sso_providers(id,issuer,client_id,redirect_uri,client_secret_json,scopes,enabled) VALUES(?,?,?,?,?,?,1)', id, issuer.replace(/\/$/, ''), clientId, redirectUri, encrypted, scopes); res.status(201).json({ id, issuer, clientId, redirectUri, scopes }); } catch (e) { next(e); } });
router.get('/start/:id', async (req, res, next) => { try { const db = await dbReady(); const provider = await db.get('SELECT * FROM sso_providers WHERE id=? AND enabled=1', req.params.id); if (!provider) return res.status(404).json({ error: { code: 'SSO_PROVIDER_NOT_FOUND', message: 'SSO provider not found.' } }); const state = crypto.randomBytes(18).toString('base64url'); res.redirect(`${provider.issuer}/authorize?${new URLSearchParams({ response_type: 'code', client_id: provider.client_id, redirect_uri: provider.redirect_uri, scope: provider.scopes, state })}`); } catch (e) { next(e); } });
router.get('/callback/:id', async (req, res, next) => { try { const db = await dbReady(); const provider = await db.get('SELECT * FROM sso_providers WHERE id=? AND enabled=1', req.params.id); if (!provider || !req.query.code) return res.status(400).json({ error: { code: 'INVALID_SSO_CALLBACK', message: 'Provider and authorization code are required.' } }); const secret = provider.client_secret_json ? vault.decrypt(JSON.parse(provider.client_secret_json)) : undefined; const tokenResponse = await fetch(`${provider.issuer}/token`, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ grant_type: 'authorization_code', code: String(req.query.code), redirect_uri: provider.redirect_uri, client_id: provider.client_id, ...(secret ? { client_secret: secret } : {}) }) }); if (!tokenResponse.ok) throw new Error(`OIDC token exchange returned ${tokenResponse.status}`); const tokens = await tokenResponse.json(); const claims = decodeJwt(tokens.id_token || ''); const subject = claims.sub || claims.email; if (!subject) throw new Error('OIDC identity token has no subject.'); const identityId = `identity-${crypto.randomUUID()}`; await db.run('INSERT INTO user_identities(id,provider_id,subject,email,display_name,role) VALUES(?,?,?,?,?,?) ON CONFLICT(provider_id,subject) DO UPDATE SET email=excluded.email, display_name=excluded.display_name', identityId, provider.id, subject, claims.email || null, claims.name || claims.preferred_username || subject, 'viewer'); const identity = await db.get('SELECT * FROM user_identities WHERE provider_id=? AND subject=?', provider.id, subject); const token = `sso_${crypto.randomBytes(32).toString('hex')}`; await db.run('INSERT INTO sessions(id,token_hash,role,username,expires_at) VALUES(?,?,?,?,datetime(\'now\',\'+8 hours\'))', `session-${crypto.randomUUID()}`, hashKey(token), identity.role, identity.display_name || identity.email || subject); res.json({ token, user: { id: identity.id, username: identity.display_name, email: identity.email, role: identity.role }, expiresIn: 28800 }); } catch (e) { next(e); } });
module.exports = router;
