'use strict';

const SCOPES = Object.freeze(['MISSION', 'WORKSPACE', 'PROJECT', 'PERSISTENT']);
const STATUSES = Object.freeze(['ACTIVE', 'QUIESCENT', 'CLOSED', 'SUSPENDED']);
const EVENT_TYPES = Object.freeze([
  'HOST_CREATED', 'CONSTITUTION_UPDATED', 'SYMBIONT_DISCOVERED',
  'SYMBIONT_ADMISSION_STARTED', 'SYMBIONT_ADMITTED', 'SYMBIONT_REJECTED',
  'SYMBIONT_QUARANTINED', 'SYMBIONT_SANCTIONED', 'SYMBIONT_EXPELLED',
  'SYMBIONT_DORMANT', 'RESOURCE_GRANTED', 'RESOURCE_REVOKED',
  'CAPABILITY_USED', 'CONTRIBUTION_VERIFIED', 'IMMUNE_REJECTION',
  'IMMUNE_OVERRIDE', 'VERTICAL_TRANSMISSION', 'HORIZONTAL_ACQUISITION',
  'VARIANT_SELECTED', 'VARIANT_RUNTIME_EVALUATED'
]);

module.exports = { SCOPES, STATUSES, EVENT_TYPES };
