[build]
jobs = 2

[target.x86_64-pc-windows-msvc]
linker = "link.exe"
rustflags = ["-C", "link-arg=/DEBUG:NONE", "-C", "link-arg=/INCREMENTAL:NO"]

[profile.test]
debug = 0
strip = "debuginfo"
incremental = false
debug-assertions = true
overflow-checks = true
codegen-units = 1

[profile.bench]
debug = false
debug-assertions = false
codegen-units = 1

[profile.dev]
debug = 0
strip = "debuginfo"
incremental = false
debug-assertions = true
overflow-checks = true
codegen-units = 1

[profile.release]
debug = false
debug-assertions = false
codegen-units = 1
lto = "thin"
