//! Provenance tree renderer for the `inspect belief` command.
//!
//! Extracted from `output.rs` so the parent module stays under the 400-line
//! rule. The printer is plain-text only; structured output (JSON / YAML)
//! flows through `print_serialized` in the parent.

use genos_core::ProvenanceNode;

/// Render a [`ProvenanceNode`] tree to stdout using `├──` / `└──` connectors
/// and edge labels (`derived from`, `generated by`, `noted as`) between the
/// connector and the child label.
///
/// Example:
///
/// ```text
/// api returns_one yes (confidence=0.90, status=Inferred)
/// ├── derived from db_query (success, <id>)
/// │       └── generated by tool_completed seq=2 branch=<…>
/// └── noted as from the README
/// ```
pub fn print_provenance_tree(node: &ProvenanceNode) {
    print_node(node, "", true);
}

fn print_node(node: &ProvenanceNode, prefix: &str, is_last: bool) {
    // The connector for the *current* node is rendered by the caller's
    // branch construction; we only print this node's own label here.
    println!("{}", node_label(node));

    let child_count = node.children.len();
    for (index, child) in node.children.iter().enumerate() {
        let last = index + 1 == child_count;
        let connector = if last { "└── " } else { "├── " };
        let next_prefix = format!("{prefix}{}", if last { "    " } else { "│   " });
        // Edge label sits between the connector and the child label.
        let edge_prefix = match child.edge.as_deref() {
            Some(edge) => format!("{edge} "),
            None => String::new(),
        };
        // Render the child's label *as the connector line*; subsequent
        // grandchildren hang off the trailing prefix.
        println!("{prefix}{connector}{edge_prefix}{}", child_label(child));
        let grand_count = child.children.len();
        for (g_index, grand) in child.children.iter().enumerate() {
            let g_last = g_index + 1 == grand_count;
            let g_connector = if g_last { "└── " } else { "├── " };
            let g_edge_prefix = match grand.edge.as_deref() {
                Some(edge) => format!("{edge} "),
                None => String::new(),
            };
            println!(
                "{next_prefix}{g_connector}{g_edge_prefix}{}",
                child_label(grand)
            );
            // Deeper descendants (rare for this tree shape) get pushed to a
            // recursive print pass; since the inspect tree depth is
            // evidence-size × 2, this stays bounded in practice.
            if !grand.children.is_empty() {
                print_descendants(
                    grand,
                    &format!("{next_prefix}{}", if g_last { "    " } else { "│   " }),
                );
            }
        }
        let _ = is_last;
    }
}

fn print_descendants(node: &ProvenanceNode, prefix: &str) {
    let last_index = node.children.len();
    for (index, child) in node.children.iter().enumerate() {
        let last = index + 1 == last_index;
        let connector = if last { "└── " } else { "├── " };
        let edge_prefix = match child.edge.as_deref() {
            Some(edge) => format!("{edge} "),
            None => String::new(),
        };
        println!("{prefix}{connector}{edge_prefix}{}", child_label(child));
        if !child.children.is_empty() {
            let next = format!("{prefix}{}", if last { "    " } else { "│   " });
            print_descendants(child, &next);
        }
    }
}

fn node_label(node: &ProvenanceNode) -> String {
    match (&node.id, &node.kind[..]) {
        (Some(id), "belief") => format!("{} ({})", node.label, id),
        _ => node.label.clone(),
    }
}

fn child_label(node: &ProvenanceNode) -> String {
    match (&node.id, &node.kind[..]) {
        (Some(id), "tool_output") | (Some(id), "event") | (Some(id), "missing") => {
            format!("{} ({})", node.label, id)
        }
        _ => node.label.clone(),
    }
}
