use rand::rngs::StdRng;
use rand::{RngCore, SeedableRng};
use std::sync::Mutex;
use std::time::SystemTime;
use uuid::Uuid;

/// Abstraction over OS entropy (Time and Randomness) to enable perfect reproducibility
/// when replaying agent trajectories.
pub trait Environment: Send + Sync {
    /// Returns the current time (real or frozen).
    fn now(&self) -> SystemTime;

    /// Generates a new unique identifier (real UUID v4 or deterministic pseudo-UUID).
    fn new_uuid(&self) -> Uuid;

    /// Generates a random u64 value (true randomness or deterministic PRNG).
    fn random_u64(&self) -> u64;
}

/// The default environment for live agents, directly hooked to the OS.
#[derive(Clone, Default)]
pub struct RealEnvironment;

impl RealEnvironment {
    pub fn new() -> Self {
        Self
    }
}

impl Environment for RealEnvironment {
    fn now(&self) -> SystemTime {
        SystemTime::now()
    }

    fn new_uuid(&self) -> Uuid {
        Uuid::new_v4()
    }

    fn random_u64(&self) -> u64 {
        rand::thread_rng().next_u64()
    }
}

/// A frozen environment used for deterministic replay (`genos agent replay`).
pub struct FrozenEnvironment {
    fixed_time: SystemTime,
    prng: Mutex<StdRng>,
}

impl FrozenEnvironment {
    pub fn new(fixed_time: SystemTime, seed: u64) -> Self {
        Self {
            fixed_time,
            prng: Mutex::new(StdRng::seed_from_u64(seed)),
        }
    }
}

impl Environment for FrozenEnvironment {
    fn now(&self) -> SystemTime {
        self.fixed_time
    }

    fn new_uuid(&self) -> Uuid {
        let mut prng = self.prng.lock().unwrap();
        let mut bytes = [0u8; 16];
        prng.fill_bytes(&mut bytes);

        // Ensure the generated bytes form a valid UUID v4 (RFC 4122)
        bytes[6] = (bytes[6] & 0x0f) | 0x40; // Version 4
        bytes[8] = (bytes[8] & 0x3f) | 0x80; // Variant 1

        Uuid::from_bytes(bytes)
    }

    fn random_u64(&self) -> u64 {
        let mut prng = self.prng.lock().unwrap();
        prng.next_u64()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_frozen_environment_is_deterministic() {
        let time = SystemTime::UNIX_EPOCH;

        let env1 = FrozenEnvironment::new(time, 42);
        let env2 = FrozenEnvironment::new(time, 42);

        assert_eq!(env1.now(), time);
        assert_eq!(env2.now(), time);

        // First 3 calls should match exactly between the two identical environments
        for _ in 0..3 {
            assert_eq!(env1.random_u64(), env2.random_u64());
            assert_eq!(env1.new_uuid(), env2.new_uuid());
        }
    }

    #[test]
    fn test_frozen_environment_uuids_are_valid_v4() {
        let env = FrozenEnvironment::new(SystemTime::UNIX_EPOCH, 1234);
        let id = env.new_uuid();
        assert_eq!(id.get_version_num(), 4);
    }
}
