import fs from 'fs';
import { execSync } from 'child_process';
import path from 'path';

console.log("=== GenOS Orchestrator CLI ===");
console.log("Checking that all GenOS features (organizations, biomimicry, strategies) are usable by agents...");

const seedToolsPath = 'backend/src/db/seedTools.js';
let seedToolsCode = fs.readFileSync(seedToolsPath, 'utf8');

const orgServiceCode = fs.readFileSync('backend/src/services/dynamicOrganizationService.js', 'utf8');
const orgMatches = orgServiceCode.match(/ORGANIZATIONS\s*=\s*Object\.freeze\(\{([\s\S]+?)\}\);/);
const orgs = [];
if (orgMatches) {
  const lines = orgMatches[1].split('\n');
  for (const line of lines) {
    const m = line.match(/^\s*([a-zA-Z0-9_]+)\s*:/);
    if (m) orgs.push(m[1]);
  }
}

const missingOrgs = orgs.filter(org => !seedToolsCode.includes(org));
console.log(`Found ${missingOrgs.length} missing organizations.`);

import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const strategies1 = require('../backend/src/strategies/families/coreStrategies.js');
const strategies2 = require('../backend/src/strategies/families/knowledgeResilienceStrategies.js');
const strategies3 = require('../backend/src/strategies/families/temporalCollectiveStrategies.js');
const allStrategies = [...strategies1, ...strategies2, ...strategies3];

const allToolReqs = new Set();
for (const s of allStrategies) {
  for (const t of (s.primitives || [])) {
    allToolReqs.add(t);
  }
}

const missingStrats = [...allToolReqs].filter(t => !seedToolsCode.includes(t));
console.log(`Found ${missingStrats.length} missing strategy primitives.`);

if (missingOrgs.length === 0 && missingStrats.length === 0) {
  console.log("All features are correctly mapped to tools. Nothing to do.");
  process.exit(0);
}

let newTools = [];
for (const org of missingOrgs) {
  const niceName = org.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
  newTools.push(`  { name: 'genos_org_${org}', cat: 'Swarm Biomimicry', risk: 'Low', desc: 'Activate ${niceName} organization mode' },`);
}

for (const strat of missingStrats) {
  const niceName = strat.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
  newTools.push(`  { name: 'genos_strat_${strat}', cat: 'Strategy Primitives', risk: 'Amber', desc: 'Execute ${niceName} strategy primitive' },`);
}

seedToolsCode = seedToolsCode.replace(/\n];/, ',\n\n  // Auto-generated by Orchestrator CLI\n' + newTools.join('\n') + '\n];');
fs.writeFileSync(seedToolsPath, seedToolsCode, 'utf8');

console.log("Corrected backend/src/db/seedTools.js with all missing features.");
execSync('git add backend/src/db/seedTools.js');
execSync('git commit -m "feat(orchestrator): auto-correct missing biomimicry orgs and strategy primitives for agents"');
console.log("Committed corrections to Git.");
