[package]
name = "epsilon_mcts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
rand = "0.10.2"
rayon = "1.12.0"
pyo3 = { version = "0.20.2", features = ["auto-initialize"] }

[lints]
workspace = true
