$ErrorActionPreference = "Stop"

$cargoCommand = Get-Command cargo -ErrorAction SilentlyContinue
if (-not $cargoCommand) {
	$cargoFromRustup = Join-Path $env:USERPROFILE ".cargo\bin\cargo.exe"
	if (Test-Path $cargoFromRustup) {
		$env:Path = "$(Split-Path $cargoFromRustup);$env:Path"
		$cargoCommand = Get-Command cargo -ErrorAction SilentlyContinue
	}
}

if (-not $cargoCommand) {
	throw "cargo introuvable. Installe Rust via rustup (https://rustup.rs) puis ouvre un nouveau terminal PowerShell."
}

function Invoke-Cargo {
	param(
		[Parameter(ValueFromRemainingArguments = $true)]
		[string[]]$CargoArgs
	)

	& cargo @CargoArgs
	if ($LASTEXITCODE -ne 0) {
		throw "cargo command failed: cargo $($CargoArgs -join ' ')"
	}
}

function Invoke-Genos {
	param(
		[Parameter(ValueFromRemainingArguments = $true)]
		[string[]]$GenosArgs
	)

	Invoke-Cargo run --quiet -p genos-cli -- @GenosArgs
}

function Invoke-GenosJson {
	param(
		[Parameter(ValueFromRemainingArguments = $true)]
		[string[]]$GenosArgs
	)

	$output = & cargo run --quiet -p genos-cli -- @GenosArgs
	if ($LASTEXITCODE -ne 0) {
		throw "genos command failed: genos $($GenosArgs -join ' ')"
	}

	$text = $output -join "`n"
	Write-Host $text
	$text | ConvertFrom-Json
}

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
Push-Location $repoRoot

try {
	$demoDir = ".genos/demo/belief-provenance"
	$snapshotStore = "$demoDir/agent-snapshots.jsonl"
	$eventStore = "$demoDir/agent-events.jsonl"
	$agentPath = "$demoDir/agent-a.json"
	$s0Path = "$demoDir/snapshot-s0.json"

	if (Test-Path $demoDir) {
		Remove-Item -Recurse -Force $demoDir
	}
	New-Item -ItemType Directory -Path $demoDir | Out-Null

	Write-Host "[0/6] build the genos CLI"
	Invoke-Cargo build -p genos-cli

	Write-Host "[1/6] init + create agent A and snapshot S0"
	Invoke-Genos init
	Invoke-Genos agent create --name belief-provenance --role tester --out $agentPath --format json
	Invoke-Genos snapshot create --agent $agentPath --out $s0Path --format json
	Invoke-Genos snapshot save --snapshot $s0Path --store $snapshotStore --format json

	Write-Host "[2/6] record the db_query tool call T1 on S0"
	$t1Out = Invoke-GenosJson snapshot record-tool-call `
		--snapshot $s0Path `
		--tool-name db_query `
		--input '{"sql":"SELECT 1"}' `
		--output '{"rows":1}' `
		--success true `
		--snapshots $snapshotStore --save `
		--events $eventStore --emit-events `
		--format json
	$t1Id = $t1Out.tool_output_id
	$t1CompletedEventId = $t1Out.completed_event_id
	if (-not $t1Out.tool_name -eq "db_query") { throw "expected tool_name=db_query on T1" }
	if (-not $t1Out.success) { throw "expected success=true on T1" }

	Write-Host "[3/6] derive belief B1 from T1 evidence"
	$b1Out = Invoke-GenosJson snapshot set-belief `
		--snapshot $s0Path `
		--subject api --predicate returns_one --object yes --confidence 0.9 `
		--evidence $t1Id `
		--snapshots $snapshotStore --save `
		--events $eventStore --emit-events `
		--format json
	$b1Id = $b1Out.belief_id
	if ($b1Out.status -ne "inferred") { throw "expected status=inferred on B1, got $($b1Out.status)" }
	if ($b1Out.tool_output_id -ne $t1Id) { throw "expected tool_output_id=$t1Id on B1, got $($b1Out.tool_output_id)" }
	if (-not ($b1Out.added_evidence -contains $t1Id)) {
		throw "expected added_evidence to contain $t1Id on B1"
	}

	Write-Host "[4/6] inspect text -- assert tree shape"
	$textFile = "$demoDir/inspect-text.txt"
	& cargo run --quiet -p genos-cli -- inspect belief `
		--snapshot $s0Path `
		--belief-id $b1Id `
		--events $eventStore `
		--format text `
		> $textFile 2>&1
	if ($LASTEXITCODE -ne 0) { throw "inspect belief (text) failed" }
	$inspectText = Get-Content -Raw $textFile
	Write-Host $inspectText
	if (-not ($inspectText -match "api returns_one yes")) {
		throw "expected inspect text to mention 'api returns_one yes', got: $inspectText"
	}
	if (-not ($inspectText -match "derived from db_query")) {
		throw "expected 'derived from db_query' edge, got: $inspectText"
	}
	if (-not ($inspectText -match "generated by tool_completed")) {
		throw "expected 'generated by tool_completed' edge, got: $inspectText"
	}

	Write-Host "[5/6] inspect JSON -- assert structured shape"
	$jsonFile = "$demoDir/inspect.json"
	Invoke-Genos inspect belief `
		--snapshot $s0Path `
		--belief-id $b1Id `
		--events $eventStore `
		--format json `
		> $jsonFile
	if ($LASTEXITCODE -ne 0) { throw "inspect belief (json) failed" }
	$inspectJson = Get-Content -Raw $jsonFile | ConvertFrom-Json
	if ($inspectJson.tree.kind -ne "belief") {
		throw "expected tree root kind=belief, got $($inspectJson.tree.kind)"
	}
	if ($inspectJson.tree.children[0].kind -ne "tool_output") {
		throw "expected first child kind=tool_output, got $($inspectJson.tree.children[0].kind)"
	}
	if ($inspectJson.tree.children[0].children[0].kind -ne "event") {
		throw "expected grandchild kind=event, got $($inspectJson.tree.children[0].children[0].kind)"
	}
	if ($inspectJson.tree.children[0].edge -ne "derived from") {
		throw "expected edge='derived from', got $($inspectJson.tree.children[0].edge)"
	}
	if ($inspectJson.tree.children[0].children[0].edge -ne "generated by") {
		throw "expected grandchild edge='generated by', got $($inspectJson.tree.children[0].children[0].edge)"
	}

	Write-Host "[6/6] replay S0's stream -- request + completion + belief creation"
	Invoke-Genos replay basic --events $eventStore --snapshot $s0Path --expect-last-sequence 3 --format json

	$s0Id = (Get-Content -Raw $s0Path | ConvertFrom-Json).snapshot_id
	$resolvedCursor = (Invoke-Genos snapshot get --snapshot-id $s0Id --store $snapshotStore --format json).state.event_cursor.sequence
	if ($resolvedCursor -ne 3) { throw "expected event_cursor.sequence=3 on S0, got $resolvedCursor" }

	$s0Json = Get-Content -Raw $s0Path | ConvertFrom-Json
	$b1Evidence = ($s0Json.state.beliefs | Where-Object { $_.id -eq $b1Id } | Select-Object -First 1).evidence
	if (-not $b1Evidence) { throw "expected B1 to carry evidence on disk" }
	$evidenceHasT1 = $false
	foreach ($ref in $b1Evidence) {
		if ($ref.PSObject.Properties.Name -contains "ToolOutput") {
			if ($ref.ToolOutput.tool_output_id -eq $t1Id) { $evidenceHasT1 = $true; break }
		}
	}
	if (-not $evidenceHasT1) { throw "expected B1 evidence to cite T1 ($t1Id), got: $($b1Evidence | ConvertTo-Json)" }

	Write-Host ""
	Write-Host "Demo OK: B1 derived from T1 generated by E1"
	Write-Host "b1_id=$b1Id"
	Write-Host "t1_id=$t1Id"
	Write-Host "snapshot_store=$snapshotStore"
	Write-Host "event_store=$eventStore"
	Write-Host "parent_s0=$s0Path"
	Write-Host "inspect_text=$textFile"
	Write-Host "inspect_json=$jsonFile"
}
finally {
	Pop-Location
}