#!/usr/bin/env bash
# Drives the genos CLI through the belief provenance scenario:
#   event E1 -> tool output T1 -> belief B1
# then renders the inspect tree showing B1, derived from T1, generated by E1.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$repo_root"

# --- helpers ----------------------------------------------------------------

if ! command -v cargo >/dev/null 2>&1; then
	echo "cargo not found. Install Rust via rustup (https://rustup.rs)." >&2
	exit 1
fi

run_cargo() {
	cargo "$@"
}

run_genos() {
	run_cargo run --quiet -p genos-cli -- "$@"
}

run_genos_json() {
	local out
	out="$(run_genos "$@")"
	printf '%s\n' "$out"
}

# --- layout -----------------------------------------------------------------

demo_dir=".genos/demo/belief-provenance"
snapshot_store="$demo_dir/agent-snapshots.jsonl"
event_store="$demo_dir/agent-events.jsonl"
agent_path="$demo_dir/agent-a.json"
s0_path="$demo_dir/snapshot-s0.json"

rm -rf "$demo_dir"
mkdir -p "$demo_dir"

# --- 0. build ---------------------------------------------------------------

echo "[0/6] build the genos CLI"
run_cargo build -p genos-cli

# --- 1. init + create agent A + snapshot S0 -------------------------------

echo "[1/6] init + create agent A and snapshot S0"
run_genos init
run_genos agent create --name belief-provenance --role tester \
	--out "$agent_path" --format json
run_genos snapshot create \
	--agent "$agent_path" \
	--out "$s0_path" \
	--format json
run_genos snapshot save --snapshot "$s0_path" \
	--store "$snapshot_store" --format json

# --- 2. record the tool call T1 --------------------------------------------

echo "[2/6] record the db_query tool call T1 on S0"
t1_out="$(run_genos_json snapshot record-tool-call \
	--snapshot "$s0_path" \
	--tool-name db_query \
	--input '{"sql":"SELECT 1"}' \
	--output '{"rows":1}' \
	--success \
	--snapshots "$snapshot_store" --save \
	--events "$event_store" --emit-events \
	--format json 2>/dev/null)"
t1_id="$(printf '%s\n' "$t1_out" | grep -o '"tool_output_id": *"[^"]*"' | head -1 | sed 's/.*"\([^"]*\)"$/\1/')"
t1_completed_event_id="$(printf '%s\n' "$t1_out" | grep -o '"completed_event_id": *"[^"]*"' | head -1 | sed 's/.*"\([^"]*\)"$/\1/')"
[ -n "$t1_id" ] \
	|| { echo "could not extract tool_output_id from T1 record: $t1_out" >&2; exit 1; }
[ -n "$t1_completed_event_id" ] \
	|| { echo "could not extract completed_event_id from T1 record: $t1_out" >&2; exit 1; }
printf '%s\n' "$t1_out" | grep -q '"tool_name": *"db_query"' \
	|| { echo "expected tool_name=db_query on T1, got: $t1_out" >&2; exit 1; }
printf '%s\n' "$t1_out" | grep -q '"success": *true' \
	|| { echo "expected success=true on T1, got: $t1_out" >&2; exit 1; }

# --- 3. derive belief B1 from T1 --------------------------------------------

echo "[3/6] derive belief B1 from T1 evidence"
b1_out="$(run_genos_json snapshot set-belief \
	--snapshot "$s0_path" \
	--subject api --predicate returns_one --object yes --confidence 0.9 \
	--evidence "$t1_id" \
	--snapshots "$snapshot_store" --save \
	--events "$event_store" --emit-events \
	--format json 2>/dev/null)"
b1_id="$(printf '%s\n' "$b1_out" | grep -o '"belief_id": *"[^"]*"' | head -1 | sed 's/.*"\([^"]*\)"$/\1/')"
[ -n "$b1_id" ] \
	|| { echo "could not extract belief_id from B1: $b1_out" >&2; exit 1; }

# Status must auto-flip to "inferred" because evidence was supplied and no
# explicit --status was passed.
if ! printf '%s\n' "$b1_out" | grep -q '"status": *"inferred"'; then
	echo "expected status=inferred on B1, got: $b1_out" >&2
	exit 1
fi
# tool_output_id on the response must be T1's id (the convenience field).
if ! printf '%s\n' "$b1_out" | grep -q "\"tool_output_id\": *\"$t1_id\""; then
	echo "expected tool_output_id=$t1_id on B1, got: $b1_out" >&2
	exit 1
fi
# added_evidence must list T1 (the only ref supplied).
if ! printf '%s\n' "$b1_out" | grep -q "\"added_evidence\""; then
	echo "expected added_evidence on B1, got: $b1_out" >&2
	exit 1
fi
if ! printf '%s\n' "$b1_out" | grep -q "$t1_id"; then
	echo "expected added_evidence to mention $t1_id on B1, got: $b1_out" >&2
	exit 1
fi

# --- 4. inspect text -- B1 derived from T1, generated by E1 -----------------

echo "[4/6] inspect text -- assert tree shape"
text_file="$demo_dir/inspect-text.txt"
run_genos inspect belief \
	--snapshot "$s0_path" \
	--belief-id "$b1_id" \
	--events "$event_store" \
	--format text \
	>"$text_file" 2>&1 || true
inspect_text="$(cat "$text_file")"
printf '%s\n' "$inspect_text"

# The belief root line carries B1's id.
if ! printf '%s\n' "$inspect_text" | grep -q "api returns_one yes"; then
	echo "expected inspect text to mention 'api returns_one yes', got: $inspect_text" >&2
	exit 1
fi
# T1 (the tool output node) must appear as a child with the
# 'derived from' edge label.
if ! printf '%s\n' "$inspect_text" | grep -q "derived from db_query"; then
	echo "expected 'derived from db_query' edge, got: $inspect_text" >&2
	exit 1
fi
# E1 (the originating event) must appear under T1 with the
# 'generated by' edge label.
if ! printf '%s\n' "$inspect_text" | grep -q "generated by tool_completed"; then
	echo "expected 'generated by tool_completed' edge, got: $inspect_text" >&2
	exit 1
fi

# --- 5. inspect JSON -- machine-parseable shape ----------------------------

echo "[5/6] inspect JSON -- assert structured shape"
json_file="$demo_dir/inspect.json"
run_genos inspect belief \
	--snapshot "$s0_path" \
	--belief-id "$b1_id" \
	--events "$event_store" \
	--format json \
	>"$json_file"
if ! grep -q '"kind": *"belief"' "$json_file"; then
	echo "expected tree root kind=belief in JSON, got: $(cat "$json_file")" >&2
	exit 1
fi
if ! grep -q '"kind": *"tool_output"' "$json_file"; then
	echo "expected first child kind=tool_output in JSON, got: $(cat "$json_file")" >&2
	exit 1
fi
if ! grep -q '"kind": *"event"' "$json_file"; then
	echo "expected grandchild kind=event in JSON, got: $(cat "$json_file")" >&2
	exit 1
fi
if ! grep -q '"edge": *"derived from"' "$json_file"; then
	echo "expected edge='derived from' in JSON, got: $(cat "$json_file")" >&2
	exit 1
fi
if ! grep -q '"edge": *"generated by"' "$json_file"; then
	echo "expected edge='generated by' in JSON, got: $(cat "$json_file")" >&2
	exit 1
fi

# --- 6. replay assertion ----------------------------------------------------

echo "[6/6] replay S0's stream -- request + completion + belief creation"
run_genos replay basic --events "$event_store" --snapshot "$s0_path" \
	--expect-last-sequence 3 --format json

# event_cursor.sequence on S0 should be 3 after the three writes
# (T1.requested, T1.completed, B1.created).
s0_json="$(cat "$s0_path")"
last_cursor="$(printf '%s\n' "$s0_json" | grep -o '"sequence": *[0-9]*' | head -1 | sed 's/.*: *//')"
[ "$last_cursor" = "3" ] \
	|| { echo "expected event_cursor.sequence=3 on S0, got $last_cursor" >&2; exit 1; }

# The on-disk belief B1 must carry T1 in its `evidence` list.
# Look at the chunk of the JSON around B1's id, then check it mentions
# T1's id inside the same chunk. `-A` walks forward 14 lines, which is
# enough to span the belief block including its `evidence` array.
b1_chunk="$(printf '%s\n' "$s0_json" | grep -A14 "\"id\": *\"$b1_id\"")"
if ! printf '%s\n' "$b1_chunk" | grep -q "\"tool_output_id\": *\"$t1_id\""; then
	echo "expected B1 on-disk to carry T1 evidence, snapshot chunk: $b1_chunk" >&2
	exit 1
fi

echo ""
echo "Demo OK: B1 derived from T1 generated by E1"
echo "b1_id=$b1_id"
echo "t1_id=$t1_id"
echo "snapshot_store=$snapshot_store"
echo "event_store=$event_store"
echo "parent_s0=$s0_path"
echo "inspect_text=$text_file"
echo "inspect_json=$json_file"