import React, { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, GitBranch, ShieldCheck, Network, Bell, Play, Scissors } from 'lucide-react';
import { api } from '../api/client';
import { useToastStore } from '../store/useToastStore';

type Tab = 'mcts' | 'safety' | 'provenance' | 'swarm' | 'compare' | 'notifications';

export const EvaluationLineageConsole: React.FC = () => {
  const [tab, setTab] = useState<Tab>('mcts');
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [bench, setBench] = useState<any>(null);
  const [threshold, setThreshold] = useState(0.65);
  const showToast = useToastStore((s) => s.showToast);
  const load = () => api.getEvaluationOverview().then(setData).catch((e) => showToast('error', 'Evaluation backend', e.message)).finally(() => setLoading(false));
  useEffect(() => { load(); const timer = window.setInterval(load, 8000); return () => window.clearInterval(timer); }, []);

  const nodes = data?.mcts?.nodes || [];
  const edges = data?.mcts?.edges || [];
  const roots = useMemo(() => nodes.filter((n: any) => !edges.some((e: any) => e.target === n.id)), [nodes, edges]);
  const runBench = async () => { try { setBench(await api.runImpossibleBench({ abstentionThreshold: threshold })); load(); } catch (e: any) { showToast('error', 'ImpossibleBench', e.message); } };
  const prune = async (id: string) => { try { await api.pruneMctsNode(id); showToast('success', 'Branch pruned', 'The MCTS lineage remains auditable through provenance.'); load(); } catch (e: any) { showToast('error', 'Prune failed', e.message); } };
  const updateNotifications = async () => { try { await api.updateNotificationPreferences((data?.notifications || []).map((n: any) => ({ ...n, enabled: n.enabled }))); showToast('success', 'Notifications saved', 'Error, drift, budget, blocking and escalation rules persisted.'); } catch (e: any) { showToast('error', 'Notifications', e.message); } };

  const tabs: Array<[Tab, string, React.ReactNode]> = [['mcts', 'MCTS / trajectories', <GitBranch size={14} />], ['safety', 'Abstention / ImpossibleBench', <ShieldCheck size={14} />], ['provenance', 'Provenance cryptographique', <Activity size={14} />], ['swarm', 'Stigmergie / quorum', <Network size={14} />], ['compare', 'Versions & compétences', <GitBranch size={14} />], ['notifications', 'Notifications', <Bell size={14} />]];
  return <div style={{ height: '100%', overflowY: 'auto', padding: '24px 32px', background: 'var(--bg-main)', color: 'var(--text-primary)' }}>
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start', marginBottom: 18 }}><div><h1 style={{ margin: 0, fontSize: '1.25rem' }}>Evaluation, Lineage & Swarm</h1><p style={{ color: 'var(--text-secondary)', margin: '6px 0' }}>Observabilité backend temps réel · scores, décisions, preuves et garde-fous.</p></div><span style={{ color: data ? 'var(--success)' : 'var(--warning)', fontSize: '.75rem' }}>{loading ? 'Synchronisation…' : 'Backend connecté'}</span></div>
    <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap', marginBottom: 16 }}>{tabs.map(([id, label, icon]) => <button key={id} className="gh-btn" onClick={() => setTab(id)} style={{ background: tab === id ? 'var(--bg-subtle)' : undefined, color: tab === id ? 'var(--text-primary)' : undefined, display: 'flex', gap: 6, alignItems: 'center' }}>{icon}{label}</button>)}</div>
    {tab === 'mcts' && <section style={panel}><h3>Arbre des hypothèses · contrôles MCTS</h3><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', gap: 10 }}>{(roots.length ? roots : nodes).slice(0, 24).map((node: any) => <div key={node.id} style={card}><div style={{ display: 'flex', justifyContent: 'space-between' }}><strong>{node.label}</strong>{node.pruned && <span style={{ color: 'var(--danger)' }}>élagué</span>}</div><small>score {Number(node.score).toFixed(3)} · {node.visits} visites</small><div style={{ height: 5, background: 'var(--bg-main)', margin: '10px 0' }}><div style={{ width: `${Math.max(3, Math.min(100, node.score * 100))}%`, height: '100%', background: node.pruned ? 'var(--text-muted)' : 'var(--accent-blue)' }} /></div>{!node.pruned && <button className="gh-btn" onClick={() => prune(node.id)}><Scissors size={12} /> Élague</button>}</div>)}</div><p style={{ color: 'var(--text-secondary)', fontSize: '.78rem' }}>Les nœuds sont lus depuis lineage_nodes; l’élagage marque la branche et crée une preuve SHA-256, sans supprimer l’historique.</p></section>}
    {tab === 'safety' && <section style={panel}><h3><ShieldCheck size={16} /> Interface abstention & anti-hallucination</h3><label style={{ display: 'block', margin: '16px 0' }}>Seuil d’abstention: <strong>{threshold.toFixed(2)}</strong><input type="range" min="0.1" max="0.95" step="0.01" value={threshold} onChange={(e) => setThreshold(Number(e.target.value))} style={{ width: '100%' }} /></label><button className="gh-btn gh-btn-primary" onClick={runBench}><Play size={13} /> Lancer ImpossibleBench réel</button>{bench && <div style={{ marginTop: 16 }}>{bench.results.map((r: any) => <div key={r.id} style={{ ...card, display: 'flex', justifyContent: 'space-between' }}><span>{r.id} · confiance {r.confidence}</span><strong style={{ color: r.correct ? 'var(--success)' : 'var(--danger)' }}>{r.abstained ? 'ABSTENTION' : 'RÉPONSE'} · {r.correct ? 'OK' : 'ERREUR'}</strong></div>)}<p>Brier: <strong>{bench.brierScore}</strong> · score: <strong>{Math.round(bench.results.filter((r: any) => r.correct).length / bench.results.length * 100)}%</strong></p></div>}</section>}
    {tab === 'provenance' && <section style={panel}><h3>Chaîne de provenance cryptographique</h3>{(data?.provenance || []).map((p: any) => <div key={p.id} style={card}><div><strong>{p.subject_type}</strong> · {p.subject_id}</div><code style={{ fontSize: '.72rem', wordBreak: 'break-all' }}>{p.payload_hash}</code><small style={{ display: 'block', color: 'var(--text-secondary)' }}>{p.algorithm} · {p.created_at}</small></div>)}</section>}
    {tab === 'swarm' && <section style={panel}><h3>Marqueurs de stigmergie & quorum pondéré</h3><p>Agents: <strong>{data?.swarm?.agents?.length || 0}</strong> · messages: <strong>{data?.swarm?.messages?.length || 0}</strong> · Brier moyen: <strong>{data?.evaluations?.brierScore ?? '—'}</strong> · poids: <code>{data?.evaluations?.quorumWeightFormula}</code></p>{(data?.swarm?.weightedVotes || []).map((v: any) => <div key={v.agentId} style={card}><strong>{v.agentId}</strong> · poids de vote <strong>{v.weight}</strong> · Brier {v.brierScore ?? '—'}</div>)}{(data?.swarm?.messages || []).slice(0, 20).map((m: any) => <div key={m.id} style={card}><strong>{m.agent_id || 'agent'}</strong> → {m.payload?.recipient || 'swarm'} <span style={{ color: 'var(--text-secondary)' }}> · {m.action}</span></div>)}</section>}
    {tab === 'compare' && <section style={panel}><h3>Comparaison modèles, prompts, génomes et configurations</h3><p style={{ color: 'var(--text-secondary)' }}>Chaque run expose ses empreintes prompt/genome/config et sa version modèle.</p>{(data?.evaluations?.runs || []).map((r: any) => <div key={r.id} style={card}><strong>{r.benchmark}</strong> · {r.model_version} · score {r.score} · Brier {r.brier_score}<br /><small>prompt {r.prompt_hash?.slice(0, 16)}… · config {r.config_hash?.slice(0, 16)}…</small></div>)}<p style={{ marginTop: 20 }}>Transfert de compétence: utilisez Genome Factory / Memory & Experience pour cherry-pick une expérience; la provenance est conservée par le backend.</p></section>}
    {tab === 'notifications' && <section style={panel}><h3><Bell size={16} /> Notifications configurables</h3>{(data?.notifications || []).map((n: any) => <label key={n.event_type} style={{ ...card, display: 'flex', justifyContent: 'space-between' }}><span>{n.event_type}</span><input type="checkbox" checked={n.enabled} onChange={(e) => setData((d: any) => ({ ...d, notifications: d.notifications.map((x: any) => x.event_type === n.event_type ? { ...x, enabled: e.target.checked } : x) }))} /></label>)}<button className="gh-btn gh-btn-primary" onClick={updateNotifications}>Enregistrer la politique</button></section>}
  </div>;
};

const panel: React.CSSProperties = { background: 'var(--bg-panel)', border: '1px solid var(--panel-border)', borderRadius: 6, padding: 18, minHeight: 320 };
const card: React.CSSProperties = { background: 'var(--bg-main)', border: '1px solid var(--panel-border)', borderRadius: 5, padding: 12, marginBottom: 8 };
