import React, { useEffect, useMemo, useState } from 'react';
import { Activity, GitBranch, ShieldCheck, Route, Play, CheckCircle, XCircle } from 'lucide-react';
import { api } from '../api/client';

const panel: React.CSSProperties = { background: 'var(--bg-panel)', border: '1px solid var(--panel-border)', borderRadius: 8, padding: 16 };
const button: React.CSSProperties = { background: 'var(--accent-blue)', color: '#fff', border: 0, borderRadius: 5, padding: '7px 10px', cursor: 'pointer', fontWeight: 600 };

export const PlatformSafetyCenter: React.FC = () => {
  const [graph, setGraph] = useState<any>({ nodes: [], edges: [] });
  const [telemetry, setTelemetry] = useState<any>({ totals: {}, byAgent: [] });
  const [providers, setProviders] = useState<any[]>([]);
  const [approvals, setApprovals] = useState<any[]>([]);
  const [audit, setAudit] = useState<any[]>([]);
  const [route, setRoute] = useState<any>(null);
  const [incident, setIncident] = useState('inc-001');
  const [replay, setReplay] = useState<any>(null);
  const [message, setMessage] = useState('');
  const load = async () => { try { const [g, t, p, a, l] = await Promise.all([api.getPlatformGraph(), api.getPlatformTelemetry(), api.getPlatformProviders(), api.getPlatformApprovals(), api.getPlatformAudit()]); setGraph(g); setTelemetry(t); setProviders(p); setApprovals(a); setAudit(l); } catch (e: any) { setMessage(e.message); } };
  useEffect(() => { load(); }, []);
  const edges = useMemo(() => new Set((graph.edges || []).map((e: any) => `${e.source}->${e.target}`)), [graph.edges]);
  const runRoute = async () => { try { setRoute(await api.routePlatformModel({ complexity: 0.72, uncertainty: 0.58, requiredCapabilities: ['reasoning'], maxCostUsd: 20 })); } catch (e: any) { setMessage(e.message); } };
  const runReplay = async () => { try { setReplay(await api.replayPlatformIncident(incident)); } catch (e: any) { setMessage(e.message); } };
  const decide = async (id: string, decision: string) => { await api.decidePlatformApproval(id, decision, 'Studio operator decision'); await load(); };
  return <div style={{ width: '100%', height: '100%', overflow: 'auto', padding: 22, color: 'var(--text-primary)' }}>
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18 }}><div><h1 style={{ fontSize: 24 }}>Platform & Safety Center</h1><p style={{ color: 'var(--text-secondary)', marginTop: 5 }}>Causal observability, Zero Trust policy and model governance</p></div><span style={{ color: 'var(--success)', fontSize: 12 }}><ShieldCheck size={14} style={{ verticalAlign: 'middle' }} /> policy plane online</span></div>
    {message && <div style={{ ...panel, borderColor: 'var(--danger)', marginBottom: 12 }}>{message}</div>}
    <div style={{ display: 'grid', gridTemplateColumns: '1.4fr 1fr', gap: 14 }}>
      <section style={panel}><h3><GitBranch size={16} /> Causal DAG & agent lineage</h3><div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginTop: 14 }}>{(graph.nodes || []).map((n: any) => <div key={n.id} title={n.state_summary || ''} style={{ border: '1px solid var(--panel-border)', borderLeft: `3px solid ${n.node_type === 'agent' ? 'var(--accent-purple)' : 'var(--accent-blue)'}`, borderRadius: 5, padding: '8px 10px', minWidth: 145, fontSize: 12 }}><div style={{ fontWeight: 700 }}>{n.label}</div><div style={{ color: 'var(--text-muted)', marginTop: 4 }}>{n.node_type} · {n.status || (n.score !== undefined ? `score ${Number(n.score).toFixed(2)}` : 'recorded')}</div></div>)}</div><div style={{ color: 'var(--text-muted)', fontSize: 11, marginTop: 12 }}>{graph.nodes?.length || 0} nodes · {edges.size} causal edges · persisted lineage source</div></section>
      <section style={panel}><h3><Activity size={16} /> Advanced telemetry</h3><div style={{ display: 'flex', gap: 18, margin: '18px 0' }}><Metric label="events" value={telemetry.totals?.events || 0} /><Metric label="tokens" value={telemetry.totals?.tokens || 0} /><Metric label="cost" value={`$${Number(telemetry.totals?.costUsd || 0).toFixed(3)}`} /></div>{(telemetry.byAgent || []).slice(0, 5).map((r: any) => <div key={`${r.agent_id}-${r.model}`} style={{ display: 'flex', justifyContent: 'space-between', borderTop: '1px solid var(--border-subtle)', padding: '7px 0', fontSize: 12 }}><span>{r.agent_id || 'unknown'} / {r.model || 'runtime'}</span><span>{r.tokens || 0} tok · {Number(r.latencyMs || 0).toFixed(0)}ms</span></div>)}</section>
      <section style={panel}><h3><Route size={16} /> Routing policy preview</h3><p style={{ color: 'var(--text-secondary)', fontSize: 12, margin: '9px 0 12px' }}>{providers.length} enabled provider configurations · this preview does not invoke a model</p><button style={button} onClick={runRoute} disabled={providers.length === 0}>Preview sample workload</button>{providers.length === 0 && <div style={{ color: 'var(--text-muted)', fontSize: 11, marginTop: 8 }}>Register an enabled provider configuration to evaluate routing policy.</div>}{route?.selected && <div style={{ marginTop: 14, padding: 10, background: 'var(--bg-subtle)', borderRadius: 5, fontSize: 12 }}><b>{route.selected.provider} / {route.selected.model}</b><div style={{ color: 'var(--text-secondary)', marginTop: 5 }}>policy score {route.selected.score} · configured latency {route.selected.latencyMs}ms · ${route.selected.costInput + route.selected.costOutput}/1k</div>{route.requiresApproval && <div style={{ color: 'var(--warning)', marginTop: 5 }}>approval required: high uncertainty/complexity</div>}</div>}</section>
      <section style={panel}><h3><Play size={16} /> Causal Incident Studio</h3><div style={{ display: 'flex', gap: 8, margin: '12px 0' }}><input value={incident} onChange={e => setIncident(e.target.value)} style={{ flex: 1, background: 'var(--bg-main)', color: 'var(--text-primary)', border: '1px solid var(--panel-border)', padding: 8, borderRadius: 4 }} /><button style={button} onClick={runReplay}>Replay step-by-step</button></div>{replay && <div style={{ maxHeight: 170, overflow: 'auto', fontSize: 12 }}>{replay.timeline.map((s: any) => <div key={s.step} style={{ borderTop: '1px solid var(--border-subtle)', padding: '7px 0' }}><b>#{s.step} {s.action}</b> · {s.agentId} <span style={{ color: 'var(--text-secondary)' }}>{s.detail}</span></div>)}</div>}<div style={{ color: 'var(--text-muted)', fontSize: 11 }}>Replay is deterministic over the telemetry audit stream; it does not rerun the incident.</div></section>
      <section style={panel}><h3><ShieldCheck size={16} /> Human approvals</h3>{approvals.length === 0 && <div style={{ color: 'var(--text-muted)', fontSize: 12 }}>No pending approvals</div>}{approvals.filter(a => a.status === 'pending').map(a => <div key={a.id} style={{ borderTop: '1px solid var(--border-subtle)', padding: '9px 0', fontSize: 12 }}><b>{a.action}</b> · {a.risk} risk · uncertainty {a.uncertainty}<div style={{ marginTop: 7 }}><button style={{ ...button, background: 'var(--success)', marginRight: 6 }} onClick={() => decide(a.id, 'approve')}><CheckCircle size={13} /> approve</button><button style={{ ...button, background: 'var(--danger)' }} onClick={() => decide(a.id, 'reject')}><XCircle size={13} /> reject</button></div></div>)}</section>
      <section style={panel}><h3>Zero Trust audit log</h3>{audit.slice(0, 7).map((a: any) => <div key={a.id} style={{ borderTop: '1px solid var(--border-subtle)', padding: '7px 0', fontSize: 11 }}><b style={{ color: a.decision === 'deny' ? 'var(--danger)' : 'var(--success)' }}>{a.decision}</b> · {a.action} · {a.resource || 'system'}<div style={{ color: 'var(--text-muted)' }}>{a.reason}</div></div>)}</section>
    </div>
  </div>;
};
const Metric = ({ label, value }: { label: string; value: React.ReactNode }) => <div><div style={{ fontSize: 20, fontWeight: 700 }}>{value}</div><div style={{ color: 'var(--text-muted)', fontSize: 11 }}>{label}</div></div>;
