//! Tests for the provenance walker (the inspect tree builder).

#![cfg(test)]

use super::evidence::EvidenceRef;
use super::provenance::{
    augment_tool_output_node, provenance_for_belief, EventLookup, InMemoryEventLookup,
};
use crate::events::{AgentEvent, AgentEventType};
use crate::ids::EventId;
use crate::snapshot::tests::snapshot_with_variable;
use crate::tool_outputs::{record_tool_call_on_branch, ToolCallRequest};
use crate::upsert_belief_with_evidence;
use serde_json::json;

#[test]
fn inspect_belief_walks_evidence_to_tool_output_to_event() {
    let mut snapshot = snapshot_with_variable("counter", "0");
    let tool_write = record_tool_call_on_branch(
        &mut snapshot,
        ToolCallRequest {
            tool_name: "db_query",
            input: json!({}),
            output: json!({}),
            success: true,
            receipt: None,
            is_tainted: false,
        },
    );

    let belief_write = upsert_belief_with_evidence(
        &mut snapshot,
        "api",
        "returns_one",
        "yes",
        0.9,
        vec![EvidenceRef::ToolOutput {
            tool_output_id: tool_write.record.id.clone(),
        }],
        None,
    )
    .expect("ok");

    // Stand up an EventLookup that knows about the completion event.
    let mut lookup = InMemoryEventLookup::default();
    lookup.events.insert(
        tool_write.completed_event.event_id.clone(),
        tool_write.completed_event.clone(),
    );

    let tree = provenance_for_belief(&snapshot, &belief_write.belief_id, &lookup);

    assert_eq!(tree.kind, "belief");
    assert_eq!(tree.id.as_deref(), Some(belief_write.belief_id.0.as_str()));
    assert_eq!(tree.children.len(), 1);

    let tool_node = &tree.children[0];
    assert_eq!(tool_node.kind, "tool_output");
    assert_eq!(tool_node.edge.as_deref(), Some("derived from"));
    // The walker doesn't itself attach the originating event â€” that's the
    // CLI's `augment_tool_output_node` step, which needs the `ToolOutputRecord`
    // in hand. Call it here and assert the event grandchild is now attached.
    let mut augmented = tool_node.clone();
    augment_tool_output_node(&mut augmented, &tool_write.record, &lookup);
    assert_eq!(augmented.children.len(), 1);

    let event_node = &augmented.children[0];
    assert_eq!(event_node.kind, "event");
    assert_eq!(event_node.edge.as_deref(), Some("generated by"));
}

#[test]
fn inspect_belief_missing_event_renders_a_placeholder() {
    let mut snapshot = snapshot_with_variable("counter", "0");
    let tool_write = record_tool_call_on_branch(
        &mut snapshot,
        ToolCallRequest {
            tool_name: "x",
            input: json!({}),
            output: json!({}),
            success: true,
            receipt: None,
            is_tainted: false,
        },
    );

    let belief_write = upsert_belief_with_evidence(
        &mut snapshot,
        "api",
        "returns_one",
        "yes",
        0.9,
        vec![EvidenceRef::ToolOutput {
            tool_output_id: tool_write.record.id.clone(),
        }],
        None,
    )
    .expect("ok");

    // Empty lookup: the walker still builds the tool_output node, and the
    // augmentation fills a `missing` placeholder for the originating event.
    let lookup = InMemoryEventLookup::default();
    let tree = provenance_for_belief(&snapshot, &belief_write.belief_id, &lookup);
    let mut tool_node = tree.children[0].clone();
    augment_tool_output_node(&mut tool_node, &tool_write.record, &lookup);
    let missing = &tool_node.children[0];
    assert_eq!(missing.kind, "missing");
    assert_eq!(missing.edge.as_deref(), Some("generated by"));
}

#[test]
fn inspect_belief_unknown_id_renders_a_missing_root() {
    let snapshot = snapshot_with_variable("counter", "0");
    let bogus = crate::ids::BeliefId::new();
    let tree = provenance_for_belief(&snapshot, &bogus, &InMemoryEventLookup::default());
    assert_eq!(tree.kind, "missing");
    assert_eq!(tree.id.as_deref(), Some(bogus.0.as_str()));
}

#[test]
fn inspect_belief_note_evidence_uses_noted_as_edge() {
    let mut snapshot = snapshot_with_variable("counter", "0");
    let belief_write = upsert_belief_with_evidence(
        &mut snapshot,
        "api",
        "returns_one",
        "yes",
        0.9,
        vec![EvidenceRef::Note {
            text: "from the README".to_string(),
        }],
        None,
    )
    .expect("ok");

    let lookup = InMemoryEventLookup::default();
    let tree = provenance_for_belief(&snapshot, &belief_write.belief_id, &lookup);
    assert_eq!(tree.children.len(), 1);
    assert_eq!(tree.children[0].kind, "note");
    assert_eq!(tree.children[0].edge.as_deref(), Some("noted as"));
    assert_eq!(tree.children[0].label, "from the README");
}

// Sanity: an `AgentEvent` round-trips through `EventLookup` correctly even
// when the lookup is `InMemoryEventLookup`.
#[test]
fn in_memory_lookup_resolves_known_events() {
    let event = AgentEvent {
        event_id: EventId::new(),
        agent_id: crate::ids::AgentId::new(),
        branch_id: None,
        sequence: 1,
        timestamp: chrono::Utc::now(),
        event_type: AgentEventType::ToolCompleted,
        payload: json!({}),
        causation_id: None,
        correlation_id: None,
    };
    let mut lookup = InMemoryEventLookup::default();
    let known_id = event.event_id.clone();
    assert!(lookup.event(&known_id).is_none());
    lookup.events.insert(known_id.clone(), event.clone());
    let found = lookup.event(&known_id).expect("resolved");
    assert_eq!(found.event_id, known_id);
}
