//! Belief provenance walker — turns `Belief.evidence` into a tree the `inspect`
//! command can render.
//!
//! Tree shape (rooted at the belief):
//!
//! ```text
//! belief (B1)
//! ├── derived from tool_output (T1)
//! │       └── generated by event (E1)
//! └── noted as <text>            (free-form note refs only)
//! ```
//!
//! The walker is data-only: a [`ProvenanceNode`] tree and a [`ProvenanceDetail`]
//! for any extra context. The CLI's `print_provenance_tree` (in
//! `crates/genos-cli/src/output.rs`) renders it.

use crate::events::{AgentEvent, AgentEventType};
use crate::evidence::EvidenceRef;
use crate::ids::{BeliefId, EventId};
use crate::state::ToolOutputRecord;
use crate::AgentSnapshot;
use serde::Serialize;

/// Snake-case variant name of an [`AgentEventType`] for display
/// (e.g. `ToolCompleted` → `tool_completed`). The Debug-derived name
/// (`toolcompleted`) is one word; inserting `_` before each uppercase letter
/// after the first keeps the labels readable in the inspect tree.
fn event_type_label(event_type: &AgentEventType) -> String {
    let mut out = String::new();
    for (index, ch) in format!("{event_type:?}").chars().enumerate() {
        if ch.is_ascii_uppercase() && index > 0 {
            out.push('_');
        }
        out.extend(ch.to_lowercase());
    }
    out
}

/// What the walker needs to look up the originating event for a `ToolOutput`
/// ref. Core doesn't own a `LocalEventStore`, so the trait lets the CLI pass
/// in any backing store it has open.
pub trait EventLookup {
    fn event(&self, id: &EventId) -> Option<AgentEvent>;
}

/// In-memory [`EventLookup`] useful for tests and for callers that already
/// have events in hand.
#[derive(Default)]
pub struct InMemoryEventLookup {
    pub events: std::collections::HashMap<EventId, AgentEvent>,
}

impl EventLookup for InMemoryEventLookup {
    fn event(&self, id: &EventId) -> Option<AgentEvent> {
        self.events.get(id).cloned()
    }
}

/// Tree node the inspect command renders. `kind` is one of `belief`,
/// `tool_output`, `event`, `note`, `missing`. `edge` is the relationship
/// label printed between connector and child (`derived from`,
/// `generated by`, `noted as`).
#[derive(Clone, Debug, Serialize)]
pub struct ProvenanceNode {
    pub kind: String,
    pub id: Option<String>,
    pub label: String,
    pub edge: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<serde_json::Value>,
    pub children: Vec<ProvenanceNode>,
}

#[derive(Clone, Debug, Serialize)]
pub struct ProvenanceDetail {
    pub snapshot_id: String,
    pub branch_id: String,
    pub belief_id: String,
    pub tree: ProvenanceNode,
}

/// Build the provenance tree for a belief on `snapshot`.
///
/// `belief_id` not found → a `kind = "missing"` root with a descriptive
/// label; never panics. For each `EvidenceRef::ToolOutput { id }`, the tree
/// includes a `tool_output` child (with `derived from` edge) and, when
/// `events.event(record.generating_event_id)` resolves, an `event` grandchild
/// (`generated by`). When the event lookup misses, a `missing` placeholder
/// tells the user the originating event isn't on the current branch's
/// stream.
pub fn provenance_for_belief(
    snapshot: &AgentSnapshot,
    belief_id: &BeliefId,
    events: &dyn EventLookup,
) -> ProvenanceNode {
    let Some(belief) = snapshot.beliefs().iter().find(|b| &b.id == belief_id) else {
        return ProvenanceNode {
            kind: "missing".to_string(),
            id: Some(belief_id.0.clone()),
            label: format!("belief {} not found on this snapshot", belief_id),
            edge: None,
            detail: None,
            children: vec![],
        };
    };

    let belief_label = format!(
        "{} {} {} (confidence={:.2}, status={:?})",
        belief.subject, belief.predicate, belief.object_value, belief.confidence, belief.status
    );

    let mut children = Vec::new();
    for reference in &belief.evidence {
        children.push(build_evidence_child(reference, events));
    }

    ProvenanceNode {
        kind: "belief".to_string(),
        id: Some(belief.id.0.clone()),
        label: belief_label,
        edge: None,
        detail: None,
        children,
    }
}

fn build_evidence_child(reference: &EvidenceRef, _events: &dyn EventLookup) -> ProvenanceNode {
    match reference {
        EvidenceRef::ToolOutput { tool_output_id } => {
            // The record itself isn't reachable here — we look it up via the
            // EventLookup. The CLI side will resolve it from the snapshot
            // when it walks; here we collapse the tool_output node into an
            // event-edged grandchild with the tool output id visible.
            ProvenanceNode {
                kind: "tool_output".to_string(),
                id: Some(tool_output_id.0.clone()),
                label: format!("tool_output:{}", tool_output_id),
                edge: Some("derived from".to_string()),
                detail: None,
                children: vec![],
            }
            // Note: in core, the record's full content (tool_name, success,
            // input, output) is owned by the caller; the CLI's
            // `cmd_inspect_belief` augments this node with the record's
            // detail and the originating event lookup. The core walker here
            // stays a pure data structure that knows nothing about
            // event stores.
        }
        EvidenceRef::Note { text } => ProvenanceNode {
            kind: "note".to_string(),
            id: None,
            label: text.clone(),
            edge: Some("noted as".to_string()),
            detail: None,
            children: vec![],
        },
    }
}

/// Augment a `tool_output` provenance node with the `ToolOutputRecord` and its
/// originating event. Used by the CLI's `inspect belief` to fill in the
/// `detail` field and attach the `generated by` grandchild.
///
/// Public so tests can exercise the augmentation path directly.
pub fn augment_tool_output_node(
    node: &mut ProvenanceNode,
    record: &ToolOutputRecord,
    events: &dyn EventLookup,
) {
    node.label = format!(
        "{} ({}, {})",
        record.tool_name,
        if record.success { "success" } else { "failed" },
        record.id
    );
    node.detail = Some(serde_json::json!({
        "tool_output_id": record.id,
        "tool_name": record.tool_name,
        "input": record.input,
        "output": record.output,
        "success": record.success,
        "created_at": record.created_at,
        "generating_event_id": record.generating_event_id,
    }));

    match events.event(&record.generating_event_id) {
        Some(event) => {
            node.children.push(ProvenanceNode {
                kind: "event".to_string(),
                id: Some(event.event_id.0.clone()),
                label: format!(
                    "{} seq={} branch={}",
                    event_type_label(&event.event_type),
                    event.sequence,
                    event
                        .branch_id
                        .as_ref()
                        .map(|b| b.0.clone())
                        .unwrap_or_default()
                ),
                edge: Some("generated by".to_string()),
                detail: Some(serde_json::json!({
                    "event_type": event_type_label(&event.event_type),
                    "sequence": event.sequence,
                    "timestamp": event.timestamp,
                    "causation_id": event.causation_id,
                    "payload": event.payload,
                })),
                children: vec![],
            });
        }
        None => {
            node.children.push(ProvenanceNode {
                kind: "missing".to_string(),
                id: Some(record.generating_event_id.0.clone()),
                label: format!(
                    "originating event {} not found on this branch's stream",
                    record.generating_event_id
                ),
                edge: Some("generated by".to_string()),
                detail: None,
                children: vec![],
            });
        }
    }
}
